### ISSUE TITLE
Downloading Selected NZBs Error: String Indicies Must be Integers

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#101]
Attempting to select multiple NZBs from multiple indexers, and then clicking `download selected` results in this error in the GUI:

```
an error occured :
500: INTERNAL SERVER ERROR

string indicies must be integers
```

And this error in the console:

```python
2016-01-11 22:49:14,822 - ERROR - web - string indices must be integers
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 188, in decorated
    return f(*args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 575, in internalapi_addnzb
    title = item["title"]
TypeError: string indices must be integers
```

Screenshot in case it's helpful:

![al-nzbhydra-stringindices](https://cloud.githubusercontent.com/assets/12164957/12256890/3a71018e-b8b6-11e5-850a-aa0408b49d7d.jpg)

I tried killing NZBHydra and restarting it, and then I also tried a hard reload in my browser, just to be sure this time ;)

By the way, as a related feature request, it might be nice to have Select All/Unselect All for the checkboxes, or maybe Inverse like how Binsearch does it.

**Comment by theotherp** [comment]
Yeah, unfortunately stuff like this tends to happen because I don't have any tests for interaction between frontend and backend. I test manually after I change something but it's easy to miss something :-(
