### ISSUE TITLE
Unknown literal error in parsing GUID when trying to download NZB

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#116]
I got this error today when I tried to send an nzb to nzbget from a Sonarr manual search.

```
2016-01-27 16:34:45,715 - DEBUG - web - http://localhost:5075/api?apikey=<APIKEY>&t=get&id=(guid:'http:%2F%2Flocalhost:5075%2Fapi%3Fapikey=<APIKEY>%26t=get%26id=(guid:!'http:%2F%2Flocalhost:5075%2Fapi%3Fapikey=<APIKEY>%2526t=get%2526id=(guid:!!!'634c0a68d89548be7778e8eea43a949e!!!',indexer:DogNZB,searchid:646,title:Duck.Dynasty.S09E02.720p.HDTV.x264-AAF)!',indexer:DogNZB,searchid:646,title:Duck.Dynasty.S09E02.720p.HDTV.x264-AAF)',indexer:DogNZB,searchid:646,title:Duck.Dynasty.S09E02.720p.HDTV.x264-AAF)
2016-01-27 16:34:45,716 - DEBUG - web - API request: {u'minsize': None, u'attrs': None, u'query': None, u'rid': None, u'id': u"(guid:'http://localhost:5075/api?apikey=<APIKEY>&t=get&id=(guid:!'http://localhost:5075/api?apikey=<APIKEY>%26t=get%26id=(guid:!!!'634c0a68d89548be7778e8eea43a949e!!!',indexer:DogNZB,searchid:646,title:Duck.Dynasty.S09E02.720p.HDTV.x264-AAF)!',indexer:DogNZB,searchid:646,title:Duck.Dynasty.S09E02.720p.HDTV.x264-AAF)',indexer:DogNZB,searchid:646,title:Duck.Dynasty.S09E02.720p.HDTV.x264-AAF)", u'dbsearchid': None, u'category': None, u'group': None, u'title': None, u'imdbid': None, u'maxage': None, u'indexer': None, u'ep': None, u'maxsize': None, u'input': None, u'indexers': None, u'extended': None, u'offsets': None, u'season': None, 'apikey':<APIKEY>', u'offset': 0, u'genre': None, u'minage': None, u'episode': None, u'tvdbid': None, u'o': None, u'cat': None, u'q': None, u'del': None, u't': u'get', u'limit': 100}
2016-01-27 16:34:45,716 - DEBUG - web - Query ID was not properly parsed. Converted it to (guid:!'http://localhost:5075/api?apikey=<APIKEY>&t=get&id=(guid:!!!'634c0a68d89548be7778e8eea43a949e!!!',indexer:DogNZB,searchid:646,title:Duck.Dynasty.S09E02.720p.HDTV.x264-AAF)!',indexer:DogNZB,searchid:646,title:Duck.Dynasty.S09E02.720p.HDTV.x264-AAF)',indexer:DogNZB,searchid:646,title:Duck.Dynasty.S09E02.720p.HDTV.x264-AAF)
2016-01-27 16:34:45,717 - ERROR - web - unknown literal: "!'"
Traceback (most recent call last):
  File "/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/nzbhydra/nzbhydra/web.py", line 311, in api
    args = rison.loads(args["id"])
  File "/nzbhydra/libs/rison/decoder.py", line 225, in loads
    return Parser().parse(s, format=format)
  File "/nzbhydra/libs/rison/decoder.py", line 34, in parse
    value = self.read_value()
  File "/nzbhydra/libs/rison/decoder.py", line 45, in read_value
    return self.parse_open_paren()
  File "/nzbhydra/libs/rison/decoder.py", line 120, in parse_open_paren
    v = self.read_value()
  File "/nzbhydra/libs/rison/decoder.py", line 43, in read_value
    return self.parse_bang()
  File "/nzbhydra/libs/rison/decoder.py", line 94, in parse_bang
    raise ParserException('unknown literal: "!' + c + '"')
ParserException: unknown literal: "!'"
```

**Comment by theotherp** [comment]
Ah shit. Yeah, that doesn't look right.

**Comment by judhat2** [comment]
The next available nzb in the list was successful. It was only that nzb. If that helps...

**Comment by theotherp** [comment]
The next one was also from DogNZB?

**Comment by judhat2** [comment]
No, the next one was from nzbgeek

**Comment by theotherp** [comment]
Ok, thanks.

**Comment by theotherp** [comment]
Sorry, I cannot reproduce this. Haven't ever seen that problem ever with a couple of dozen series in sonar running against hydra for weeks. Please report if this happens again, it might've just been a glitch (although I cannot explain how that could happen...).

**Comment by albino1** [comment]
This looks a lot like the error I had before and reported here:

https://github.com/theotherp/nzbhydra/issues/75#issuecomment-166420299

In my case I was using it manually and not with Sonarr.

**Comment by theotherp** [comment]
No, I don't think so. I've changed the implementation in the meantime and for me it works with either setting when accessing hydra from sonarr.

**Comment by theotherp** [comment]
Oh, wait a second.

**Comment by judhat2** [comment]
It's the only time that I have ever seen it, and I use nzbhydra with Sonarr often.  However, I can reproduce the error if I search for that episode using hydra's TV category search and select that specific nzb.  If I can give you anymore info to help you, please let me know.

**Comment by theotherp** [comment]
Weird, I did the same. I downloaded all 6 NZBs from DogNZB just fine.

Could you perhaps upload the content of your settings.cfg to pastebin and post the link here? If you want, remove any sensitive data like username, password, IP, API key.

You don't cache your search results, do you? If you do please delete all the cache files from the cache folder or restart hydra if you use in-memory cache and try again.

**Comment by judhat2** [comment]
Caching was enabled. I disabled it and restarted hydra.  I didn't find a cache folder anywhere inside nzbhydra's directory to delete.  I repeated the search and could reproduce the error again.  Here is my settings.cfg http://pastebin.com/kb33NBdc

Then, I enabled only dognzb and searched it again.  This time I could download that nzb. Weird.  I enabled all my indexers again and repeated the search. Again, I got the error from that nzb.

I tried one more thing.  I disabled dognzb and used all of my other indexers for that search. pfmonkey happened to be the top choice for that nzb then.  Got the same error from when tried to download from that indexer.

I noticed that with all of these searches, that green arrow box appeared next to that nzb when I checked to include duplicates.  However, clicking on the box did not show the duplicates from the other indexers.  The green arrow changed to point up, but no dropdown list appeared.  Strange.

**Comment by theotherp** [comment]
Uhm... no idea what's going on. But it's good to know that this only happens with multiple indexers enabled, I tested only with DogNZB, naturally.

**Comment by theotherp** [comment]
Concerning the failing expansion of the title group, you should be able to see a javascript error in the console (f12 / console) after clicking that button.

I can now reproduce that, yay :-/

**Comment by judhat2** [comment]
Not sure if you were asking for it or not, but here is the error I saw in the console. 
http://pastebin.com/zyBGs6HF

**Comment by theotherp** [comment]
Yeah, in some cases the duplicate detection doesn't work properly and messes up all the results. I'm now trying to reproduce that. I already managed to do so but for some reason I don't understand yet it only happens sometimes. But I have a hunch, at least.

**Comment by theotherp** [comment]
Do you have the "threaded server" enabled?

**Comment by judhat2** [comment]
Yes, I have been using hydra with that enabled

**Comment by theotherp** [comment]
Ok, unfortunartely I could reproduce the bug even with that option disabled.

This is definitely the most elusive bug I've had with this tool yet, but I *think* I got it. Will have to hit F5 a couple of hundred more times to find out -.-

**Comment by albino1** [comment]
FWIW, looking through my logs it seems like the three times I got it were all when I was doing some tests trying to send several NZBs to SABnzbd all at the exact same time, just clicking send down the row.  Unfortunately, I wasn't running the log in any sort of Debug mode so it mostly looks like the link I posted above just from three different indexers, but here they are in case they help:

https://gist.github.com/albino1/e4199378bff4897021fb

**Comment by theotherp** [comment]
I know what's the problem is, there's something wrong with the duplicate detection, probably the piece of code I spent the most work on and which I forget to understand the minute I stop working at...

**Comment by theotherp** [comment]
![Yesssss](https://i.imgur.com/Yz6C9GK.png)

Found and fixed it. Fuuuck me that was hard. Turns out that my duplicate detection would behave differently depending on in which order the results were processed. As one indexer is almost always faster than the other (in my case nzb.su faster than DogNZB) the results would come in in the same order and all was good. But when DogNZB was faster for once the order was different and then the duplication detection would get into trouble. That's what made it so hard to replicate - every time I had the wrong results I needed for debugging and would try again they would already be gone again.

Anyway, fix will come with the next push. At least I hope it fixes your problem...

**Comment by albino1** [comment]
Haha, glad you worked it out :)

**Comment by judhat2** [comment]
Awesome, great work!
