### ISSUE TITLE
ERROR - web - HTTPConnectionPool(host='127.0.0.1', port=8080): 

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#122]
Not sure what this is in relation to, but got it several times.  Judging by the IP and port it would look like it errored while sending a file to SABnzbd.

```python
2016-02-02 16:14:13,852 - ERROR - web - HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=5)
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 263, in wrapped_function
    return f(*args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 638, in internalapi_addnzb
    add_success = downloader.add_link(link, title, category)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\downloader.py", line 225, in add_link
    r = requests.get(f.tostr(), verify=False, timeout=5)
  File "C:\Program Files (x86)\NZBHydra\libs\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\libs\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\libs\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\NZBHydra\libs\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\libs\requests\adapters.py", line 435, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8080): Read timed out. (read timeout=5)
2016-02-02 16:14:44,288 - INFO - infos - Converting imdb value 158788 from tmdb 
```

NZB Hydra: 0.0.1a59

**Comment by theotherp** [comment]
Yeah, it cannot connect to your downloader. Don't think that's a bug...

**Comment by theotherp** [comment]
If you do think this is a bug because sab is actually online please reopen this but I'm not sure what I could do about it.

**Comment by albino1** [comment]
SAB was and is still definitely online.  I was using it at the same time via push from an indexer, and then when NZB Hydra was failing I just switched back over to NZBM.

Since upgrading to 0.0.1a59 I seem to be having trouble sending to SAB again, getting the WAIT error on that end.  Running Test Connection is successful, but nothing actually sends.

Here's my settings, though there's not much to look at:

![al-nzbhydra-sabsettings](https://cloud.githubusercontent.com/assets/12164957/12792852/90814b8e-ca62-11e5-9332-83f26af1c37d.jpg)

**Comment by theotherp** [comment]
No idea. I'll increase the timeout and log the used link in the next version. Until then try and switch the access type to Redirect.

**Comment by albino1** [comment]
Sorry, I've been out of town.  I just upgraded to 0.0.1a61 and can't seem to replicate it.  I'd say close it for now.
