### ISSUE TITLE
ERROR - web - u'indexerguid'

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#123]
Here's the Traceback:

```python
2016-02-02 16:15:25,957 - ERROR - web - u'indexerguid'
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 353, in api
    return extract_nzb_infos_and_return_response(args["indexer"], args["indexerguid"], args["title"], args["searchid"])
KeyError: u'indexerguid'
```

NZB Hydra: 0.0.1a59

**Comment by theotherp** [comment]
Some more context please...? What were you doing when it occurred?

**Comment by albino1** [comment]
Interestingly, I don't use the API, I only use it manually, but the log does report some sort of API error.  Maybe from some sort of failurelink request from SABnzbd?

Also, it reports 2 failed login attempts from my IP address, but there weren't any, just 1 successful remote login.

Here's a fuller log from before and after:

```python
2016-02-02 16:14:44,829 - WARNING - search_module - NZBCat: Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-02-02 16:14:44,841 - INFO - search_module - NZBCat: Query returned no results
2016-02-02 16:14:44,900 - INFO - search_module - PFMonkey: Query returned no results
2016-02-02 16:14:44,936 - INFO - search_module - Newztown: Query returned no results
2016-02-02 16:14:45,117 - ERROR - search_module - Unable to access NZBPlanet: Unknown error while trying to access the indexer.
2016-02-02 16:14:45,167 - INFO - search_module - DogNZB: Query returned no results
2016-02-02 16:14:45,418 - WARNING - search_module - PirateNZB: Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-02-02 16:14:45,418 - INFO - search_module - PirateNZB: Query returned no results
2016-02-02 16:14:45,766 - WARNING - search_module - NZBFinder: Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-02-02 16:14:45,769 - INFO - search_module - NZBFinder: Query returned no results
2016-02-02 16:14:45,783 - INFO - search_module - OZnzb: Query returned no results
2016-02-02 16:14:45,890 - INFO - binsearch - Last results count 0
2016-02-02 16:14:45,910 - INFO - search_module - nzbgeek: Query returned no results
2016-02-02 16:15:05,117 - ERROR - search_module - Error while connecting to URL https://althub.co.za/api?apikey=<APIKEY>&t=movie&extended=1&offset=0&limit=100&cat=2000&imdbid=2301039: HTTPSConnectionPool(host='althub.co.za', port=443): Read timed out. (read timeout=20)
2016-02-02 16:15:25,957 - INFO - web - API request to download Movie.Title.2013.720p-Group from Usenet Crawler
2016-02-02 16:15:25,957 - ERROR - web - u'indexerguid'
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 353, in api
    return extract_nzb_infos_and_return_response(args["indexer"], args["indexerguid"], args["title"], args["searchid"])
KeyError: u'indexerguid'
2016-02-02 16:22:02,552 - WARNING - web - IP 123.45.67.89 failed to authenticate. The last time was at 2016-02-03 00:21:02. This was his 1. failed login attempt
2016-02-02 16:23:02,592 - WARNING - web - IP 123.45.67.89 failed to authenticate. The last time was at 2016-02-03 00:22:02. This was his 2. failed login attempt
2016-02-02 23:04:07,946 - WARNING - search_module - DogNZB: Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-02-02 23:04:07,946 - INFO - search_module - DogNZB: Query returned no results
2016-02-02 23:04:08,039 - INFO - binsearch - Last results count 0
2016-02-02 23:04:08,085 - WARNING - search_module - NZBCat: Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-02-02 23:04:08,216 - ERROR - search_module - Unable to access NZBPlanet: Unknown error while trying to access the indexer.
2016-02-02 23:04:08,802 - WARNING - search_module - NZBFinder: Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-02-02 23:04:11,108 - WARNING - search_module - PirateNZB: Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-02-02 23:06:01,424 - WARNING - search_module - DogNZB: Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-02-02 23:06:01,424 - INFO - search_module - DogNZB: Query returned no results
```

**Comment by theotherp** [comment]
Please update to a60 and try again. If it still doesn't work:

You tried to add the download to sabnzbd? What do your downloader settings look like?

**Comment by theotherp** [comment]
Any news on this?

**Comment by albino1** [comment]
So I upgraded to a61 and added like 20 NZBs from a variety of indexers and all of them eventually arrived in SABnzbd with no error messages in NZBHydra.

They all say API requests even though they were all added manually, so I'm not sure if that's important, but it doesn't appear to be immediately broken anymore :)

Here's some output with no errors showing the "API requests":

```python
2016-02-09 15:30:00,526 - INFO - web - API request to download Show.Title.S01E
01.DVDRip.XviD-ORPHEUS-Obfuscated from nzbgeek
2016-02-09 15:30:01,507 - INFO - api - Returning downloaded NZB Show.Title.S01
E01.DVDRip.XviD-ORPHEUS-Obfuscated from nzbgeek
2016-02-09 15:30:32,848 - INFO - web - API request to download Show.Title.S01E
01.HebSub.HDTV.XviD-FuzePacks from NZBClub
2016-02-09 15:30:34,242 - INFO - api - Returning downloaded NZB Show.Title.S01
E01.HebSub.HDTV.XviD-FuzePacks from NZBClub
```

**Comment by theotherp** [comment]
It says "API request" because it uses the API (and API key) to download the NZB instead of the internal route which needs authentication (if enabled). Don't let the wording confuse you :-)

**Comment by albino1** [comment]
Ah, thanks for the clarification, makes sense :)
