### ISSUE TITLE
Error: 'unicode' object has no attribute 'isSetting'

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#136]
I am getting this error when I try to send an NZB to nzbget. I have tried different combinations of the NZB access and adding types, but I get the error everytime.  
```
2016-02-20 15:28:02,265 - ERROR - web - 'unicode' object has no attribute 'isSetting'
Traceback (most recent call last):
  File "/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nzbhydra/nzbhydra/web.py", line 272, in wrapped_function
    return f(*args, **kwargs)
  File "/nzbhydra/nzbhydra/web.py", line 889, in internalapi_getcategories
    if config.settings.downloader.downloader.isSetting(config.settings.DownloaderSelection.nzbget):
AttributeError: 'unicode' object has no attribute 'isSetting'
```

**Comment by theotherp** [comment]
That's caused by the config rewrite, which I feared would break a lot of things. I've been saying this for months but I really need to increase my test coverage...

**Comment by judhat2** [comment]
Thanks again!
