### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sqlite_version_info'

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#158]
I updated to version d695797 and couldn't start nzbhydra, because I had python version 2.7.6.  So I upgraded to 2.7.11.  Now I get this error when I try to start nzbhyrdra.  Is this an error on my end somewhere?

```
user@HTPC:~# python nzbhydra/nzbhydra.py --daemon
Setting base path to nzbhydra
Traceback (most recent call last):
  File "nzbhydra/nzbhydra.py", line 30, in <module>
    from nzbhydra import indexers
  File "nzbhydra/nzbhydra/indexers.py", line 13, in <module>
    from nzbhydra import config, database
  File "nzbhydra/nzbhydra/database.py", line 17, in <module>
    from playhouse.sqlite_ext import SqliteExtDatabase
  File "nzbhydra/libs/playhouse/sqlite_ext.py", line 74, in <module>
    FTS_VER = sqlite3.sqlite_version_info[:3] >= (3, 7, 4) and 'FTS4' or 'FTS3'
AttributeError: 'NoneType' object has no attribute 'sqlite_version_info'
```
I also tested my sqlite version to check if I have over 3.7.4
```
user@HTPC:~# sqlite3 --version
3.8.2 2013-12-06 14:53:30
```

**Comment by theotherp** [comment]
Please check if you have a file "_sqlite3.lib" in your python27\libs folder

**Comment by judhat2** [comment]
Thanks. It wasn't there.  I don't understand it, but I when I compiled python I did `make install` instead of `make altinstall`.  All is good now.
