### ISSUE TITLE
URL Base Causing "Cannot Read property 'replace' of undefined

### ISSUE THREAD

**Issue by imadunatic** [theotherp/nzbhydra#164]
Updated to the latest yesterday and Hydra will only load the logo. Finally traced it down to setting a url base (copied and pasted line by line from working cfg file to mine and this is definitely the culprit), if I remove the URL base from the cfg it loads fine. 

```
2016-02-28 08:50:37,308 - INFO - nzbhydra - Started
2016-02-28 08:50:37,308 - INFO - config - Found obsolete setting root.indexers.womble.generate_queries and will remove it
2016-02-28 08:50:37,308 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-02-28 08:50:37,308 - INFO - indexers - Loading indexer Binsearch
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer NZBIndex
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer NZBClub
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer Womble
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer DogNZB
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer OZNZB
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer PFMonkey
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer Althub
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer Dusky
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer 6box
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer 6box nzedb
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer 6box nntmux
2016-02-28 08:50:37,308 - INFO - indexers - Loaded indexer Drunken Slug
2016-02-28 08:50:37,308 - INFO - nzbhydra - Starting web app on 0.0.0.0:9846
2016-02-28 08:50:37,308 - INFO - nzbhydra - Go to https://theleiterhouse.duckdns.org/nzbhydra/ for the frontend
2016-02-28 08:50:49,023 - ERROR - web - The client encountered the following error: TypeError: Cannot read property 'replace' of undefined
at trimEmptyHash (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:21376:13)
at $LocationProvider.$get (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:22206:9)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13815:19)
at $LocationProvider.origProvider.$get (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13687:43)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13815:19)
at http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13614:37
at getService (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13761:39)
at injectionArgs (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13785:58)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13807:18)
at http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13614:37. Caused by: No known cause
2016-02-28 08:50:49,040 - ERROR - web - The client encountered the following error: TypeError: Cannot read property 'replace' of undefined
at trimEmptyHash (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:21376:13)
at $LocationProvider.$get (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:22206:9)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13815:19)
at $LocationProvider.origProvider.$get (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13687:43)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13815:19)
at http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13614:37
at getService (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13761:39)
at injectionArgs (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13785:58)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13807:18)
at http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13614:37. Caused by: No known cause
2016-02-28 08:50:49,043 - ERROR - web - The client encountered the following error: TypeError: Cannot read property 'replace' of undefined
at trimEmptyHash (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:21376:13)
at $LocationProvider.$get (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:22206:9)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13815:19)
at $LocationProvider.origProvider.$get (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13687:43)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13815:19)
at http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13614:37
at getService (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13761:39)
at injectionArgs (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13785:58)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13807:18)
at http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13614:37. Caused by: No known cause
2016-02-28 08:50:49,046 - ERROR - web - The client encountered the following error: TypeError: Cannot read property 'replace' of undefined
at trimEmptyHash (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:21376:13)
at $LocationProvider.$get (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:22206:9)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13815:19)
at $LocationProvider.origProvider.$get (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13687:43)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13815:19)
at http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13614:37
at getService (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13761:39)
at injectionArgs (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13785:58)
at Object.invoke (http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13807:18)
at http://192.168.1.21:9846/nzbhydra/static/js/alllibs.js:13614:37. Caused by: No known cause
2016-02-28 08:50:49,119 - INFO - update - git output: 'git' is not recognized as an internal or external command,

operable program or batch file.
2016-02-28 08:50:49,121 - ERROR - update - git version returned : 'git' is not recognized as an internal or external command,

operable program or batch file.
2016-02-28 08:50:49,131 - ERROR - update - Unable to find working git command
```

Any chance this is a config error? I'm only trying to access hydra locally at local ip:port which is how I've been accessing it locally all along. I don't think the URL base would affect this, but I'll admit I'm a little green with the proxy stuff...

**Comment by theotherp** [comment]
If you have a base URL set you need to use it when calling hydra. Call the reverse proxy not the local address.

**Comment by imadunatic** [comment]
Good lord... do you ever feel like you're herding cats? I was using the local ip:port since the dawn of time, I'm assuming it was a happy accident this was working before?

Either way, thanks again. Working great.

**Comment by theotherp** [comment]
I changed the implementation of the base URL thingy with 8a5620e93b9c148c99e863095aed6168773422a2 so that other reverse proxies than apache and nginx (e.g. IIS) would work better.

Glad it's working now.
