### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by KrunchMuffin** [theotherp/nzbhydra#165]
I have the latest release. THis was working originally, I just did a Pull and it is not working now.

> 2016-03-01 15:51:07,160 - ERROR - web - The client encountered the following error: TypeError: Cannot read property 'replace' of undefined
at trimEmptyHash (http://127.0.0.1:5075/hydra/static/js/alllibs.js:21376:13)
at $LocationProvider.$get (http://127.0.0.1:5075/hydra/static/js/alllibs.js:22206:9)
at Object.invoke (http://127.0.0.1:5075/hydra/static/js/alllibs.js:13815:19)
at $LocationProvider.origProvider.$get (http://127.0.0.1:5075/hydra/static/js/alllibs.js:13687:43)
at Object.invoke (http://127.0.0.1:5075/hydra/static/js/alllibs.js:13815:19)
at http://127.0.0.1:5075/hydra/static/js/alllibs.js:13614:37
at getService (http://127.0.0.1:5075/hydra/static/js/alllibs.js:13761:39)
at injectionArgs (http://127.0.0.1:5075/hydra/static/js/alllibs.js:13785:58)
at Object.invoke (http://127.0.0.1:5075/hydra/static/js/alllibs.js:13807:18)
at http://127.0.0.1:5075/hydra/static/js/alllibs.js:13614:37. Caused by: No known cause

**Comment by theotherp** [comment]
You using a reverse proxy?

**Comment by KrunchMuffin** [comment]
Yes, but got error locally

**Comment by theotherp** [comment]
Call the proxy's address

**Comment by theotherp** [comment]
See https://github.com/theotherp/nzbhydra/issues/164

**Comment by theotherp** [comment]
I'll check tonight why using the local address doesn't work anymore when having set a base URL.

**Comment by theotherp** [comment]
Works fine for me when having set a base URL and calling the local URL like "http://127.0.0.1:5075/nzbydra" with a base URL of "/nzbhydra".
