### ISSUE TITLE
missing ',' error

### ISSUE THREAD

**Issue by kylerw** [theotherp/nzbhydra#167]
Mylar is trying to download the nzb file and send to NZBGet and receiving: 

Unable to download nzb from link: http://192.168.1.188:5075/api?apikey=APIKEYHERE&t=get&id=%28indexer%3Anzb.su%2Cindexerguid%3Af6315d32c23c24a7ef2f29a9e4a3f920%2Csearchid%3A4989%2Ctitle%3A%27Spider-Man-Deadpool%2B001%2B%282016%29%2B%28Digital%29%2B%28Zone-EMPIRE%27 [http://kylerw.com/nzbhydra/getnzb?apikey=APIKEYHERE&id=(indexer:nzb.su,indexerguid:f6315d32c23c24a7ef2f29a9e4a3f920,searchid:4989,title:'Spider-Man-Deadpool+001+(2016)+(Digital)+(Zone-EMPIRE')]

NZBHydra shows:

2016-03-03 12:58:38,302 - ERROR - web - missing ','
Traceback (most recent call last):
  File "/config/hydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/config/hydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/config/hydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/config/hydra/nzbhydra/web.py", line 344, in api
    args = rison.loads(args["id"])
  File "/config/hydra/libs/rison/decoder.py", line 225, in loads
    return Parser().parse(s, format=format)
  File "/config/hydra/libs/rison/decoder.py", line 34, in parse
    value = self.read_value()
  File "/config/hydra/libs/rison/decoder.py", line 45, in read_value
    return self.parse_open_paren()
  File "/config/hydra/libs/rison/decoder.py", line 111, in parse_open_paren
    raise ParserException("missing ','")
ParserException: missing ','

I've tried using the local IP or the external (behind proxy) url and both receive this error.

**Comment by kylerw** [comment]
Looking at this, it appears it is most likely a Mylar error? Right?

**Comment by theotherp** [comment]
I don' know what Mylar is, so no idea ;-)

**Comment by kylerw** [comment]
Just got confirmation Mylar isn't supporting NZBHydra yet.

FYI: Comics --> https://github.com/evilhero/mylar/
