### ISSUE TITLE
Add a url link to the TVrage ID on the search history page

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#171]
![image](https://cloud.githubusercontent.com/assets/3536802/13814425/8b22013c-ebc9-11e5-8d5d-7e812905387c.png)

I know this isn't a big deal or a priority, but I noticed that the TVrage ID on the search history page didn't give a link that goes to the show's url like it does for imdb or tvdb.  Sonarr uses this id, so I see it a lot in the history.  TVmaze's api can convert it and give a url to their website.

Maybe you can implement it.  This code gets the url for Game of Thrones from it's TVrage id.

```python
import json
try:
    # For Python 3.0 and later
    from urllib.request import urlopen
except ImportError:
    # Fall back to Python 2's urllib2
    from urllib2 import urlopen

def get_tvmaze_link(url):
    """Receive the content of url, parse it as JSON and return the tvmaze link."""
    content = urlopen(url).read()
    try:
        data = json.loads(content)
    except:
        data = json.loads(content.decode('utf8'))
    return data["url"]

# Game of Thrones TVrage id
rid = 24493
link = get_tvmaze_link("http://api.tvmaze.com/lookup/shows?tvrage=" + str(rid))
```

**Comment by judhat2** [comment]
I just saw that you have pytvmaze in your libs. I guess it would be simpler to use it. 
```python
import pytvmaze
rid = 24493
url = pytvmaze.get_show(tvrage_id=rid).url
```

**Comment by theotherp** [comment]
Good idea!

**Comment by judhat2** [comment]
Thanks for implementing this.  However, the first time I click on a specific rid link, I get this error.  But every time after that, clicking that specific rid successfully takes me to the corresponding tvdb website.
```
2016-03-29 00:26:59,730 - DEBUG - web - Redirect TVRage id request
2016-03-29 00:26:59,730 - INFO - infos - Converting from tvrage value 4284 to tvdb 
2016-03-29 00:26:59,733 - INFO - infos - Requesting info for tvrage key 4284 from TVMaze
2016-03-29 00:27:01,634 - INFO - infos - Successfully converted from tvrage value 4284 to tvdb 
2016-03-29 00:27:01,636 - ERROR - web - encode method has been disabled in newbytes
Traceback (most recent call last):
  File "/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nzbhydra/nzbhydra/web.py", line 267, in wrapped_function
    return f(*args, **kwargs)
  File "/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/nzbhydra/nzbhydra/web.py", line 793, in internalapi_redirect_rid
    return redirect("https://thetvdb.com/?tab=series&id=" + tvdbid)
  File "/nzbhydra/libs/werkzeug/utils.py", line 366, in redirect
    location = iri_to_uri(location, safe_conversion=True)
  File "/nzbhydra/libs/werkzeug/urls.py", line 659, in iri_to_uri
    ascii_iri = to_native(iri).encode('ascii')
  File "/nzbhydra/libs/future/types/newbytes.py", line 366, in __getattribute__
    raise AttributeError("encode method has been disabled in newbytes")
AttributeError: encode method has been disabled in newbytes
2016-03-29 00:27:01,884 - DEBUG - web - Sending index.html
```

**Comment by theotherp** [comment]
Ah yes, sorry.
