### ISSUE TITLE
Error - object has no attribute

### ISSUE THREAD

**Issue by tzortst** [theotherp/nzbhydra#172]
Hey new setup, getting the following error for all searches, I've tried with only using the built in indexers but get the same error for each indexer.

Searched the issues but couldn't find anything related.

```
2016-03-17 14:38:48,572 - ERROR - search_module - Error while processing search results from indexer OZ Nzb
Traceback (most recent call last):
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 306, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\searchmodules\newznab.py", line 494, in process_query_result
    accepted, reason = self.accept_result(entry, searchRequest, self.supportedFilters)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 177, in accept_result
    if searchRequest.pubdate_utc is None:
AttributeError: 'SearchRequest' object has no attribute 'pubdate_utc'
2016-03-17 14:38:49,437 - ERROR - search_module - Error while processing search results from indexer PF Monkey
Traceback (most recent call last):
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 306, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\searchmodules\newznab.py", line 494, in process_query_result
    accepted, reason = self.accept_result(entry, searchRequest, self.supportedFilters)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 177, in accept_result
    if searchRequest.pubdate_utc is None:
AttributeError: 'SearchRequest' object has no attribute 'pubdate_utc'
2016-03-17 14:38:49,516 - ERROR - search_module - Error while processing search results from indexer nzbCat
Traceback (most recent call last):
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 306, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\searchmodules\newznab.py", line 494, in process_query_result
    accepted, reason = self.accept_result(entry, searchRequest, self.supportedFilters)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 177, in accept_result
    if searchRequest.pubdate_utc is None:
AttributeError: 'SearchRequest' object has no attribute 'pubdate_utc'
2016-03-17 14:38:49,825 - INFO - binsearch - Last results count 0
2016-03-17 14:38:49,936 - ERROR - search_module - Error while processing search results from indexer NZBs.org
Traceback (most recent call last):
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 306, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\searchmodules\newznab.py", line 494, in process_query_result
    accepted, reason = self.accept_result(entry, searchRequest, self.supportedFilters)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 177, in accept_result
    if searchRequest.pubdate_utc is None:
AttributeError: 'SearchRequest' object has no attribute 'pubdate_utc'
2016-03-17 14:38:50,069 - ERROR - search_module - Error while processing search results from indexer Binsearch
Traceback (most recent call last):
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 306, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\searchmodules\binsearch.py", line 208, in process_query_result
    accepted, reason = self.accept_result(entry, searchRequest, self.supportedFilters)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 177, in accept_result
    if searchRequest.pubdate_utc is None:
AttributeError: 'SearchRequest' object has no attribute 'pubdate_utc'
2016-03-17 14:38:50,717 - ERROR - search_module - Error while processing search results from indexer NZBClub
Traceback (most recent call last):
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 306, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\searchmodules\nzbclub.py", line 249, in process_query_result
    accepted, reason = self.accept_result(entry, searchRequest, self.supportedFilters)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 177, in accept_result
    if searchRequest.pubdate_utc is None:
AttributeError: 'SearchRequest' object has no attribute 'pubdate_utc'
2016-03-17 14:38:50,744 - ERROR - search_module - Error while processing search results from indexer nzbGeek
Traceback (most recent call last):
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 306, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\searchmodules\newznab.py", line 494, in process_query_result
    accepted, reason = self.accept_result(entry, searchRequest, self.supportedFilters)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 177, in accept_result
    if searchRequest.pubdate_utc is None:
AttributeError: 'SearchRequest' object has no attribute 'pubdate_utc'
2016-03-17 14:38:51,247 - ERROR - search_module - Error while processing search results from indexer NZBIndex
Traceback (most recent call last):
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 306, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\searchmodules\nzbindex.py", line 218, in process_query_result
    accepted, reason = self.accept_result(entry, searchRequest, self.supportedFilters)
  File "C:\Program Files (x86)\nzbhydra\nzbhydra\search_module.py", line 177, in accept_result
    if searchRequest.pubdate_utc is None:
AttributeError: 'SearchRequest' object has no attribute 'pubdate_utc'
```

**Comment by theotherp** [comment]
Oops, sorry about that.

**Comment by tzortst** [comment]
Awesome, thanks heaps works a treat :+1:
