### ISSUE TITLE
KeyError: u'indexer_search'

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#175]
I got this error when doing a movie search for 'Déjà Vu'. I tried several movies with those special characters, and they all got an error.  I searched for them using the IMDB autocomplete.
[nzbhydra-debuginfo-2016-03-26-13-02.zip](https://github.com/theotherp/nzbhydra/files/190347/nzbhydra-debuginfo-2016-03-26-13-02.zip)

```
Traceback (most recent call last):
  File "/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nzbhydra/nzbhydra/web.py", line 267, in wrapped_function
    return f(*args, **kwargs)
  File "/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/nzbhydra/nzbhydra/web.py", line 493, in internalapi_moviesearch
    return startSearch(search_request)
  File "/nzbhydra/nzbhydra/web.py", line 426, in startSearch
    return process_and_jsonify_for_internalapi(results)
  File "/nzbhydra/nzbhydra/web.py", line 418, in process_and_jsonify_for_internalapi
    results = process_for_internal_api(results)
  File "/nzbhydra/nzbhydra/api.py", line 167, in process_for_internal_api
    indexer_search_info = IndexerSearchSchema().dump(indexer_info["indexer_search"]).data
KeyError: u'indexer_search'
```

**Comment by judhat2** [comment]
Thanks!
