### ISSUE TITLE
error from CouchPotato's nzb information link

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#180]
When I click this red 'i' from within CouchPotato's search results, I get this error.  Usually, that button is a link to the details of that nzb on the server's website.  Now it just goes to a white web page that says "guid". I tried a few different movies with the same result every time. In Sonarr, the link to the nzb's detail page works fine.  Maybe it's a CouchPotato problem?
![image](https://cloud.githubusercontent.com/assets/3536802/14212731/391ded08-f86f-11e5-9161-667f084e19a3.png)

```
2016-04-02 00:59:04,651 - ERROR - web - u'guid'
Traceback (most recent call last):
  File "/root/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/nzbhydra/nzbhydra/web.py", line 262, in wrapped_function
    return f(*args, **kwargs)
  File "/root/nzbhydra/nzbhydra/web.py", line 438, in get_details
    details_link = get_details_link(d["indexer"], d["guid"])
KeyError: u'guid'
2016-04-02 00:59:04,911 - DEBUG - web - Sending index.html
```

**Comment by theotherp** [comment]
Fixed in next release, thanks for the report.

**Comment by judhat2** [comment]
Thanks!
