### ISSUE TITLE
500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by hctancredi** [theotherp/nzbhydra#192]
Hi!

I saw that "500: INTERNAL SERVER ERROR" error message was fixed some time ago, but today I got it while using with Lazy Librarian.

Anything that I am missing or maybe it's a new error?

thanks

**Comment by theotherp** [comment]
That can be all kinds of things, I need more info.

**Comment by hctancredi** [comment]
What logs do you need?

**Comment by judhat2** [comment]
![image](https://cloud.githubusercontent.com/assets/3536802/14581864/e2d036b6-0432-11e6-9e7c-3f44fabbc4bd.png)

**Comment by hctancredi** [comment]
[logfile.txt](https://github.com/theotherp/nzbhydra/files/222338/logfile.txt)

**Comment by judhat2** [comment]
I saw this error several times:
```
2016-04-16 12:16:04,328 - ERROR - web - invalid literal for long() with base 10: '02/08'
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 380, in api
    return api_search(args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 406, in api_search
    search_request.episode = int(args["episode"]) if args["episode"] else None
  File "/opt/nzbhydra/libs/future/types/newint.py", line 76, in __new__
    return super(newint, cls).__new__(cls, val)
ValueError: invalid literal for long() with base 10: '02/08'
```

**Comment by theotherp** [comment]
What are you doing when this error occurs?

**Comment by hctancredi** [comment]
Most of the errors I've faced lately happened while using LL  Force search or regular search.

**Comment by theotherp** [comment]
Sorry, forgot the LL part. Won't be able to analyze this until in two weeks or so.

**Comment by hctancredi** [comment]
That's OK. I won't be able to test anything either, I'm away from home and had to shut down my server. 

We can get back to it in 2-3 weeks.

**Comment by proxenus** [comment]
I'm also hitting a 500 internal server error but mine is keeping me from loading the page at all. I'm replying here in case it's related but I'm not sure myself. I haven't made any settings changes in a month or so and this started in the past few days some time.

Loading settings from /opt/nzbhydra/settings.cfg
2016-04-19 18:59:40,882 - INFO - nzbhydra - Started
2016-04-19 18:59:40,882 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-04-19 18:59:40,884 - INFO - indexers - Loaded indexer .......
2016-04-19 18:59:40,893 - INFO - nzbhydra - Debug mode enabled
2016-04-19 18:59:40,893 - INFO - nzbhydra - Starting web app on 0.0.0.0:5070
2016-04-19 18:59:40,894 - INFO - nzbhydra - Go to http://127.0.0.1:5070 for the frontend
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/nzbhydra/nzbhydra/web.py", line 71, in __call__
    return self.app(environ, start_response)
  File "/opt/nzbhydra/libs/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/nzbhydra/libs/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/nzbhydra/libs/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/opt/nzbhydra/libs/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/opt/nzbhydra/libs/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/opt/nzbhydra/libs/flask_session/sessions.py", line 337, in save_session
    total_seconds(app.permanent_session_lifetime))
  File "/opt/nzbhydra/libs/werkzeug/contrib/cache.py", line 694, in set
    self._prune()
  File "/opt/nzbhydra/libs/werkzeug/contrib/cache.py", line 650, in _prune
    expires = pickle.load(f)
EOFError

**Comment by theotherp** [comment]
No it isn't. If there are folders named cache and/or session, delete them and try again.

**Comment by proxenus** [comment]
removing nzbhydra/flask_session fixed my issue. Best of luck OP.
