### ISSUE TITLE
Stats page not found

### ISSUE THREAD

**Issue by blindpet** [theotherp/nzbhydra#2]
Throws a 404 pop up error on load despite stats page being there in the background

`GET http://192.168.60.134:5050/static/html/directives/indexer-statuses.html 404 (NOT FOUND)(anonymous function) @ angular.js:10722sendReq @ angular.js:10515serverRequest @ angular.js:10222processQueue @ angular.js:14745(anonymous function) @ angular.js:14761Scope.$eval @ angular.js:15989Scope.$digest @ angular.js:15800Scope.$apply @ angular.js:16097(anonymous function) @ angular.js:17864completeOutstandingRequest @ angular.js:5507(anonymous function) @ angular.js:5784
angular.js:12477 Error: [$compile:tpload] Failed to load template: static/html/directives/indexer-statuses.html (HTTP status: 404 NOT FOUND)
http://errors.angularjs.org/1.4.7/$compile/tpload?p0=static%2Fhtml%2Fdirectives%2Findexer-statuses.html&p1=404&p2=NOT%20FOUND
    at http://192.168.60.134:5050/static/js/alllibs.js:9279:12
    at handleError (http://192.168.60.134:5050/static/js/alllibs.js:26887:17)
    at processQueue (http://192.168.60.134:5050/static/js/alllibs.js:23956:28)
    at http://192.168.60.134:5050/static/js/alllibs.js:23972:27
    at Scope.$eval (http://192.168.60.134:5050/static/js/alllibs.js:25200:28)
    at Scope.$digest (http://192.168.60.134:5050/static/js/alllibs.js:25011:31)
    at Scope.$apply (http://192.168.60.134:5050/static/js/alllibs.js:25308:24)
    at done (http://192.168.60.134:5050/static/js/alllibs.js:19757:47)
    at completeRequest (http://192.168.60.134:5050/static/js/alllibs.js:19955:7)
    at XMLHttpRequest.requestLoaded (http://192.168.60.134:5050/static/js/alllibs.js:19896:9) undefined`

**Comment by theotherp** [comment]
Fixed with a77f2d82b51139b89751fbf8f7f9d58725b35419
