### ISSUE TITLE
Testing Indexers for NZBHydra Compatibility

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#20]
I went through a large list of indexers to see which ones worked or failed with NZBHydra.  Most of them worked, and of the ones that failed the only one I'm concerned about having trouble with is DOGnzb, for which I'm going to start a new Issue.

I started out testing the age and size filters with each indexer, but then it looked like you were just filtering those locally, so I stopped.  If you're actually querying the indexer with those filters, then let me know and I can do some more testing.

Here's the list:

Indexer | Result
------------ | -------------
NZBGeek | Good
PFMonkey | Good
Usenet Crawler | Good
OZNZB | Good
PirateNZB | Fails, even using a direct link to `/api?t=search` fails.  NZBM had similar problems with this indexer, so it's probably just broken.
NZBFinder | Good
NewzTown | Good
NZBPlanet | Good
DrunkenSlug | Good
AltHub | Good
LuluNZB | Good
NZB.is | Good
NZBSooti | Good (works now I guess?)
6box | Good
NZB.su | Fails.  When testing connection it says `Unable to connect to host`, then when I run a search anyway I get: `Connection failed: 403 Client Error: Forbidden for url: https://api.nzb.su/api?apikey=<API KEY>&limit=100&t=search&extended=1&offset=0&q=searchterm` ... Works in NZBM though.
NZBID | Fails, but I think this site is just broken overall.  I can't even get the search on the site to return any results.
NZBCat | Works
Dusky Deep Cave | Works
NZBTV | Works
DUTPlanet | Fails.  This a SpotWeb indexer that claims to have a Newznab-style API, but I've never been able to get it to work.  There's posts in places like Sonarr forums where people are using it, but it doesn't work with NZBM or NZBHydra so far as I can tell.

**Comment by theotherp** [comment]
Thank you so much for the tests.

The only filter I use in a query is maxage as that is the only filter that NN+ supports.

I personally use DogNZB for testing and it usually worked, so I don't know what's going on. 

Will try to get accounts for NZB.su and DUTPlanet for testing.

**Comment by theotherp** [comment]
Can't get into PirateNZB or get API access in nzb.su without donating which I'm currently unwilling to do as I have all the indexers I need. I would need an API key (for a couple of days or so) to do some testing.

**Comment by PirateNZB** [comment]
Works with PirateNZB now

**Comment by theotherp** [comment]
Awesome @PirateNZB

**Comment by albino1** [comment]
Confirmed, it's working in NZBHydra now.  Thanks @PirateNZB!

**Comment by spants** [comment]
local spotweb does not work:

2016-01-25 19:54:04,881 - ERROR - search_module - Error while processing search results from indexer spotweb
Traceback (most recent call last):
  File "/config/hydra/nzbhydra/search_module.py", line 285, in execute_queries
    parsed_results = self.process_query_result(request.content)
  File "/config/hydra/nzbhydra/searchmodules/newznab.py", line 377, in process_query_result
    description = item.find("description").text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by theotherp** [comment]
Can you post a sample API search result XML from spotweb?

**Comment by theotherp** [comment]
@spants Please open a new issue and include relevant info. Does this affect all search results from spotweb or only some, meaning do you get some results or not at all? Please provide the full XML.

**Comment by spants** [comment]
No results at all in Hydra.
I have opened a new issue

**Comment by judhat2** [comment]
> Works with PirateNZB now

@PirateNZB Did PirateNZB stop working for anyone else? It was working before, but now I am getting this error now when trying to search with them.  `Unable to access PirateNzb: Unknown error while trying to access the indexer.`

**Comment by albino1** [comment]
Just tried it and it worked for me.

**Comment by judhat2** [comment]
> Just tried it and it worked for me.

Thanks.  It was my mistake.  I was above my API limit of 5.  I thought I had paid for a VIP...

**Comment by theotherp** [comment]
I'll try and make a better error message for that case. The indexer's shown error message might be different from what others show, so hydra may not recognize this particular message.

**Comment by theotherp** [comment]
I'll try and make a better error message for that case. The indexer's shown error message might be different from what others show, so hydra may not recognize this particular message.

**Comment by DariusIII** [comment]
Also works with Tabula Rasa.

**Comment by piwi3910** [comment]
anyway how to get nzb.su to work.
Seems not to do anything then crash the whole service.
this is what happens with nzb.su activated:

2017-02-18 01:00:24,552 - INFO - nzbhydra - MainThread - Loading database file /config/hydra/nzbhydra.db
2017-02-18 01:00:24,561 - INFO - nzbhydra - MainThread - Starting db
2017-02-18 01:00:24,567 - INFO - indexers - MainThread - Activated indexer anizb
2017-02-18 01:00:24,573 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-02-18 01:00:24,579 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-02-18 01:00:24,585 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-02-18 01:00:24,598 - INFO - webaccess - MainThread - Using proxy settings: http=http://proxy.watteel.local:8080, https=http://proxy.watteel.local:8080 (username and password not shown)
2017-02-18 01:00:24,599 - INFO - webaccess - MainThread - Proxy will be disabled for accesses to localhost and 192.168.*.* addresses
2017-02-18 01:00:24,604 - NOTICE - nzbhydra - MainThread - Starting web app on 127.0.0.1:5075
2017-02-18 01:00:24,605 - NOTICE - nzbhydra - MainThread - Go to http://127.0.0.1:5075 for the frontend
2017-02-18 01:00:24,608 - INFO - web - MainThread - Running threaded server
2017-02-18 01:00:24,617 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "/opt/hydra/nzbhydra.py", line 200, in run
    web.run(host, port, basepath)
  File "/opt/hydra/nzbhydra/web.py", line 1474, in run
    app.run(host=host, port=port, debug=config.settings.main.debug, threaded=config.settings.main.runThreaded, use_reloader=config.settings.main.flaskReloader)
  File "/opt/hydra/libs/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/opt/hydra/libs/werkzeug/serving.py", line 625, in run_simple
    inner()
  File "/opt/hydra/libs/werkzeug/serving.py", line 603, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/opt/hydra/libs/werkzeug/serving.py", line 506, in make_server
    passthrough_errors, ssl_context)
  File "/opt/hydra/libs/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/opt/hydra/libs/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/opt/hydra/libs/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/opt/hydra/libs/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/opt/hydra/libs/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
2017-02-18 01:00:24,626 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-18 01:00:24,628 - INFO - nzbhydra - Dummy-3 - Database shut down

**Comment by theotherp** [comment]
Please open an issue. That's not related to the matter here.

**Comment by DariusIII** [comment]
I see you have NZBSooti on the list. As far as i know that site is dead.

**Comment by theotherp** [comment]
Then remove it, it's a wiki ;-)

**Comment by DariusIII** [comment]
Oh, damn, my bad. :)
