### ISSUE TITLE
Search error: indexerapiaccess.indexer_id / database is locked

### ISSUE THREAD

**Issue by petersw730** [theotherp/nzbhydra#202]
I'm using the latest build, but most searches end with an error of:

500: INTERNAL SERVER ERROR

NOT NULL constraint failed: indexerapiaccess.indexer_id

Looking at the Logs, I see:

2016-04-29 09:53:17,196 - ERROR - web - NOT NULL constraint failed: indexerapiaccess.indexer_id
Traceback (most recent call last):
  File "/Users/pstwecker/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/pstwecker/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/pstwecker/nzbhydra/nzbhydra/web.py", line 262, in wrapped_function
    return f(*args, **kwargs)
  File "/Users/pstwecker/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/Users/pstwecker/nzbhydra/nzbhydra/web.py", line 498, in internalapi_search
    return startSearch(search_request)
  File "/Users/pstwecker/nzbhydra/nzbhydra/web.py", line 468, in startSearch
    results = search.search(True, search_request)
  File "/Users/pstwecker/nzbhydra/nzbhydra/search.py", line 233, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "/Users/pstwecker/nzbhydra/nzbhydra/search.py", line 304, in search_and_handle_db
    result.indexerApiAccessEntry.save()
  File "/Users/pstwecker/nzbhydra/nzbhydra/database.py", line 108, in save
    super(IndexerApiAccess, self).save(*args, **kwargs)
  File "/Users/pstwecker/nzbhydra/libs/peewee.py", line 4680, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/Users/pstwecker/nzbhydra/libs/peewee.py", line 3213, in execute
    cursor = self._execute()
  File "/Users/pstwecker/nzbhydra/libs/peewee.py", line 2628, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Users/pstwecker/nzbhydra/libs/peewee.py", line 3461, in execute_sql
    self.commit()
  File "/Users/pstwecker/nzbhydra/libs/peewee.py", line 3285, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Users/pstwecker/nzbhydra/libs/peewee.py", line 3454, in execute_sql
    cursor.execute(sql, params or ())
IntegrityError: NOT NULL constraint failed: indexerapiaccess.indexer_id

I haven't seen this reported before.  Any suggestions?

Thanks,
 Peter

**Comment by theotherp** [comment]
No idea. Please enable debug log level, do a new search and post the zip that you get from the System / Bugreport tab (log and config)

**Comment by neverness74** [comment]
I get the same, and also a ```database is locked``` error that looks a bit like #38. I get both on any attempt at searching, with a 500 error as the ultimate result. Searching isn't currently working for me at all.

Have included the relevant log section below.

```
2016-05-01 22:06:59,481 - ERROR - search_module - My Indexer: An error error occurred while searching: database is locked
Traceback (most recent call last):
  File "/config/hydra/nzbhydra/search_module.py", line 304, in execute_queries
    request, papiaccess, indexerStatus = self.get_url_with_papi_access(query, "search", False)
  File "/config/hydra/nzbhydra/search_module.py", line 273, in get_url_with_papi_access
    papiaccess.save()
  File "/config/hydra/nzbhydra/database.py", line 108, in save
    super(IndexerApiAccess, self).save(*args, **kwargs)
  File "/config/hydra/libs/peewee.py", line 4680, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/config/hydra/libs/peewee.py", line 3213, in execute
    cursor = self._execute()
  File "/config/hydra/libs/peewee.py", line 2628, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/config/hydra/libs/peewee.py", line 3461, in execute_sql
    self.commit()
  File "/config/hydra/libs/peewee.py", line 3285, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/config/hydra/libs/peewee.py", line 3454, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
2016-05-01 22:07:10,810 - ERROR - web - NOT NULL constraint failed: indexerapiaccess.indexer_id
Traceback (most recent call last):
  File "/config/hydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/config/hydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/config/hydra/nzbhydra/web.py", line 262, in wrapped_function
    return f(*args, **kwargs)
  File "/config/hydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/config/hydra/nzbhydra/web.py", line 498, in internalapi_search
    return startSearch(search_request)
  File "/config/hydra/nzbhydra/web.py", line 468, in startSearch
    results = search.search(True, search_request)
  File "/config/hydra/nzbhydra/search.py", line 233, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "/config/hydra/nzbhydra/search.py", line 304, in search_and_handle_db
    result.indexerApiAccessEntry.save()
  File "/config/hydra/nzbhydra/database.py", line 108, in save
    super(IndexerApiAccess, self).save(*args, **kwargs)
  File "/config/hydra/libs/peewee.py", line 4680, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/config/hydra/libs/peewee.py", line 3213, in execute
    cursor = self._execute()
  File "/config/hydra/libs/peewee.py", line 2628, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/config/hydra/libs/peewee.py", line 3461, in execute_sql
    self.commit()
  File "/config/hydra/libs/peewee.py", line 3285, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/config/hydra/libs/peewee.py", line 3454, in execute_sql
    cursor.execute(sql, params or ())
IntegrityError: NOT NULL constraint failed: indexerapiaccess.indexer_id
```

**Comment by neverness74** [comment]
Hmm, realised I hadn't set the log level to Debug for the above log. Did that and tried a search again and it worked this time. I had rebooted repeatedly before the previous report, but perhaps by making it re-save the config, it fixed something.

**Comment by Mirabis** [comment]
I'm starting to experience the same issues ; ( What do u need from me ?

- debug logs
- hydra access
- *?

```
2016-05-10 19:48:53,125 - ERROR - web - database is locked
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 382, in api
    return api_search(args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 441, in api_search
    result = search.search(False, search_request)
  File "/opt/nzbhydra/nzbhydra/search.py", line 273, in search
    searchResult = SearchResult().get_or_create(indexer=indexer.indexer, title=result.title, link=result.link, details=result.details_link, guid=result.indexerguid)
  File "/opt/nzbhydra/libs/peewee.py", line 4519, in get_or_create
    return cls.create(**params), True
  File "/opt/nzbhydra/libs/peewee.py", line 4494, in create
    inst.save(force_insert=True)
  File "/opt/nzbhydra/nzbhydra/database.py", line 108, in save
    super(SearchResult, self).save(*args, **kwargs)
  File "/opt/nzbhydra/libs/peewee.py", line 4680, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/opt/nzbhydra/libs/peewee.py", line 3213, in execute
    cursor = self._execute()
  File "/opt/nzbhydra/libs/peewee.py", line 2628, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/opt/nzbhydra/libs/peewee.py", line 3461, in execute_sql
    self.commit()
  File "/opt/nzbhydra/libs/peewee.py", line 3285, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/opt/nzbhydra/libs/peewee.py", line 3454, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
```

**Comment by theotherp** [comment]
Noooo, please no "database is locked" errors *cry*.

**Comment by Mirabis** [comment]
Seems like a annoying thing to fix, but if we were to put:

@line 120: database.db.connect() into database.db.connect(timeout=25) (or timeout setting + extra time)

**Comment by theotherp** [comment]
I can certainly try. To be honest I know very, very little about what happens in the background and why this error occurs. As I was never able to reproduce it I can't really debug it.

**Comment by Mirabis** [comment]
Probably one of the following:
- Database is accessed from multiple points, while already in use;
- A db connection somewhere is not properly closed, thus nothing after that can access it;

I changed it to : database.db.connect(timeout=config.settings.searching.timeout+5) for timebeing/testing

@Reproducing: I think people that have multiple users accessing the same nzb hydra instance have this, and maybe why others (including you) don't' see it. [Assumption]

**Comment by Mirabis** [comment]
```NOT NULL constraint failed: indexerapiaccess.indexer_id```

Sounds like a db migration error, if the models changed since previous ones. Something tries to set indexerapiaccess.indexer_id to null (or probably not set, makes it null by default) while there's a NOT NULL Constraint on it

**Comment by theotherp** [comment]
Before I added the threaded server it was not possible to have parallel access to Hydra at all and the error still occurred. It's somehow happening during the searching, that's where I start a thread for every indexer. But even in tests with 20 indexers I never had this problem.

**Comment by theotherp** [comment]
Where do you specify that timeout?

**Comment by theotherp** [comment]
I always wanted to refactor the whole database / searching code because that's what I wrote first and it just grew out of control. But that's a big task and it's so much more fun to add features...

**Comment by Mirabis** [comment]
* web.py line 120
* database.py is skipped... don't think it's needed there
* indexers.py line 33 ( hardcoded timeout might be fine here)

But mostly  the web.py one - not sure if it helps though.... more of a trial and error

**Comment by theotherp** [comment]
I get
`TypeError: connect() got an unexpected keyword argument 'timeout'`

**Comment by Mirabis** [comment]
https://docs.python.org/2/library/sqlite3.html
```
sqlite3.connect(database[, timeout, detect_types, isolation_level, check_same_thread, factory, cached_statements])
Opens a connection to the SQLite database file database. You can use ":memory:" to open a database connection to a database that resides in RAM instead of on disk.

When a database is accessed by multiple connections, and one of the processes modifies the database, the SQLite database is locked until that transaction is committed. The timeout parameter specifies how long the connection should wait for the lock to go away until raising an exception. The default for the timeout parameter is 5.0 (five seconds).

For the isolation_level parameter, please see the Connection.isolation_level property of Connection objects.

SQLite natively supports only the types TEXT, INTEGER, REAL, BLOB and NULL. If you want to use other types you must add support for them yourself. The detect_types parameter and the using custom converters registered with the module-level register_converter() function allow you to easily do that.

detect_types defaults to 0 (i. e. off, no type detection), you can set it to any combination of PARSE_DECLTYPES and PARSE_COLNAMES to turn type detection on.

By default, the sqlite3 module uses its Connection class for the connect call. You can, however, subclass the Connection class and make connect() use your class instead by providing your class for the factory parameter.

Consult the section SQLite and Python types of this manual for details.

The sqlite3 module internally uses a statement cache to avoid SQL parsing overhead. If you want to explicitly set the number of statements that are cached for the connection, you can set the cached_statements parameter. The currently implemented default is to cache 100 statements.
```
Is what I used for reference,

But looks like ```After the database filename, you can specify arbitrary sqlite3 parameters.``` http://docs.peewee-orm.com/en/latest/peewee/database.html#using-sqlite -> We must type

```database.db.connect('nzbhydra.db',timeout=config.settings.searching.timeout)```

**Comment by theotherp** [comment]
Got it:

```
db = SqliteExtDatabase(None, pragmas=(
    ('timeout', config.settings.searching.timeout+5),
    ('threadlocals', True),
    ('journal_mode', 'WAL'),
))
```

**Comment by theotherp** [comment]
Unfortunately I have no way of testing that...

**Comment by Mirabis** [comment]
If u specify it at db creation, wouldn't u limit every action of Hydra to that 20 ~  25 seconds ?

**Comment by theotherp** [comment]
I'm out of my depth here, but I think not. It just says that it waits that long if a table is locked. For testing I set a timeout of 5 and let my search sleep for 30 seconds and it still worked fine.

**Comment by Mirabis** [comment]
I've set it to a timeout of 25 for myself.. and will see if it changes anything :)

**Comment by theotherp** [comment]
So did I on my server but I never had that database is locked error there, so it won't prove anything.

Anyway, thanks for the support.

**Comment by Mirabis** [comment]
Running latest , log doesn't show error anymore but the url still gives 'database locked'  xD

**Comment by theotherp** [comment]
Fuck. Going to bed now. More on thursday.

**Comment by theotherp** [comment]
Please post what you use, what indexers you use. Perhaps I find a way to reproduce this.

**Comment by Mirabis** [comment]
Do u have discord / or skype where i can post without cleaning my logs everytime :p?

**Comment by theotherp** [comment]
Will get back to you on thursday, thanks.

**Comment by Mirabis** [comment]
Param | Result    | extra
------------ | ------------- | -------------
extended=1 | database is locked | limit=100/offset=0
extended=0 | database is locked | limit=100/offset=0
cat=5030,5040,5045,5185,5050,5020,5010,5060,5070 | database is locked  | limit=100/offset=0/extended=1
cat=5030,5040,5045,5185,5050,5020,5010,5060 | datetime.datetime(2016, 5, 10, 20, 25, 39, 612270) is not JSON serializable| limit=100/offset=0/extended=1
cat=5030,5040,5045,5185,5050,5020,5010 | database is locked | limit=100/offset=0/extended=1
cat=5030,5040,5045,5185,5050,5020  | database is locked | limit=100/offset=0/extended=1
cat=5030,5040,5045,5185,5050 | database is locked | limit=100/offset=0/extended=1
cat=5030,5040,5045,5185 | database is locked | limit=100/offset=0/extended=1
cat=5030,5040,5045 | 'NzbSearchResult' object has no attribute 'searchResultId' | limit=100/offset=0/extended=1
cat=5030,5040 | 'NzbSearchResult' object has no attribute 'searchResultId' | limit=100/offset=0/extended=1
cat=5030 | database is locked | limit=100/offset=0/extended=1

**Comment by theotherp** [comment]
All these work just fine for me.

**Comment by theotherp** [comment]
What indexers?

**Comment by Mirabis** [comment]
https://gyazo.com/49927285d62df1eaac8b709228acadb3

pretty much all of them VIP

**Comment by theotherp** [comment]
But the indexers can't be the problem. I still have no idea why I never have that problem and you can reliably reproduce it.

**Comment by Mirabis** [comment]
Maybe it's related to the hardware/software/os ...

But I'm going to tinker with the db code a bit to see if i can solve it locally

**Comment by theotherp** [comment]
Are you running hydra on a pi or something like that? Perhaps my machine is too fast...

**Comment by Mirabis** [comment]
Nopew

a 40 Core Hypervisor / dual E5-2650v3 & 128GB ram

VM for NzbHydra
```
Dynamic memory 2 - 16 GB assigned
4 vCPu assigned
SSD  tiered disk
```

VM usage is like 0.x %

**Comment by theotherp** [comment]
Lol, that should do it.

**Comment by neverness74** [comment]
Just for info, when I had this issue it was in a Docker container. It wasn't particularly resource constrained, and the error happened consistently across a period of time including multiple reboots (and my Docker container, which comes from linuxserver.io, basically reinstalls from scratch at each reboot, preserving config files only).

It went away for me when I'm pretty sure all I did was change the logging level to Debug. I haven't seen it since (though I had both the "database is locked" and the indexer null constraint errors before then).

I had also just upgraded from 0.0.1a90 to 0.0.1a91 too, if it helps.

Unfortunately I didn't keep a copy of my config from beforehand, else a diff might have been interesting.

Anyway thanks for sticking with this issue, looks like a slippery one!!

**Comment by Mirabis** [comment]
Well, made soem changes to DB no real effect...

**BUT disabling all indexers** and enabling them one by one seems promising.

Error goes away if I only use nzbgeek

**Comment by theotherp** [comment]
With only one indexer there would only one thread be running, so then the database should never be locked. 

Thanks for the input, @neverness74. Great to here that at least it's solved for you. When I get a new bug report I always tend to think that everybody is affected and I screwed everything up. Good to have some perspective.

**Comment by Mirabis** [comment]
Indexer  | Error Occurred    
------------ | ------------- 
nzbgeek | no
dognzbcr | no
nzb.su | no
pfmonkey | no
omgwtfnzbs | no
althub | no
miatrix | no
nzbcat | no
nzbplanet |  no
nzbs.org | no
lulunzb | no
newztown.co.za |
nzb.is |
6box | 

Started enabling them one by one from top to bottom - once error occurs / i recount in table. (same url)

**Comment by Mirabis** [comment]
How big are your nzbhydra.db files?

**Comment by theotherp** [comment]
55MB

**Comment by Mirabis** [comment]
256MB ... but wiping the indexeraccess tables had no benefit... will continue searching xD

**Comment by Mirabis** [comment]
After changing my systemd script, i no longer have the ' database locked' error :yay: 

Explicitly specifying the PIDFile and pid made things go smoother.... probably it tried to start multiple instances or w/e locking eachother out.

```
[Unit]
Description=NZBHydra Daemon
Documentation=https://github.com/theotherp/nzbhydra
After=network.target

[Service]
User=root
Group=root
Type=simple
ExecStart=/usr/bin/python /opt/nzbhydra/nzbhydra.py -D --pidfile='/var/run/nzbhydra/nzbhydra.pid' --nobrowser
PIDFile=/var/run/nzbhydra/nzbhydra.pid

KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by theotherp** [comment]
That's great. I'll do some tests in that regard.

**Comment by jcoin** [comment]
Hello, i'm running nzbhydra on a raspberry pi 2 and have this issue.

here is the log about it : 

```
2016-05-16 18:38:29,526 - ERROR - search_module - Pfmonkey: An error error occurred while searching: database is locked
Traceback (most recent call last):
  File "/home/osmc/nzbhydra/nzbhydra/search_module.py", line 310, in execute_queries
    request, papiaccess, indexerStatus = self.get_url_with_papi_access(query, "search", False)
  File "/home/osmc/nzbhydra/nzbhydra/search_module.py", line 279, in get_url_with_papi_access
    papiaccess.save()
  File "/home/osmc/nzbhydra/nzbhydra/database.py", line 134, in save
    super(IndexerApiAccess, self).save(*args, **kwargs)
  File "/home/osmc/nzbhydra/libs/peewee.py", line 4920, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/home/osmc/nzbhydra/libs/peewee.py", line 3373, in execute
    cursor = self._execute()
  File "/home/osmc/nzbhydra/libs/peewee.py", line 2774, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/osmc/nzbhydra/libs/peewee.py", line 3645, in execute_sql
    self.commit()
  File "/home/osmc/nzbhydra/libs/peewee.py", line 3466, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/osmc/nzbhydra/libs/peewee.py", line 3638, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
2016-05-16 18:38:29,538 - ERROR - search_module - Database is locked: Here's more info:
2016-05-16 18:38:29,544 - ERROR - search - Error while calling search module
Traceback (most recent call last):
  File "/home/osmc/nzbhydra/nzbhydra/search.py", line 357, in start_search_futures
    results = f.result()
  File "/home/osmc/nzbhydra/libs/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/home/osmc/nzbhydra/libs/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/osmc/nzbhydra/nzbhydra/search_module.py", line 126, in search
    queries_execution_result = self.execute_queries(urls, search_request)
  File "/home/osmc/nzbhydra/nzbhydra/search_module.py", line 353, in execute_queries
    self.logger.error(json.dumps(e))
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: OperationalError('database is locked',) is not JSON serializable
```

**Comment by theotherp** [comment]
My latest commit should solve at least this particular variant of the error.

**Comment by theotherp** [comment]
Please update to 0.2.118 and enable the threaded server. Let me know if it works.
