### ISSUE TITLE
Improve binsearch parsing or at least reduce error output

### ISSUE THREAD

**Issue by sanderjo** [theotherp/nzbhydra#207]
I get `WARNING - search_module - Binsearch: Unable to find main table in binsearch page. This just sometimes happens...` and then a Traceback.

Is this as it should be? Shouldn't the exception being caught/passed/ignored as there is already a WARNING?

```
2016-05-06 11:03:43,069 - INFO - binsearch - Last results count 0
2016-05-06 11:03:43,078 - WARNING - search_module - Binsearch: Unable to find main table in binsearch page. This just sometimes happens...
2016-05-06 11:03:43,079 - ERROR - search_module - Binsearch: Error while processing search results from indexer Binsearch
Traceback (most recent call last):
  File "/home/sander/git/nzbhydra/nzbhydra/search_module.py", line 320, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/home/sander/git/nzbhydra/nzbhydra/searchmodules/binsearch.py", line 132, in process_query_result
    raise IndexerResultParsingException("Unable to find main table in binsearch page. This happens sometimes... :-)", self)
IndexerResultParsingException
```

**Comment by theotherp** [comment]
You're right.

**Comment by albino1** [comment]
I've learned to ignore it because it used to be much worse.  It used to spit out like 100 lines of HTML (see #68).

A more hopeful solution would be to find a remedy to the binsearch problem in general.  Any chance of that happening @theotherp?  Or is it just not feasible?

**Comment by theotherp** [comment]
That would be ideal, I'm adding it to my list.

**Comment by theotherp** [comment]
Have you found a query that reproduces this problem? I tried 20 or so searches and never encountered this.

**Comment by sanderjo** [comment]
It happens when I type "fedora private" in NZBhydra.

**Comment by theotherp** [comment]
Thanks, not anymore :-)

**Comment by whispy** [comment]
This issue appears to still exist.

```
2017-01-11 17:15:07,774 - ERROR - search_module - Thread-2078 - Binsearch: Error while processing search results from indexer Binsearch
Traceback (most recent call last):
  File "/config/hydra/nzbhydra/search_module.py", line 395, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/config/hydra/nzbhydra/searchmodules/binsearch.py", line 152, in process_query_result
    entry = self.parseRow(row)
  File "/config/hydra/nzbhydra/searchmodules/binsearch.py", line 210, in parseRow
    entry.poster = urlparse.unquote(poster).replace("+", " ")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 1: ordinal not in range(128)
2017-01-11 17:15:09,067 - ERROR - search_module - Thread-2078 - Binsearch: Access error: Error while parsing the results from indexer
```

**Comment by theotherp** [comment]
That's caused by an encoding error. Won't fix that, can just happen sometimes.
