### ISSUE TITLE
NZBGeek returns no results

### ISSUE THREAD

**Issue by belisarivs** [theotherp/nzbhydra#215]
I tested this with a few different queries (for instance, "ubuntu"), and manually formed a query to ensure it wasn't something odd on NZBGeek's end.  There nothing in the log file that indicates an error apart from a message saying no results returned from NZBGeek ("INFO - search_module - NZBGeek: Query returned no results").  Other indexers seem to work just fine.  

I saw that you had to do some customization for NZBGeek per ticket #182, so there might be something off there.

**Comment by theotherp** [comment]
Please post the info from System -> Bugreport.

**Comment by belisarivs** [comment]
Hrm, interesting.  I attempted to generate the system info and I got this:

> 2016-05-08 08:53:39,773 - ERROR - web - Error creating debugging infos
Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra/web.py", line 920, in internalapi_getdebugginginfos
    debuggingInfos = getDebuggingInfos()
  File "/opt/nzbhydra/nzbhydra/backup_debug.py", line 83, in getDebuggingInfos
    al = log.getAnonymizedLogFile(config.getSettingsToHide()).encode("utf-8")
  File "/opt/nzbhydra/nzbhydra/config.py", line 574, in getSettingsToHide
    ("indexers.omgwwtfnzbs.apikey", settings.indexers.omgwtfnzbs.apikey),
AttributeError: 'list' object has no attribute 'omgwtfnzbs'

Looks like there's a spelling error in nzbconfig/config.py ("indexers.omgwwtfnzbs.apikey" - note the two "w").  I'll try to fix it and generate the report.

**Comment by theotherp** [comment]
Thanks

**Comment by belisarivs** [comment]
Well, I corrected the spelling, but I guess I'm just not familiar enough with Python.  I'm not sure where the list is suppose to set "omgwtfnzbs" as an associative key.  I tried to disable the indexer and triggered a restart, but that didn't help.

**Comment by theotherp** [comment]
Ok, just post the log containing a search with nzbgeek. It should be anonymized anyway.

**Comment by theotherp** [comment]
Bugreport should work with new version.

**Comment by belisarivs** [comment]
> 2016-05-08 09:31:50,394 - INFO - nzbhydra - Started
2016-05-08 09:31:50,394 - INFO - nzbhydra - Daemonizing...
2016-05-08 09:31:50,397 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-05-08 09:31:50,403 - INFO - indexers - Activated indexer omgwtfnzbs.org
2016-05-08 09:31:50,404 - INFO - indexers - Activated indexer NZBGeek
2016-05-08 09:31:50,404 - INFO - indexers - Activated indexer NZBCat
2016-05-08 09:31:50,405 - INFO - indexers - Activated indexer NZB Finder
2016-05-08 09:31:50,405 - INFO - indexers - Activated indexer NZBGeek2
2016-05-08 09:31:50,406 - NOTICE - nzbhydra - Starting web app on 0.0.0.0:5075
2016-05-08 09:31:50,407 - NOTICE - nzbhydra - Go to http://127.0.0.1:5075 for the frontend
2016-05-08 09:31:56,449 - INFO - update - git output: git version 2.7.4
2016-05-08 09:32:20,235 - INFO - search_module - NZBGeek: Query returned no results

I added in a second NZBGeek just to see if adding it from scratch as an newznab provider would work (it didn't).  I de-selected everything other than NZBGeek and searched for "ubuntu".

**Comment by theotherp** [comment]
Sorry, forgot to mention that you should set the log level for the log file to debug...

**Comment by belisarivs** [comment]
I was wondering if there was a way to increase verbosity.  For some reason, I didn't notice it the first time around in the config section.

> 2016-05-08 10:06:01,316 - INFO - nzbhydra - Started
2016-05-08 10:06:01,316 - INFO - nzbhydra - Daemonizing...
2016-05-08 10:06:01,319 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-05-08 10:06:01,323 - DEBUG - indexers - Found indexer Binsearch
2016-05-08 10:06:01,324 - DEBUG - indexers - Found indexer NZBClub
2016-05-08 10:06:01,324 - DEBUG - indexers - Found indexer NZBIndex
2016-05-08 10:06:01,325 - DEBUG - indexers - Found indexer Womble
2016-05-08 10:06:01,325 - DEBUG - indexers - Found indexer omgwtfnzbs.org
2016-05-08 10:06:01,326 - INFO - indexers - Activated indexer omgwtfnzbs.org
2016-05-08 10:06:01,326 - DEBUG - indexers - Found indexer NZBGeek
2016-05-08 10:06:01,326 - INFO - indexers - Activated indexer NZBGeek
2016-05-08 10:06:01,326 - DEBUG - indexers - Found indexer NZBCat
2016-05-08 10:06:01,327 - INFO - indexers - Activated indexer NZBCat
2016-05-08 10:06:01,327 - DEBUG - indexers - Found indexer NZB Finder
2016-05-08 10:06:01,328 - INFO - indexers - Activated indexer NZB Finder
2016-05-08 10:06:01,328 - DEBUG - indexers - Found indexer NZBGeek2
2016-05-08 10:06:01,328 - INFO - indexers - Activated indexer NZBGeek2
2016-05-08 10:06:01,329 - NOTICE - nzbhydra - Starting web app on 0.0.0.0:5075
2016-05-08 10:06:01,330 - NOTICE - nzbhydra - Go to http://127.0.0.1:5075 for the frontend
2016-05-08 10:06:05,513 - DEBUG - web - Sending index.html
2016-05-08 10:06:06,744 - DEBUG - web - Get isAdminLoggedIn request
2016-05-08 10:06:06,758 - DEBUG - web - Get config request
2016-05-08 10:06:06,762 - DEBUG - web - Get safe config request
2016-05-08 10:06:06,788 - DEBUG - web - Get versions request
2016-05-08 10:06:06,788 - DEBUG - update - /opt/nzbhydra/.git exists. Assuming this is a git clone
2016-05-08 10:06:06,789 - DEBUG - update - Git executable not configured, trying to call git globally
2016-05-08 10:06:06,789 - DEBUG - update - Checking if we can use git commands: git version
2016-05-08 10:06:06,789 - DEBUG - update - Executing "git" version with your shell in /opt/nzbhydra
2016-05-08 10:06:06,798 - INFO - update - git output: git version 2.7.4
2016-05-08 10:06:06,798 - DEBUG - update - "git" version : returned successful
2016-05-08 10:06:06,798 - DEBUG - update - Using: git
2016-05-08 10:06:06,799 - DEBUG - update - Loading repository version from https://raw.github.com/theotherp/nzbhydra/master/version.txt
2016-05-08 10:06:35,458 - DEBUG - web - Search request with args {u'category': u'All', u'indexers': u'NZBGeek', u'minage': None, u'maxage': None, u'minsize': None, u'maxsize': None, u'offset': 0, u'query': u'ubuntu'}
2016-05-08 10:06:35,459 - DEBUG - search - Didn't find this query in cache or want to do a new search
2016-05-08 10:06:35,459 - DEBUG - search - Did not pick omgwtfnzbs.org because it was not selected by the user
2016-05-08 10:06:35,462 - DEBUG - search - Picked NZBGeek
2016-05-08 10:06:35,462 - DEBUG - search - Did not pick NZBCat because it was not selected by the user
2016-05-08 10:06:35,463 - DEBUG - search - Did not pick NZB Finder because it was not selected by the user
2016-05-08 10:06:35,463 - DEBUG - search - Did not pick NZBGeek2 because it was not selected by the user
2016-05-08 10:06:35,463 - DEBUG - search - We want 100 results but have only 0 so far
2016-05-08 10:06:35,463 - DEBUG - search - 1 indexers still have results
2016-05-08 10:06:35,464 - DEBUG - search - Searching indexers with offset 0
2016-05-08 10:06:35,464 - DEBUG - search - Added 1 of 1 calls to executor
2016-05-08 10:06:35,466 - DEBUG - search_module - NZBGeek: Requesting https://api.nzbgeek.info/api?apikey=<APIKEY>&t=search&extended=1&offset=0&limit=100&q=ubuntu+-- with timeout 5
2016-05-08 10:06:38,227 - DEBUG - search_module - NZBGeek: Successfully loaded URL https://api.nzbgeek.info/api?apikey=<APIKEY>&t=search&extended=1&offset=0&limit=100&q=ubuntu+--
2016-05-08 10:06:38,227 - DEBUG - search_module - NZBGeek: Started processing results
2016-05-08 10:06:38,228 - INFO - search_module - NZBGeek: Query returned no results
2016-05-08 10:06:38,229 - DEBUG - search - Retrieved 1 of 1 calls from executor
2016-05-08 10:06:38,232 - DEBUG - search - Returning search results now
2016-05-08 10:06:38,232 - DEBUG - search - NZBGeek returned 0 results
2016-05-08 10:06:38,233 - DEBUG - search - NZBGeek reports 0 total results. We'll include in the total this time only
2016-05-08 10:06:38,233 - DEBUG - search - We have 0 cached results and return them all because we search internally
2016-05-08 10:06:38,233 - DEBUG - api - Processing 0 results
2016-05-08 10:06:53,777 - DEBUG - web - Get askforadmin request
2016-05-08 10:06:54,961 - DEBUG - web - Get logs request
2016-05-08 10:06:54,962 - DEBUG - log - Reading log file nzbhydra.log

**Comment by belisarivs** [comment]
So, the query works if the "+--" at the end is stripped, but returns 0 results with it there.

**Comment by theotherp** [comment]
What the hell, where does that come from. Do yo have any ignored words configured?

**Comment by belisarivs** [comment]
Nope, it's a pretty vanilla setup (apart from adding in my indexers).

**Comment by theotherp** [comment]
Ok, I'll check it out.

**Comment by theotherp** [comment]
Please let me know if that works, I don't have VIP there.

**Comment by belisarivs** [comment]
Yep, that did it.  Thanks.

**Comment by theotherp** [comment]
Cool.

**Comment by roosey** [comment]
I'm having the same issue whats the fix here?

**Comment by albino1** [comment]
Try upgrading to NZBHydra2:

https://github.com/theotherp/nzbhydra2/
