### ISSUE TITLE
Indexer delete button does not work

### ISSUE THREAD

**Issue by belisarivs** [theotherp/nzbhydra#216]
Sorry to follow up one bug with another.  I tried to delete the second NZBGeek indexer I added to try and debug #215, but nothing happened.  Looked through the log, and got this:

> 2016-05-08 10:34:13,050 - DEBUG - web - Log error request
2016-05-08 10:34:13,050 - ERROR - web - The client encountered the following error: $scope.deleteIndexer@http://nzb:5075/static/js/nzbhydra.js:3080:9
anonymous/fn@http://nzb:5075/static/js/alllibs.js line 23297 > Function:2:227
expensiveCheckFn@http://nzb:5075/static/js/alllibs.js:24287:18
ngEventHandler/</callback@http://nzb:5075/static/js/alllibs.js:33757:17
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://nzb:5075/static/js/alllibs.js:26031:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://nzb:5075/static/js/alllibs.js:26131:20
ngEventHandler/<@http://nzb:5075/static/js/alllibs.js:33762:17
jQuery.event.dispatch@http://nzb:5075/static/js/alllibs.js:4434:15
jQuery.event.add/elemData.handle@http://nzb:5075/static/js/alllibs.js:4121:6
. Caused by: No known cause

**Comment by belisarivs** [comment]
Here's a better stack-trace (don't know why that other one was so wonky):

> 2016-05-08 10:44:49,633 - ERROR - web - The client encountered the following error: TypeError: Cannot read property 'splice' of undefined
at Scope.$scope.deleteIndexer (http://nzb:5075/static/js/nzbhydra.js:3080:20)
at fn (eval at <anonymous> (http://nzb:5075/static/js/alllibs.js:23297:15), <anonymous>:4:230)
at expensiveCheckFn (http://nzb:5075/static/js/alllibs.js:24287:18)
at callback (http://nzb:5075/static/js/alllibs.js:33757:17)
at Scope.$eval (http://nzb:5075/static/js/alllibs.js:26031:28)
at Scope.$apply (http://nzb:5075/static/js/alllibs.js:26131:25)
at HTMLButtonElement.<anonymous> (http://nzb:5075/static/js/alllibs.js:33762:23)
at HTMLButtonElement.jQuery.event.dispatch (http://nzb:5075/static/js/alllibs.js:4435:9)
at HTMLButtonElement.elemData.handle (http://nzb:5075/static/js/alllibs.js:4121:28). Caused by: No known cause

**Comment by theotherp** [comment]
Aaargh leave me alone *runs away and cries*.

Seriously though, thanks for the report. I changed too much stuff yesterday and pushed it without properly testing.

**Comment by belisarivs** [comment]
Bah, that's what users are for.
