### ISSUE TITLE
 AttributeError: 'NzbSearchResult' object has no attribute 'searchResultId'

### ISSUE THREAD

**Issue by Mirabis** [theotherp/nzbhydra#229]
```
2016-05-10 20:32:28,193 - DEBUG - web - http://mydomain.nl/api?t=tvsearch&cat=5030,5040,5045,5185,5050,5020,5010,5060,5070&extended=1&apikey=<APIKEY>&offset=400&limit=100
2016-05-10 20:32:28,193 - DEBUG - web - API request: {u'minsize': None, u'raw': 0, u'attrs': None, u'query': None, u'rid': None, u'id': None, u'dbsearchid': None, u'category': None, u'group': None, u'author': None, u'imdbid': None, u'maxage': None, u'indexer': None, u'ep': None, u'maxsize': None, u'input': None, u'indexers': None, u'extended': True, u'offsets': None, u'season': None, u'minage': None, u'offset': 400, u'genre': None, 'apikey':<APIKEY>', u'episode': None, u'tvdbid': None, u'title': None, u'o': u'XML', u'cat': u'5030,5040,5045,5185,5050,5020,5010,5060,5070', u'q': None, u'del': None, u't': u'tvsearch', u'limit': 100}
2016-05-10 20:32:28,194 - INFO - web - API search request: SearchRequest [ type "tv", category "5030,5040,5045,5185,5050,5020,5010,5060,5070", offset "400", limit "100" ]
2016-05-10 20:32:28,194 - INFO - search - Will ignore results older than 2900 days
2016-05-10 20:32:28,260 - DEBUG - search - Found search in cache
2016-05-10 20:32:28,261 - DEBUG - search - Will search at indexers as long as we don't have enough results for the current offset+limit and any indexer has more results.
2016-05-10 20:32:28,261 - DEBUG - search - We have 1275 cached results and return 400-500 of 2293737 total available accounting for the limit set for the API search
2016-05-10 20:32:28,332 - ERROR - web - 'NzbSearchResult' object has no attribute 'searchResultId'
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 382, in api
    return api_search(args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 442, in api_search
    results = process_for_external_api(result)
  File "/opt/nzbhydra/nzbhydra/api.py", line 152, in process_for_external_api
    results = transform_results(results["results"], True)
  File "/opt/nzbhydra/nzbhydra/api.py", line 122, in transform_results
    i.link = get_nzb_link_and_guid(i.searchResultId, external)
```

For some reason the NzbSearchResult is invalid or null.. which errors out when we want the searchResultId attribute.

We can probably do a check first but.. might be handier to fix it at the proper spot ( where the attribute had to be set)

**Comment by theotherp** [comment]
Yeah, I just realized that happens when SearchResult was not created because of missing data. But it's still contained in the list and later handled and then the id is empty.

I'll add a quick fix. Considering all the bug reports coming in I will need to some serious reworking on the search results processing code.

**Comment by theotherp** [comment]
It's just strange that hydra keeps running fine on my desktop and my server, without any of the issues reported here.

**Comment by Mirabis** [comment]
Ha.... was about to fork for some changes when I received the spree of ' commit' mails ;p

**Comment by theotherp** [comment]
When I did all the new features I didn't expect so many bug reports coming in... I hope I don't make matters worse, but I was so productive yesterday and wanted to share my results :-D
