### ISSUE TITLE
Remote Access Error: [Errno 10053] 

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#24]
I was playing around with accessing NZBHydra remotely from my laptop, and it worked pretty flawlessly.  However, after looking at the console on the Windows 7 PC running my NZBHydra installation I noticed these errors listed twice:
```python
----------------------------------------
Exception happened during processing of request from ('123.45.67.89', 60991)
Traceback (most recent call last):
  File "C:\NZBHydra\libs\SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\NZBHydra\libs\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\NZBHydra\libs\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\NZBHydra\libs\SocketServer.py", line 657, in __init__
    self.finish()
  File "C:\NZBHydra\libs\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "C:\NZBHydra\libs\socket.py", line 283, in close
    self.flush()
  File "C:\NZBHydra\libs\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in yo
ur host machine
----------------------------------------
```

I tried to replicate them, but I couldn't figure out how to make it happen intentionally.

**Comment by theotherp** [comment]
I have no idea what that means and haven't seen that before. Will do some research.

**Comment by theotherp** [comment]
Ok, considering http://stackoverflow.com/questions/17787023/python-how-to-catch-a-flask-except-like-this and http://stackoverflow.com/questions/17854713/error-errno-10053 I'm going to ignore this for now.
