### ISSUE TITLE
WindowsError: [Error 32]

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#255]
I've been getting these a lot for several versions of NZBHydra now:

```python
Traceback (most recent call last):
  File "C:\Program Files\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Program Files\Python27\lib\logging\handlers.py", line 142, in doRollo
ver
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process
Logged from file search.py, line 272
```

And sometimes this version with a slightly different line number in `search.py`:

```python
Traceback (most recent call last):
  File "C:\Program Files\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Program Files\Python27\lib\logging\handlers.py", line 142, in doRollo
ver
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process
Logged from file search.py, line 263
```

The error is only visible when running NZBH from the command prompt as the errors are outputted to the console, but not anywhere in my log, even though my logging is set to Debug.

I was trying to figure out if the "other process" was something on my end, so I've been waiting to report the error as I tried eliminate possibilities locally (antivirus, online backup, etc).  So far it's continued to show up. 

I'm not running any other programs that call python to run, but I noticed that `python.exe` appeared twice in my Task Manager.  Turns out it's because of the automatic restart after upgrading:

![nzbh-pythonrestarted](https://cloud.githubusercontent.com/assets/12164957/15313095/df111048-1bbd-11e6-9633-315813f1573d.jpg)

So maybe after upgrading you end up with two instances of NZBH/python both trying to access the file at the same time?

Anyway, I can't seem to reliably replicate it, but the error appears a lot though.  It repeats enough times in my console that I can't ever scroll up far enough to get to the point before it started spitting out.  There's no timestamp associated with it, so it's kind of hard to track down when it's occurring so I can figure out why.  It definitely doesn't happen on every search, so I'm not sure what the trigger is.

I would think most users would never see this error, so maybe it's not a big deal.  Or maybe it's just something broken on my end, who knows :)

**Comment by theotherp** [comment]
To be honest I had that sometimes as well and so far ignored it. Adding it to my list...
