### ISSUE TITLE
Address already in use Error

### ISSUE THREAD

**Issue by kylerw** [theotherp/nzbhydra#256]
I can access the web interface fine but I'm receiving:

2016-05-18 10:29:02,649 - ERROR - nzbhydra - Fatal error occurred
Traceback (most recent call last):
  File "/config/hydra/nzbhydra.py", line 141, in run
    web.run(host, port, basepath)
  File "/config/hydra/nzbhydra/web.py", line 1116, in run
    app.run(host=host, port=port, debug=config.settings.main.debug, threaded=config.settings.main.runThreaded, use_reloader=config.settings.main.flaskReloader)
  File "/config/hydra/libs/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/config/hydra/libs/werkzeug/serving.py", line 625, in run_simple
    inner()
  File "/config/hydra/libs/werkzeug/serving.py", line 603, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/config/hydra/libs/werkzeug/serving.py", line 506, in make_server
    passthrough_errors, ssl_context)
  File "/config/hydra/libs/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/config/hydra/libs/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/config/hydra/libs/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/config/hydra/libs/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/config/hydra/libs/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

**Comment by kylerw** [comment]
Had been seeing it the last couple days but I seemed to have resolved it with a shutdown and restart.
