### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by icetail** [theotherp/nzbhydra#262]
I keep getting this error.
(and i think this is why my sickbear also times out.
Request failed: HTTPConnectionPool(host='***.******.**', port=80): Read timed out. (read timeout=30))

Version: 0.2.97

2016-05-23 09:08:07,698 - ERROR - web - database is locked
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 474, in api
    return api_search(args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 536, in api_search
    result = search.search(False, search_request)
  File "/opt/nzbhydra/nzbhydra/search.py", line 248, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "/opt/nzbhydra/nzbhydra/search.py", line 320, in search_and_handle_db
    dbsearch.save()
  File "/opt/nzbhydra/nzbhydra/database.py", line 77, in save
    super(Search, self).save(*args, **kwargs)
  File "/opt/nzbhydra/libs/peewee.py", line 4920, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/opt/nzbhydra/libs/peewee.py", line 3373, in execute
    cursor = self._execute()
  File "/opt/nzbhydra/libs/peewee.py", line 2774, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/opt/nzbhydra/libs/peewee.py", line 3645, in execute_sql
    self.commit()
  File "/opt/nzbhydra/libs/peewee.py", line 3466, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/opt/nzbhydra/libs/peewee.py", line 3638, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked

**Comment by theotherp** [comment]
It's a known problem, there are several issues for this.

Do you use a start script? Do you run it daemonized? In docker? Try to shut down your instance and run it using screen or tmux.

**Comment by icetail** [comment]
sorry, could not find any issues for this.

I've installed through this guide http://www.htpcguides.com/install-nzbhydra-ubuntu-universal-usenet-searching/ 
and use the Systemd startup Script.
I'm going to try tmux

**Comment by theotherp** [comment]
One is closed and the other named misleadingly, it's alright.

See #202 and #38

**Comment by icetail** [comment]
Even after a clean restart and no update (fresh install) it still locked my database (with upstart script and also in docker)

**Comment by theotherp** [comment]
What about tmux?

**Comment by theotherp** [comment]
Anyway, sorry you're having a bad time. I have some ideas on how to tackle this but don't have currently time. Hopefully in two weeks or so.

**Comment by Spritzup** [comment]
I had the same behavior after I started hammering NZBHydra in a short period of time.  Restarting the container that it runs in seems to have fixed the issue for now.

Probably unrelated, but I did have an expired indexer in my configuration.

~Spritz

**Comment by theotherp** [comment]
@Spritzup Please post the stack trace of the error.

**Comment by icetail** [comment]
Running with tmux now, I'll let you know how it goes.

**Comment by icetail** [comment]
also in tmux: 2016-05-25 09:59:03,022 - ERROR - web - database is locked

**Comment by theotherp** [comment]
Huh.

Try disabling the threaded server in the main config and restart. As I explained in the other thread I haven't been able to reproduce this so far, so debugging is hard.

**Comment by Spritzup** [comment]
As requested -->

`2016-05-23 22:06:52,365 - ERROR - web - database is locked
Traceback (most recent call last):
  File "/config/hydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/config/hydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/config/hydra/nzbhydra/web.py", line 316, in wrapped_function
    return f(*args, **kwargs)
  File "/config/hydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/config/hydra/nzbhydra/web.py", line 584, in getnzb
    return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"])
  File "/config/hydra/nzbhydra/web.py", line 756, in extract_nzb_infos_and_return_response
    link, _, _ = get_indexer_nzb_link(searchResultId, "redirect", True)
  File "/config/hydra/nzbhydra/api.py", line 229, in get_indexer_nzb_link
    papiaccess.save()
  File "/config/hydra/nzbhydra/database.py", line 134, in save
    super(IndexerApiAccess, self).save(*args, **kwargs)
  File "/config/hydra/libs/peewee.py", line 4920, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/config/hydra/libs/peewee.py", line 3373, in execute
    cursor = self._execute()
  File "/config/hydra/libs/peewee.py", line 2774, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/config/hydra/libs/peewee.py", line 3645, in execute_sql
    self.commit()
  File "/config/hydra/libs/peewee.py", line 3466, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/config/hydra/libs/peewee.py", line 3638, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked`

**Comment by theotherp** [comment]
That's really weird, that's a place in the code where no parallel access to the database exists, so the database cannot be locked by hydra itself.
 
In this particular place I can only surmise that several instances of hydra are running or something else is locking the database file.

**Comment by Spritzup** [comment]
@theotherp - I can't speak for the code, but I can speak for the setup it's running on.  Hydra is running in a docker container hosted by the latest version of unraid (Linux storage distro, for lack of a better description).  The DB should be isolated from anything else touching it by virtue of being containerized.

That being said, I only just started playing with Hydra and was wondering if an auto-update function exists, and what its default state is.

Could the (and just throwing this out there) database be having more requests than it can handle, which then causes the database to lock?

~Spritz

**Comment by theotherp** [comment]
No automated update, you have to trigger it manually. This will not be changed in the near future, probably never.

In your particular case there only a couple of select statements executed against the database. As I said before, I have never encountered this problem (apart from once where the code was just bad), neither on windows nor on my linux server, in eight months of development. I was never able to reproduce it, even with multiple parallel searches or downloads. Some users encounter it sparingly, others every time they search. I have no idea what to do here.

**Comment by Spritzup** [comment]
lol, I can appreciate the difficulty in trying to fix something you can't even replicate.  That being said, if I can help in anyway, please let me know.

I will say since I cycled the container, I've had no issues (~12 hours).

~Spritz

**Comment by icetail** [comment]
so... turned off threaded server and running in tmux... no locks anymore

**Comment by theotherp** [comment]
Good to know.

**Comment by connors511** [comment]
I'm getting the database is locked error as well, running 0.2.97 on docker.
Enabled indexers: AltHub, Binsearch, FreeNZB, NZBClub, NZBFinder, NZBIndex and Usenet-Crawler.

For me, it seems the error only occurs when nzbhydra is being hit with more than a single request at a time (Sonarr searching for two series or Couchpotato searching for a movie when Sonarr is doing an episode). From my latest log, it looks like the error is always preceeded by the same warning:
```
2016-05-28 10:03:48,065 - WARNING - search_module - NZBFinder: Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-05-28 10:03:48,066 - DEBUG - search - Retrieved 2 of 5 calls from executor
2016-05-28 10:03:48,316 - DEBUG - search_module - NZBIndex: Successfully loaded URL https://nzbindex.com/search?<SNIP>
2016-05-28 10:03:48,316 - DEBUG - search_module - NZBIndex: Started processing results
2016-05-28 10:03:48,316 - DEBUG - nzbindex - Using HTML parser html.parser
2016-05-28 10:03:48,358 - DEBUG - search - Retrieved 3 of 5 calls from executor
2016-05-28 10:03:48,427 - DEBUG - search_module - AltHub: Successfully loaded URL https://api.althub.co.za/api?<SNIP>
2016-05-28 10:03:48,427 - DEBUG - search_module - AltHub: Started processing results
2016-05-28 10:03:48,433 - DEBUG - search - Retrieved 5 of 5 calls from executor
2016-05-28 10:03:48,434 - DEBUG - search_module - AltHub: Successfully loaded URL https://api.althub.co.za/api?<SNIP>
2016-05-28 10:03:48,434 - DEBUG - search_module - AltHub: Started processing results
2016-05-28 10:03:48,439 - DEBUG - search - Retrieved 5 of 5 calls from executor
2016-05-28 10:03:48,456 - DEBUG - search_module - AltHub: Successfully loaded URL https://api.althub.co.za/api?<SNIP>
2016-05-28 10:03:48,456 - DEBUG - search_module - AltHub: Started processing results
2016-05-28 10:03:48,459 - DEBUG - search - Retrieved 4 of 5 calls from executor
2016-05-28 10:03:48,460 - ERROR - web - database is locked
Traceback (most recent call last):
  File "/config/hydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/config/hydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/config/hydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/config/hydra/nzbhydra/web.py", line 474, in api
    return api_search(args)
  File "/config/hydra/nzbhydra/web.py", line 536, in api_search
    result = search.search(False, search_request)
  File "/config/hydra/nzbhydra/search.py", line 248, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "/config/hydra/nzbhydra/search.py", line 320, in search_and_handle_db
    dbsearch.save()
  File "/config/hydra/nzbhydra/database.py", line 77, in save
    super(Search, self).save(*args, **kwargs)
  File "/config/hydra/libs/peewee.py", line 4920, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/config/hydra/libs/peewee.py", line 3373, in execute
    cursor = self._execute()
  File "/config/hydra/libs/peewee.py", line 2774, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/config/hydra/libs/peewee.py", line 3645, in execute_sql
    self.commit()
  File "/config/hydra/libs/peewee.py", line 3466, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/config/hydra/libs/peewee.py", line 3638, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
```

**Comment by theotherp** [comment]
Try to disable the threaded server.

**Comment by connors511** [comment]
Just wanted to pop by and say it seems to be working now.
I don't think I've seen a single "database locked" error since I switched off threaded server :)

**Comment by theotherp** [comment]
Awesome, thanks for the feedback. I'll do some testing. It's a bit weird that previously with threaded server enabled all manual searches would've been at the same time as the automated searches by Sonarr/CP/whatever, but who knows. I also tested multiple consecutive searches and never that had problem.

@Everybody: You might also try disabling the threaded server.

**Comment by theotherp** [comment]
Alright, I have a unit test that reliably produces this error. Not that I have any idea how to solve it, but it's a first step.

**Comment by theotherp** [comment]
Looks like I found a solution for this. Check 0.2.118 and enable the threaded server. Let me know if it works.

**Comment by judhat2** [comment]
Unfortunately, I got this error again.  If I search sonarr and nzb hydra at the same time, I get the error.  Whichever one started first is completed, but the second gets the error. I am on 6591c94. 
[nzbhydra-debuginfo-2016-07-04-01-06.zip](https://github.com/theotherp/nzbhydra/files/345161/nzbhydra-debuginfo-2016-07-04-01-06.zip)

```
2016-07-04 01:01:51,401 - ERROR - web - database is locked
Traceback (most recent call last):
  File "/root/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/nzbhydra/nzbhydra/web.py", line 355, in wrapped_function
    return f(*args, **kwargs)
  File "/root/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/root/nzbhydra/nzbhydra/web.py", line 674, in internalapi_search
    return startSearch(search_request)
  File "/root/nzbhydra/nzbhydra/web.py", line 640, in startSearch
    results = search.search(search_request)
  File "/root/nzbhydra/nzbhydra/search.py", line 258, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "/root/nzbhydra/nzbhydra/search.py", line 332, in search_and_handle_db
    dbsearch.save()
  File "/root/nzbhydra/nzbhydra/database.py", line 77, in save
    super(Search, self).save(*args, **kwargs)
  File "/root/nzbhydra/libs/peewee.py", line 4920, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/root/nzbhydra/libs/peewee.py", line 3373, in execute
    cursor = self._execute()
  File "/root/nzbhydra/libs/peewee.py", line 2774, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/root/nzbhydra/libs/peewee.py", line 3645, in execute_sql
    self.commit()
  File "/root/nzbhydra/libs/peewee.py", line 3466, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/root/nzbhydra/libs/peewee.py", line 3638, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
```

Glad to see Germany finally beat Italy.  I was rooting for them. Maybe they can win the whole thing.

**Comment by theotherp** [comment]
Ok, I give up. No idea what to do.

**Comment by judhat2** [comment]
Well, if I remember right, before you made the changes, both searches would be canceled. At least now, one of them will show results. If that's any consolation...
