### ISSUE TITLE
Internal server error when downloading multiple NZBs

### ISSUE THREAD

**Issue by martynhaigh** [theotherp/nzbhydra#274]
After a search returns multiple results, checking the checkboxes next to one or more of them results in this error:

> 
> An error occured :
> 500: INTERNAL SERVER ERROR
> 
> Instance matching query does not exist:
> SQL: SELECT "t1"."id", "t1"."indexer_id", "t1"."firstFound", "t1"."title", "t1"."guid", "t1"."link", "t1"."details" FROM "searchresult" AS t1 WHERE ("t1"."id" IS ?)
> PARAMS: [None]

the log file looks like this:
```

2016-06-04 14:03:32,939 - ERROR - web - Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."indexer_id", "t1"."firstFound", "t1"."title", "t1"."guid", "t1"."link", "t1"."details" FROM "searchresult" AS t1 WHERE ("t1"."id" IS ?)
PARAMS: [None]
Traceback (most recent call last):
  File "/config/hydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/config/hydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/config/hydra/nzbhydra/web.py", line 262, in wrapped_function
    return f(*args, **kwargs)
  File "/config/hydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/config/hydra/nzbhydra/web.py", line 694, in internalapi_addnzb
    searchResult = SearchResult.get(SearchResult.id == searchResultId)
  File "/config/hydra/libs/peewee.py", line 4505, in get
    return sq.get()
  File "/config/hydra/libs/peewee.py", line 2889, in get
    % self.sql())
SearchResultDoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."indexer_id", "t1"."firstFound", "t1"."title", "t1"."guid", "t1"."link", "t1"."details" FROM "searchresult" AS t1 WHERE ("t1"."id" IS ?)
PARAMS: [None]
```

**Comment by theotherp** [comment]
I don't understand, just checking the boxes? That shouldn't cause any errors. What version do you use? The current version should catch that error and log it properly.

**Comment by theotherp** [comment]
I cannot reproduce this.

**Comment by theotherp** [comment]
Please reopen when you have more infos.
