### ISSUE TITLE
Error when searching by API

### ISSUE THREAD

**Issue by tjiddy** [theotherp/nzbhydra#275]
I see this error in the logs when mylar calls the API to search 

```
2016-06-06 00:45:32,692 - INFO - search - Removed 3 duplicates from 32 results
2016-06-06 00:45:32,950 - ERROR - web - invalid literal for long() with base 10: ''
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 508, in api
    searchResultId = int(args["id"][len("nzbhydrasearchresult"):])
  File "/opt/nzbhydra/libs/future/types/newint.py", line 76, in __new__
    return super(newint, cls).__new__(cls, val)
ValueError: invalid literal for long() with base 10: ''
```

**Comment by theotherp** [comment]
Please enable debug log level and try again. Post the log. Post the log from mylar.

**Comment by mattswest** [comment]
I believe @evilhero fixed this on mylar's end about 15 hours ago.

https://github.com/evilhero/mylar/commit/5431908c835bb20b3d330e52d20abb87aa62bdff

**Comment by theotherp** [comment]
Well that's great, thanks for the info.
