### ISSUE TITLE
Error even with python-lxml is installed

### ISSUE THREAD

**Issue by jangrewe** [theotherp/nzbhydra#290]
I'm running Debian jessie with LXML installed via packages, but i still get this:

```
2016-06-12 11:54:32,121 - ERROR - search_module - Binsearch: Error while processing search results from indexer Binsearch
Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra/search_module.py", line 341, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/opt/nzbhydra/nzbhydra/searchmodules/binsearch.py", line 129, in process_query_result
    soup = BeautifulSoup(html, config.settings.searching.htmlParser)
  File "/opt/nzbhydra/libs/bs4/__init__.py", line 156, in __init__
    % ",".join(features))
FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
2016-06-12 11:54:32,906 - ERROR - search_module - NZBIndex: Error while processing search results from indexer NZBIndex
Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra/search_module.py", line 341, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/opt/nzbhydra/nzbhydra/searchmodules/nzbindex.py", line 122, in process_query_result
    soup = BeautifulSoup(html, config.settings.searching.htmlParser)
  File "/opt/nzbhydra/libs/bs4/__init__.py", line 156, in __init__
    % ",".join(features))
FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by theotherp** [comment]
lxml can be a pain in the arse to install. Not sure I understand what you mean by "installed via packages". Did you install it using pip or your package manager? Try the other way. 

You can easily test it running this python script:
```
import lxml
from bs4 import BeautifulSoup
soup = BeautifulSoup("", "lxml")

```

**Comment by jangrewe** [comment]
I'm sorry, i meant Debian packages, not Python packages.

My default python is `Python 2.7.9`, but i noticed that python-lxml is `3.4.0-1`
I've put that test code into a script and ran it, it doesn't complain about anything.
Running the test script explicitly with python3 results in an error about missing `bs4`,
and trying to `pip install lxml` tells me that the `Requirement [is] already satisfied`

**Comment by jangrewe** [comment]
I just checked, the LXML package is used for Python 2.7: ´/usr/lib/python2.7/dist-packages/lxml-3.4.0.egg-info´

**Comment by theotherp** [comment]
I remember that I had a really hard time to get this to run. I'm currently testing it and have some conflicting test results. It works in python console but not in Hydra. I'll check it later, until then just use the default parser, the performance loss is not that bad.

**Comment by jangrewe** [comment]
Great, thank you - also in general for creating NZB Hydra ;-)

**Comment by jangrewe** [comment]
Hi, i just tested this again with the most recent commit, but i still get this:

```
2016-07-01 20:56:07,682 - ERROR - search_module - Binsearch: Error while processing search results from indexer Binsearch
Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra/search_module.py", line 359, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/opt/nzbhydra/nzbhydra/searchmodules/binsearch.py", line 129, in process_query_result
    soup = BeautifulSoup(html, config.settings.searching.htmlParser)
  File "/opt/nzbhydra/libs/bs4/__init__.py", line 156, in __init__
    % ",".join(features))
FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

if it's of any help:
```
$ dpkg -l | grep lxml
ii  python-lxml                                       3.4.0-1                              amd64        pythonic binding for the libxml2 and libxslt libraries
```

**Comment by theotherp** [comment]
No idea, sorry. Just use BS, compared with the rest of the stuff the minor performance doesn't matter all that much.
