### ISSUE TITLE
API Not Refreshing

### ISSUE THREAD

**Issue by beezlebug923** [theotherp/nzbhydra#299]
I just reformatted my PC and started from scratch with Hydra, Sonarr and NZBGet. Whenever I try to setup the indexer with Sonarr exactly as I had before it fails each time. Its throwing the error:

2016-06-18 11:35:42,434 - ERROR - web - The client encountered the following error: Error: Invalid argument.
at interpolateFnWatchAction (http://127.0.0.1:5075/static/js/alllibs.js:18712:17)
at interpolateFnWatcher (http://127.0.0.1:5075/static/js/alllibs.js:21357:17)
at watchGroupAction (http://127.0.0.1:5075/static/js/alllibs.js:25954:13)
at $digest (http://127.0.0.1:5075/static/js/alllibs.js:26284:23)
at $apply (http://127.0.0.1:5075/static/js/alllibs.js:26548:13)
at Anonymous function (http://127.0.0.1:5075/static/js/alllibs.js:34234:17)
at dispatch (http://127.0.0.1:5075/static/js/alllibs.js:4434:6)
at handle (http://127.0.0.1:5075/static/js/alllibs.js:4120:5). Caused by: No known cause

BUT what I find really odd is if I go to refresh the API key it won't generate a new key. It creates examples like

r.5h0imedvy12(e+19)
1.t4mb58ibrth(e+20)

Thoughts?

**Comment by theotherp** [comment]
When does it throw that error?

**Comment by theotherp** [comment]
What do you mean set up with sonarr? How can hydra throw a Javascript error when you configure sonarr? Please describe in more detail what your steps are.

**Comment by theotherp** [comment]
What does sonarr say in the logs? What exactly fails?

**Comment by beezlebug923** [comment]
Here's what I'm doing.

1. In Sonarr, add NZBHydra as a new Newznab Indexer
2. URL, API key, etc are correct. When I attempt to save the setting Sonarr gives the error: No results were returned from your indexer, please check your settings.
3. Sonarr log has: Invalid request Validation failed:   -- No results were returned from your indexer, please check your settings.
4. Each time I attempt to save the setting it adds that error message I reported earlier to the NZBHydra log.

If I go back to version 0.0.1a84 everything works fine. I'm able to set it up as a new Newznab indexer and it saves the settings without issue.

**Comment by theotherp** [comment]
Uhm, sorry, no idea. That output tells me nothing without context. Could you try a different browser? Are you using Internet Explorer by any chance?
