### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'type'

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#306]
I saw this error several times in my log from a few different searches.  It looks like it happened when hydra was trying to get more results from an indexer by changing the offset to 100. 
[nzbhydra-debuginfo-2016-06-30-04-04.zip](https://github.com/theotherp/nzbhydra/files/339987/nzbhydra-debuginfo-2016-06-30-04-04.zip)

```
2016-06-30 03:50:57,267 - ERROR - search - Error while calling search module
Traceback (most recent call last):
  File "/root/nzbhydra/nzbhydra/search.py", line 369, in start_search_futures
    results = f.result()
  File "/root/nzbhydra/libs/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/root/nzbhydra/libs/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/nzbhydra/nzbhydra/search_module.py", line 103, in search
    urls = self.get_showsearch_urls(search_request)
  File "/root/nzbhydra/nzbhydra/searchmodules/newznab.py", line 319, in get_showsearch_urls
    url = self.build_base_url("tvsearch", search_request.category, offset=search_request.offset)
  File "/root/nzbhydra/nzbhydra/searchmodules/newznab.py", line 286, in build_base_url
    url = _build_base_url(self.settings.host, self.settings.apikey, action, category, self.limit, offset)
  File "/root/nzbhydra/nzbhydra/searchmodules/newznab.py", line 261, in _build_base_url
    if category.type == "newznab":
AttributeError: 'unicode' object has no attribute 'type'
```

**Comment by judhat2** [comment]
Thanks!
