### ISSUE TITLE
datetime is not JSON serializable

### ISSUE THREAD

**Issue by rickytin** [theotherp/nzbhydra#320]
I have this error when I include Oznzb to do a search.

An error occured :
500: INTERNAL SERVER ERROR

datetime.datetime(2016, 7, 8, 11, 30, 14, 670000, tzinfo=tzutc()) is not JSON serializable

![nzbhydra](https://cloud.githubusercontent.com/assets/4860538/16686218/b155b600-44de-11e6-96e8-4be5408cdaec.PNG)

**Comment by theotherp** [comment]
Enable debug log level, do another search, post log.

**Comment by rickytin** [comment]
Thanks theotherp for the replay, I will do that tonight at home.

**Comment by theotherp** [comment]
Please be aware that I'm leaving for vacation tomorrow, so you might need to wait a bit for that fix. Sorry.

**Comment by rickytin** [comment]
Don't worry, have a great vacation.

**Comment by rickytin** [comment]
2016-07-09 06:33:22,407 - INFO - indexers - Activated indexer Binsearch
2016-07-09 06:33:22,408 - INFO - indexers - Activated indexer NZBClub
2016-07-09 06:33:22,423 - INFO - indexers - Activated indexer NZBIndex
2016-07-09 06:33:22,424 - INFO - indexers - Activated indexer NZBGeek
2016-07-09 06:33:22,430 - INFO - indexers - Activated indexer DogNZB
2016-07-09 06:33:22,430 - INFO - indexers - Activated indexer Althub
2016-07-09 06:33:22,431 - INFO - indexers - Activated indexer Usenet-crawler
2016-07-09 06:33:22,433 - INFO - indexers - Activated indexer Nzbs
2016-07-09 06:33:22,434 - INFO - indexers - Activated indexer 6box
2016-07-09 06:33:22,436 - INFO - indexers - Activated indexer anizb
2016-07-09 06:33:22,448 - INFO - indexers - Activated indexer Oznzb
2016-07-09 06:33:22,450 - INFO - indexers - Activated indexer NZBFinder
2016-07-09 06:33:22,450 - INFO - indexers - Activated indexer Dusky
2016-07-09 06:33:22,453 - INFO - indexers - Removing old indexer entry oznzb from database
2016-07-09 06:33:22,513 - INFO - indexers - Removing old indexer entry NZB Finder from database
2016-07-09 06:33:22,588 - INFO - indexers - Removing old indexer entry Dusky.deepcave.net/ from database
2016-07-09 06:33:22,665 - INFO - indexers - Removing old indexer entry Dusky.deepcave from database
2016-07-09 06:33:39,861 - INFO - search - Deleting 518 search results from database that are older than 7 days
2016-07-09 06:33:39,973 - INFO - infos - Converting from tvdbid value 281537 to title 
2016-07-09 06:33:39,990 - INFO - infos - Successfully converted from tvdb value 281537 to title 
2016-07-09 06:33:40,006 - ERROR - web - Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name" FROM "indexer" AS t1 WHERE (lower("t1"."name") = ?)
PARAMS: [u'oznzb']
Traceback (most recent call last):
  File "c:\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\NZBHydra\nzbhydra\web.py", line 355, in wrapped_function
    return f(*args, **kwargs)
  File "c:\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "c:\NZBHydra\nzbhydra\web.py", line 747, in internalapi_tvsearch
    return startSearch(search_request)
  File "c:\NZBHydra\nzbhydra\web.py", line 640, in startSearch
    results = search.search(search_request)
  File "c:\NZBHydra\nzbhydra\search.py", line 207, in search
    indexers_to_call = pick_indexers(search_request)
  File "c:\NZBHydra\nzbhydra\search.py", line 114, in pick_indexers
    status = p.indexer.status.get()
  File "c:\NZBHydra\nzbhydra\search_module.py", line 57, in indexer
    return Indexer.get(fn.lower(Indexer.name) == self.settings.name.lower())
  File "c:\NZBHydra\libs\peewee.py", line 4733, in get
    return sq.get()
  File "c:\NZBHydra\libs\peewee.py", line 3041, in get
    % self.sql())
IndexerDoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name" FROM "indexer" AS t1 WHERE (lower("t1"."name") = ?)
PARAMS: [u'oznzb']

**Comment by WilliamJBrown** [comment]
I too a getting this issue. Mill post some debug in a minute.

**Comment by WilliamJBrown** [comment]
[http://imgur.com/07DbuR8](url)

And now my search works fine? I turned on debug and now search is fine? Weird. WIll post debug if it happens again.

**Comment by theotherp** [comment]
That's a different kind of error though.

**Comment by theotherp** [comment]
For some reason hydra removed an indexer from the database that was apparently still used (oznzb). No idea why. Will try to find out ;-)

**Comment by P4R4DiSi4C** [comment]
Hello,
Got the same errors and 3 failed indexers:

`2016-07-29 21:45:57,918 - INFO - search - Did not pick omgwtfnzbs.org because it is disabled temporarily due to an error: Connection failed: HTTPSConnectionPool(host='api.omgwtfnzbs.org', port=443): Read timed out. (read timeout=20)
2016-07-29 21:45:57,918 - INFO - search - Did not pick Drunken Slug because it is disabled temporarily due to an error: Access failed
2016-07-29 21:45:58,746 - ERROR - search_module - nzb.su: Error while connecting to URL https://api.nzb.su/api?apikey=<APIKEY>&t=search&extended=1&offset=0&limit=100&q=mr+robot: 503 Server Error: Service Temporarily Unavailable for url: https://api.nzb.su/api?apikey=<APIKEY>&t=search&extended=1&offset=0&limit=100&q=mr+robot
2016-07-29 21:45:59,200 - ERROR - web - datetime.datetime(2016, 7, 29, 19, 45, 57, 966000, tzinfo=tzutc()) is not JSON serializable
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "nzbhydra\web.py", line 355, in wrapped_function
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 674, in internalapi_search
  File "nzbhydra\web.py", line 640, in startSearch
  File "nzbhydra\search.py", line 265, in search
  File "nzbhydra\search.py", line 351, in search_and_handle_db
  File "json\__init__.py", line 244, in dumps
  File "json\encoder.py", line 207, in encode
  File "json\encoder.py", line 270, in iterencode
  File "json\encoder.py", line 184, in default
TypeError: datetime.datetime(2016, 7, 29, 19, 45, 57, 966000, tzinfo=tzutc()) is not JSON serializable`


Thanks

**Comment by theotherp** [comment]
Well, connection to omgwtf timed out, DS is disabled because of a prior error and nzb.su often causes trouble.

Will try to check it out on the weekend.

**Comment by P4R4DiSi4C** [comment]
Alright, thanks for your answer. Will wait for a solution :(

**Comment by theotherp** [comment]
I think the error is misleading.. When trying to provide debug info another error occurs and hides the original issue. I improved it in the latest version.

**Comment by theotherp** [comment]
Do you still get the same error when you restart hydra? If yes please post the full log (see the bug report tab in the system section).

**Comment by P4R4DiSi4C** [comment]
Alright so like I said, I get the error only when I enable nzb.su...
OMGWTFNZBS still timed out, I don't know why.

Here are the files you requested:

[logfile.txt](https://github.com/theotherp/nzbhydra/files/391377/logfile.txt)
[settings.txt](https://github.com/theotherp/nzbhydra/files/391380/settings.txt)

**Comment by theotherp** [comment]
Alright, I don't know why that happens, that part of the code is pretty old and I've never seen it before. I'll add a fallback.

**Comment by P4R4DiSi4C** [comment]
Great ! Thanks for your work !

**Comment by theotherp** [comment]
I think this is fixed. Please reopen if it occurs again.
