### ISSUE TITLE
500: INTERNAL SERVER ERROR - categories

### ISSUE THREAD

**Issue by Obscurax** [theotherp/nzbhydra#321]
So I just installed NZBHydra, configured some indexers and this error came up:
I'm using the Windows version and I updated to the latest version first.
```
An error occured :
500: INTERNAL SERVER ERROR

categories
```
When looking at the logs I see this error:

```
2016-07-08 14:55:14,740 - ERROR - web - u'categories'
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "nzbhydra\web.py", line 355, in wrapped_function
  File "nzbhydra\web.py", line 1037, in internalapi_getsafeconfig
  File "nzbhydra\config.py", line 786, in getSafeConfig
KeyError: u'categories'
```
regards Obs

**Comment by theotherp** [comment]
Sorry about that, thought I had that fixed. Open your settings.cfg and for each entry in the "indexers" section add a new line
`"categories": [],`

I'll push a fix in a couple of minutes.

**Comment by Obscurax** [comment]
That did the trick. It's working now, just downloaded my first Linux distro ;)
Thanks for the super fast support.
