### ISSUE TITLE
Unable to use with couchpotato

### ISSUE THREAD

**Issue by WilliamJBrown** [theotherp/nzbhydra#327]
It seems to be pulling results and displaying them in CP. From this I am assuming they are talking correctly. The problem is when it trys to snatch the nzb to push it to NZBGet also the same when manually pushing it. Currently what I can assume is the error is this snipet of code in the logs. I see that it says connection refused but I assume its working because it shows results within CP and not giving 0 results. I have double checked API Key and address. I am currently running CP in synology with the community app. I am running NZBHydra in docker also in synology. 

Any other things you need please ask, other than using the API it works awesome. 

`[tato.core.plugins.release] Tried to download, but the "nzb" provider gave an error: Traceback (most recent call last): File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/release/main.py", line 311, in download filedata = data.get('download')(url = data.get('url'), nzb_id = data.get('id')) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/nzb/newznab.py", line 198, in download data = self.urlopen(url, show_error = False, headers = {'User-Agent': Env.getIdentifier()}) File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/base.py", line 220, in urlopen response = r.request(method, url, **kwargs) File "/usr/local/couchpotatoserver/share/CouchPotatoServer/libs/requests/sessions.py", line 469, in request resp = self.send(prep, **send_kwargs) File "/usr/local/couchpotatoserver/share/CouchPotatoServer/libs/requests/sessions.py", line 577, in send r = adapter.send(request, **kwargs) File "/usr/local/couchpotatoserver/share/CouchPotatoServer/libs/requests/adapters.py", line 413, in send raise ConnectionError(err, request=request) ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))`

Not sure if their is a quicker form of communication we can undertake. I just finished work myself and can jump into a instant chat to try and get to the bottom of this. I will be free for the next 4ish hours.

**Comment by WilliamJBrown** [comment]
My stupid port settings on the docker app within synology were wrong. Now fixed. Might write up a NZBHydra Synology app install guide at some point. I cant be the only one struggling here.
