### ISSUE TITLE
500 Server Error with CouchPotato

### ISSUE THREAD

**Issue by jluce50** [theotherp/nzbhydra#328]
I just installed and setup NZBHydra. It's working great with Sonarr, but CP is giving me fits. When I search for a movie this is what I see in the NZBHydra log:

```
2016-07-29 18:45:45,634 - ERROR - search - Error while calling search module
Traceback (most recent call last):
  File "nzbhydra\search.py", line 371, in start_search_futures
  File "site-packages\concurrent\futures\_base.py", line 398, in result
  File "site-packages\concurrent\futures\thread.py", line 55, in run
  File "nzbhydra\search_module.py", line 92, in search
  File "nzbhydra\search_module.py", line 73, in search_ids
  File "site-packages\bunch\__init__.py", line 121, in __getattr__
AttributeError: search_ids
```

And this is what the CP logs show:

```
[hpotato.core.plugins.base] Failed opening url in Newznab: http://127.0.0.1:5075/api?imdbid=4624424&apikey=xxx&t=movie&extended=1 Traceback (most recent call last):
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5075/api?imdbid=4624424&apikey=xxx&t=movie&extended=1
```

Pretty sure it's probably a config issue on my end, but I can't figure it out.

**Comment by theotherp** [comment]
For some reason one of your enabled indexers has not set its search capabilities. Did you add an indexer in the config and selected to continue even after the check failed?

Please go to the config section and for every indexer open its config. If it says "Unknown" in "Search IDs" or "Search types" click the field and select any value. A button "Check capabilities" should appear. Click that. Afterwards save the config.

Check your log file for any prior errors, this shouldn't've happened.

**Comment by jluce50** [comment]
Ah, yup. Oznzb seems to be down. Disabling it fixed the error. 

The only "prior" errors I see are this:

```
2016-07-29 17:42:49,898 - INFO - newznab - Testing connection for host https://6box.me
2016-07-29 17:42:53,825 - ERROR - newznab - Error getting or parsing caps XML. Error message: 'NoneType' object has no attribute 'findall'
2016-07-29 17:42:53,825 - ERROR - web - 'NoneType' object has no attribute 'update'
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 355, in wrapped_function
  File "nzbhydra\web.py", line 929, in internalapi_testcaps
AttributeError: 'NoneType' object has no attribute 'update'
```

After that, it's all search_ids errors. Let me know if you want me to upload the whole log.

**Comment by theotherp** [comment]
No that's enough, thank you.

**Comment by theotherp** [comment]
That's bad error handling on my part, but I don't know why the 6box caps check failed, I just tested it and it ran fine.

**Comment by theotherp** [comment]
Please reopen if it happens again.
