### ISSUE TITLE
Getting 500: internal server error while trying to search

### ISSUE THREAD

**Issue by PoppinTaco** [theotherp/nzbhydra#331]
This is the error that I'm getting while trying to search directly from Hydra. Couch potato and Sonarr fail searches also.

Hydra worked fine until July 26th. Thats the last day anything was downloaded.

An error occured :
500: INTERNAL SERVER ERROR
an integer is required

Portion of the log with the error

2016-08-01 23:33:04,713 - INFO - search - Will ignore results older than 1200 days
2016-08-01 23:33:04,729 - ERROR - web - an integer is required
Traceback (most recent call last):
  File "c:\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\NZBHydra\nzbhydra\web.py", line 355, in wrapped_function
    return f(*args, **kwargs)
  File "c:\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "c:\NZBHydra\nzbhydra\web.py", line 674, in internalapi_search
    return startSearch(search_request)
  File "c:\NZBHydra\nzbhydra\web.py", line 640, in startSearch
    results = search.search(search_request)
  File "c:\NZBHydra\nzbhydra\search.py", line 214, in search
    indexers_to_call = pick_indexers(search_request)
  File "c:\NZBHydra\nzbhydra\search.py", line 126, in pick_indexers
    comparisonTime = arrow.utcnow().replace(hour=p.settings.hitLimitResetTime, minute=0, second=0)
  File "c:\NZBHydra\libs\arrow\arrow.py", line 414, in replace
    current = self._datetime.replace(**absolute_kwargs)
TypeError: an integer is required

**Comment by theotherp** [comment]
Apparently sometimes the config migration fails.

Please shutdown hydra, open your settings.cfg and for every indexer make sure that the "hitLimitResetTime" is either "null" or "0" (both without quotation marks).

**Comment by theotherp** [comment]
I'll try to improve the migration.

**Comment by PoppinTaco** [comment]
I'll give this a try in a bit. Thank you!

**Comment by PoppinTaco** [comment]
Thank you very much! That fixed it! Love the program keep up the great work!

**Comment by theotherp** [comment]
I know what happened, should be fixed now.
