### ISSUE TITLE
API request from Sonarr no longer working

### ISSUE THREAD

**Issue by RobbieG3** [theotherp/nzbhydra#332]
Just updated to 0.2.129. When I test the indexer in Sonarr, it says, "Unable to connect to indexer, check the log for more details"

Actual searches using the API seem to be working, though.

Log from NZB Hydra:

```
2016-08-02 19:12:00,102 - ERROR - web - newint argument must be a string or a number,not '<type 'NoneType'>'
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 508, in api
    return api_search(args)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 563, in api_search
    search_request.season = int(args["season"]) if isNumber(args["season"]) else args["season"]
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 1334, in isNumber
    int(string)
  File "C:\Program Files (x86)\NZBHydra\libs\future\types\newint.py", line 87, in __new__
    "not '{0}'".format(type(val)))
TypeError: newint argument must be a string or a number,not '<type 'NoneType'>'

```

I can search from NZB Hydra directly without issue.

Update:
Log with Debug enabled for both logfile and console log level:

```
2016-08-02 19:33:36,214 - DEBUG - web - http://127.0.0.1:5075/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<APIKEY>&offset=0&limit=100
2016-08-02 19:33:36,214 - DEBUG - web - API request: {u'minsize': None, u'raw': 0, u'attrs': None, u'query': None, u'rid': None, u'id': None, u'dbsearchid': None, u'category': None, u'group': None, u'author': None, u'imdbid': None, u'maxage': None, u'indexer': None, u'ep': None, u'maxsize': None, u'input': None, u'indexers': None, u'extended': True, u'offsets': None, u'season': None, u'minage': None, u'offset': 0, u'genre': None, 'apikey':<APIKEY>', u'episode': None, u'tvdbid': None, u'title': None, u'o': u'XML', u'cat': u'5030,5040', u'q': None, u'del': None, u't': u'tvsearch', u'limit': 100}
2016-08-02 19:33:36,216 - ERROR - web - newint argument must be a string or a number,not '<type 'NoneType'>'
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 508, in api
    return api_search(args)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 563, in api_search
    search_request.season = int(args["season"]) if isNumber(args["season"]) else args["season"]
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 1334, in isNumber
    int(string)
  File "C:\Program Files (x86)\NZBHydra\libs\future\types\newint.py", line 87, in __new__
    "not '{0}'".format(type(val)))
TypeError: newint argument must be a string or a number,not '<type 'NoneType'>'
2016-08-02 19:33:39,677 - DEBUG - web - Call to method base
2016-08-02 19:33:39,677 - DEBUG - web - Requiring auth for method base
2016-08-02 19:33:39,677 - DEBUG - web - Sending index.html
2016-08-02 19:33:40,526 - DEBUG - web - Call to method internalapi_getversions
2016-08-02 19:33:40,526 - DEBUG - web - Requiring auth for method internalapi_getversions
2016-08-02 19:33:40,528 - DEBUG - update - Loading repository version from https://raw.github.com/theotherp/nzbhydra/master/version.txt
2016-08-02 19:33:40,551 - DEBUG - web - Call to method base
2016-08-02 19:33:40,552 - DEBUG - web - Requiring auth for method base
2016-08-02 19:33:40,552 - DEBUG - web - Sending index.html
2016-08-02 19:33:40,598 - DEBUG - web - Call to method internalapi_getsafeconfig
2016-08-02 19:33:40,598 - DEBUG - web - Requiring auth for method internalapi_getsafeconfig
2016-08-02 19:33:40,599 - DEBUG - web - Call to method internalapi_askAdmin
2016-08-02 19:33:40,599 - DEBUG - web - Requiring auth for method internalapi_askAdmin
2016-08-02 19:33:40,601 - DEBUG - web - Get askadmin request
2016-08-02 19:33:40,736 - DEBUG - web - Call to method internalapi_getlogs
2016-08-02 19:33:40,736 - DEBUG - web - Requiring auth for method internalapi_getlogs
2016-08-02 19:33:40,743 - DEBUG - log - Reading log file nzbhydra.log
```

Update 2:
Not sure if this is part of the same problem, but Sonarr is returning this from the log:
```
Newznab	NZB Hydra HTTP request failed: [500:InternalServerError] [GET] at [http://127.0.0.1:5075/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100]	8:02pm

HttpClient	HTTP Error - Res: [GET] http://127.0.0.1:5075/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100: 500.InternalServerError
 newint argument must be a string or a number,not '<type 'NoneType'>'
```

**Comment by theotherp** [comment]
Which version of Python do you run? It worked fine for me before.

**Comment by RobbieG3** [comment]
Python 2.7 in Windows 7.
I think your update fixed the problem, thanks!
Daily shows seem to be working now, as well.

Looking at the logs, a lot of the indexers say: Indexer returned a result
page without total results and offset. Shame! *rings bell*
I'm assuming that is a separate issues/normal? Something I need to do
something about?

**Comment by theotherp** [comment]
No, you can ignore that.

2.7x where x is what? 9? 11? 6?

**Comment by RobbieG3** [comment]
2.7.12:d33e0cf91556, June 27, 2015
