### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by penetrance** [theotherp/nzbhydra#333]
python nzbhydra.py --nobrowser

Traceback (most recent call last):
  File "nzbhydra.py", line 24, in <module>
    from nzbhydra import indexers
  File "/opt/nzbhydra/nzbhydra/indexers.py", line 16, in <module>
    from nzbhydra.searchmodules import newznab, womble, nzbclub, nzbindex, binsearch, omgwtf, jackett, anizb #Actually used but referenced dynamically
  File "/opt/nzbhydra/nzbhydra/searchmodules/nzbindex.py", line 15, in <module>
    from bs4 import BeautifulSoup
  File "/opt/nzbhydra/libs/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/opt/nzbhydra/libs/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/opt/nzbhydra/libs/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by theotherp** [comment]
Make sure you're running hydra from its folder. Check if your python version is earlier than 2.7.9.

**Comment by penetrance** [comment]
i am running it its folder and the version of python i'm running is 
Python 2.7.12 (default, Jul 18 2016, 15:02:52) 
[GCC 4.8.4] on linux2

I think it's something I must have installed because couchpotato works on my other ubuntu install fine

**Comment by theotherp** [comment]
Yeah, sorry no idea...

**Comment by penetrance** [comment]
i ended up reinstalling ubuntu and installing nzbhydra first and it worked so it was definitely something i did.
