### ISSUE TITLE
Error loading Config page

### ISSUE THREAD

**Issue by zybron** [theotherp/nzbhydra#350]
I'm getting the error listed below when I attempt to access the Config page:

2016-08-24 12:15:27,025 - ERROR - web - The client encountered the following error: TypeError: Cannot read property '$dirty' of undefined
at Scope.ConfigController.$scope.isSavingNeeded (http://192.168.1.65:5075/static/js/nzbhydra.js:5423:27)
at http://192.168.1.65:5075/static/js/nzbhydra.js:5443:24
at Scope.$broadcast (http://192.168.1.65:5075/static/js/alllibs.js:26763:28)
at Object.transitionTo (http://192.168.1.65:5075/static/js/alllibs.js:59611:24)
at Object.go (http://192.168.1.65:5075/static/js/alllibs.js:59450:21)
at http://192.168.1.65:5075/static/js/alllibs.js:60563:20
at http://192.168.1.65:5075/static/js/alllibs.js:28368:31
at completeOutstandingRequest (http://192.168.1.65:5075/static/js/alllibs.js:15080:10)
at http://192.168.1.65:5075/static/js/alllibs.js:15356:7. Caused by: No known cause

The page doesn't render properly after this error and it's just gibberish, mostly.

I would set the log level to debug, but without accessing the config page it's a bit more difficult. I can modify the settings file directly and restart, if needed, but I would need to know exactly what to change. 

If it helps, this is a dockerized version running on unRaid. I have attached my log and settings file to this post.

[nzbhydra-debuginfo-2016-08-24-12-20.zip](https://github.com/theotherp/nzbhydra/files/435163/nzbhydra-debuginfo-2016-08-24-12-20.zip)

**Comment by theotherp** [comment]
I'll try to take a look tomorrow.

**Comment by theotherp** [comment]
Hey. Unfortunately I cannot reproduce that problem. Would you be willing to send me your original settings.cfg? Replace the API keys and send the file to [my email](mailto:theotherp@gmx.de).

Changing the log level wouldn't help.

**Comment by zybron** [comment]
Interesting. I typically use Chrome, but just tried it in Firefox and the config pages display just fine. I'm sending you my settings.cfg anyway, in case it will help you identify and fix this issue in Chrome, apparently.
