### ISSUE TITLE
Searching sometimes shows no results due to a javascript error caused by duplicate search result IDs

### ISSUE THREAD

**Issue by bblairau** [theotherp/nzbhydra#358]
After the latest update -  0.2.146  I am no longer getting any results when I search on TV shows.

I've searched and not found anyone else with a similar issue. It appears to work if I select Movies sometimes, cause now that I tried it again it's failed.

It seems to be related too

http://errors.angularjs.org/1.5.5/ngRepeat/dupes?

Which there a number of at the end of the logs.....

I've attached the logs

[settings.txt](https://github.com/theotherp/nzbhydra/files/441782/settings.txt)
[logfile.txt](https://github.com/theotherp/nzbhydra/files/441783/logfile.txt)

Hope this helps. Any more info please ask

**Comment by theotherp** [comment]
Does 0.2.147 solve this?

**Comment by bblairau** [comment]
No. Still getting the same thing with 0.2.147

2016-08-29 18:52:30,506 - INFO - <string> - Started
2016-08-29 18:52:30,509 - INFO - <string> - Loading database file nzbhydra.db
2016-08-29 18:52:30,523 - INFO - indexers - Activated indexer Binsearch
2016-08-29 18:52:30,526 - INFO - indexers - Activated indexer NZBClub
2016-08-29 18:52:30,532 - INFO - indexers - Activated indexer NZBIndex
2016-08-29 18:52:30,535 - INFO - indexers - Activated indexer Womble
2016-08-29 18:52:30,539 - INFO - indexers - Activated indexer omgwtfnzbs.org
2016-08-29 18:52:30,543 - INFO - indexers - Activated indexer oznzb
2016-08-29 18:52:30,546 - INFO - <string> - Debug mode enabled
2016-08-29 18:52:30,551 - NOTICE - <string> - Starting web app on 0.0.0.0:5075
2016-08-29 18:52:30,555 - INFO - <string> - Opening browser to http://127.0.0.1:5075
2016-08-29 18:53:07,539 - INFO - search - Returning 157 results
2016-08-29 18:53:08,125 - INFO - web - Search completed in 9084 ms
2016-08-29 18:53:08,904 - ERROR - web - The client encountered the following error: Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: titleGroup in filteredResults | itemsPerPage:limitTo track by groupId(titleGroup), Duplicate key: 26052, Duplicate value: [[{"age_days":0,"age_precise":true,"category":"TV HD","dbsearchid":null,"details_link":"https://legendwww.oznzb.com/details/bd36b7c34f17489dd866e5ec79dd0d67","downloadType":"nzb","epoch":1472455454,"has_nfo":2,"hash":-1473358277,"indexer":"oznzb","indexerguid":"bd36b7c34f17489dd866e5ec79dd0d67","indexerscore":"0","link":"http://my**************.org:5075/getnzb?searchresultid=26052","pubdate_utc":"2016-08-29T17:24:14+10:00","searchResultId":"26052","size":1773108282,"title":"The.Night.Of.Part.8.INTERNAL.720p.HDTV.x264-BATV"}]]
http://errors.angularjs.org/1.5.5/ngRepeat/dupes?p0=titleGroup%20in%20filteredResults%20%7C%20itemsPerPage%3AlimitTo%20track%20by%20groupId(titleGroup)&p1=26052&p2=%5B%5B%7B%22age_days%22%3A0%2C%22age_precise%22%3Atrue%2C%22category%22%3A%22TV%20HD%22%2C%22dbsearchid%22%3Anull%2C%22details_link%22%3A%22https%3A%2F%2Flegendwww.oznzb.com%2Fdetails%2Fbd36b7c34f17489dd866e5ec79dd0d67%22%2C%22downloadType%22%3A%22nzb%22%2C%22epoch%22%3A1472455454%2C%22has_nfo%22%3A2%2C%22hash%22%3A-1473358277%2C%22indexer%22%3A%22oznzb%22%2C%22indexerguid%22%3A%22bd36b7c34f17489dd866e5ec79dd0d67%22%2C%22indexerscore%22%3A%220%22%2C%22link%22%3A%22http%3A%2F%2Fmy**************.org%3A5075%2Fgetnzb%3Fsearchresultid%3D26052%22%2C%22pubdate_utc%22%3A%222016-08-29T17%3A24%3A14%2B10%3A00%22%2C%22searchResultId%22%3A%2226052%22%2C%22size%22%3A1773108282%2C%22title%22%3A%22The.Night.Of.Part.8.INTERNAL.720p.HDTV.x264-BATV%22%7D%5D%5D
at http://my**************.org:5075/static/js/alllibs.js:9279:12
at ngRepeatAction (http://my**************.org:5075/static/js/alllibs.js:38164:21)
at $watchCollectionAction (http://my**************.org:5075/static/js/alllibs.js:26147:13)
at Scope.$digest (http://my**************.org:5075/static/js/alllibs.js:26284:23)
at Scope.$apply (http://my**************.org:5075/static/js/alllibs.js:26548:24)
at done (http://my**************.org:5075/static/js/alllibs.js:20783:47)
at completeRequest (http://my**************.org:5075/static/js/alllibs.js:20989:7)
at XMLHttpRequest.requestLoaded (http://my**************.org:5075/static/js/alllibs.js:20922:9). Caused by: No known cause

**Comment by bblairau** [comment]
The service is running on a Windows 2012 R2 Server... Client is windows 10. I have tried with Edge and chrome. Same result on both.

**Comment by bblairau** [comment]
I may have just fixed it... Downloaded the latest windows release... Still didn't work... deleted DB and now it's working..... hopefully all good now... thanks for a great tool

**Comment by bblairau** [comment]
And now it doesn't work.. Sorry... By the time I put the comment in saying it was working, all the entries had gone off the screen and now it's doing exactly the same thing again.

**Comment by theotherp** [comment]
Damn. Yeah, I cannot reliably reproduce this, I tried yesterday and it worked flawlessly with different searches. No idea what's going on, will need to do some more tests tonight.

**Comment by theotherp** [comment]
You could rename your nzbhydra.db file and start with a new instance. Do a couple of searches to check if this still happens.

**Comment by bblairau** [comment]
It works the first time and then has the same issue for any subsequent search.

**Comment by theotherp** [comment]
Would you be willing to send me your nzbhydra.db, your original settings.cfg and the query you're doing? I have enough indexers and promise I won't use any of the API keys ;-)

It would allow me to reproduce the problem. If yes, please send it [via email](mailto:theotherp@gmx.de).

**Comment by bblairau** [comment]
It Seems a fresh install with my old DB and settings fixes the problem. Must be some along the way with a remnant from an update.
Thanks for your help
