### ISSUE TITLE
Spotweb returns error

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra#369]
I've added spotweb as a indexer. Unfortunately this does not work as it works for ie SickRage or CouchPotatoe.

I get an error when I search by using spotweb. It shows a cross in the Indexer statuses, but the response time is filled.

The log:
```
2016-09-21 15:52:04,497 - ERROR - search_module - Spotweb: Error while processing search results from indexer Spotweb
Traceback (most recent call last):
  File "/volume1/web/nzbhydra/nzbhydra/search_module.py", line 385, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/volume1/web/nzbhydra/nzbhydra/searchmodules/jackett.py", line 84, in process_query_result
    entries, total, offset = self.parseXml(xml_response, maxResults)
  File "/volume1/web/nzbhydra/nzbhydra/searchmodules/jackett.py", line 109, in parseXml
    entry = self.parseItem(item)
  File "/volume1/web/nzbhydra/nzbhydra/searchmodules/jackett.py", line 120, in parseItem
    entry.details_link = item.find("comments").text
AttributeError: 'NoneType' object has no attribute 'text'
```

[nzbhydra-debuginfo-2016-09-21-15-53.zip](https://github.com/theotherp/nzbhydra/files/485219/nzbhydra-debuginfo-2016-09-21-15-53.zip)

**Comment by pven** [comment]
When I look for something that can not be found, the check is ok. When I look for something that is found, a cross is shown.

![afbeelding 2015-06-02_09-34-09](https://cloud.githubusercontent.com/assets/671621/18715114/6488453e-8018-11e6-8452-f3a97b67a81d.jpg)

**Comment by theotherp** [comment]
You added the indexer as "Jackett". Don't do that, just click "Add new indexer". Not sure if that helps, but it's the right option anyway.

**Comment by pven** [comment]
Thanks! It works right away. :-)
