### ISSUE TITLE
No ID search possible (internal server errror)

### ISSUE THREAD

**Issue by dYna77** [theotherp/nzbhydra#375]
When is search for a movie using the id feature, this error appears:
An error occured :
500: INTERNAL SERVER ERROR
search_ids

The logs:
`2016-10-06 09:53:04,833 - INFO - infos - Successfully converted from tmdb value 71670 to imdb 
2016-10-06 09:53:04,841 - INFO - search - Did not pick Binsearch because it is disabled temporarily due to an error: Connection failed: ('Connection aborted.', error(54, 'Connection reset by peer'))
2016-10-06 09:53:04,842 - INFO - infos - Converting from imdbid value 1255916 to title 
2016-10-06 09:53:04,843 - INFO - infos - Successfully converted from imdb value 1255916 to title 
2016-10-06 09:53:04,848 - ERROR - web - search_ids
Traceback (most recent call last):
  File "/usr/home/media/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/home/media/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/home/media/nzbhydra/nzbhydra/web.py", line 350, in wrapped_function
    return f(*args, **kwargs)
  File "/usr/home/media/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/usr/home/media/nzbhydra/nzbhydra/web.py", line 722, in internalapi_moviesearch
    searchResult = startSearch(search_request)
  File "/usr/home/media/nzbhydra/nzbhydra/web.py", line 643, in startSearch
    results = search.search(search_request)
  File "/usr/home/media/nzbhydra/nzbhydra/search.py", line 242, in search
    indexers_to_call = pick_indexers(search_request)
  File "/usr/home/media/nzbhydra/nzbhydra/search.py", line 177, in pick_indexers
    if search_request.identifier_key is not None and not canUseIdKey(p, search_request.identifier_key):
  File "/usr/home/media/nzbhydra/nzbhydra/search.py", line 85, in canUseIdKey
    if key in indexer.settings.search_ids:
  File "/usr/home/media/nzbhydra/libs/bunch/__init__.py", line 121, in __getattr__
    raise AttributeError(k)
AttributeError: search_ids`

**Comment by theotherp** [comment]
Your indexer might not be configured properly. Please post the debug info from the system tab which contains an anonymized version of your settings file.

**Comment by dYna77** [comment]
[settings.txt](https://github.com/theotherp/nzbhydra/files/515940/settings.txt)

**Comment by theotherp** [comment]
Your tabula rasa config is incomplete. Remove it and add it again. Would be interesting to know how that happened.

**Comment by dYna77** [comment]
Thank you!
Now it is working :-)
