### ISSUE TITLE
Database locked error

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#38]
Database locked error with many newznab indexers (4 or more). See https://pay.reddit.com/r/usenet/comments/3vna42/presenting_nzb_hydra_the_usenet_meta_search_alpha/cxq61ii

Haven't experienced that yet but perhaps it can be reproduced.

**Comment by bleachjt** [comment]
Here's what the command window tells me when I get this error:
2015-12-07 13:39:54,505 - ERROR - web - database is locked
Traceback (most recent call last):
  File "C:\nzbhydra-master\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\nzbhydra-master\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\nzbhydra-master\nzbhydra\web.py", line 167, in decorated
    return f(*args, **kwargs)
  File "C:\nzbhydra-master\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "C:\nzbhydra-master\nzbhydra\web.py", line 346, in internalapi_moviesearch
    results = search.search(True, search_request)
  File "C:\nzbhydra-master\nzbhydra\search.py", line 139, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "C:\nzbhydra-master\nzbhydra\search.py", line 179, in search_and_handle_db
    results_by_indexer = start_search_futures(indexers_and_search_requests)
  File "C:\nzbhydra-master\nzbhydra\search.py", line 205, in start_search_futures
    results = f.result()
  File "C:\nzbhydra-master\libs\concurrent\futures\_base.py", line 396, in result
    return self.__get_result()
  File "C:\nzbhydra-master\libs\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\nzbhydra-master\nzbhydra\search_module.py", line 111, in search
    return self.execute_queries(urls)
  File "C:\nzbhydra-master\nzbhydra\search_module.py", line 227, in execute_queries
    psearch.save()
  File "C:\nzbhydra-master\nzbhydra\database.py", line 82, in save
    super(IndexerSearch, self).save(*args, **kwargs)
  File "C:\nzbhydra-master\libs\peewee.py", line 4461, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "C:\nzbhydra-master\libs\peewee.py", line 3113, in execute
    cursor = self._execute()
  File "C:\nzbhydra-master\libs\peewee.py", line 2535, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "C:\nzbhydra-master\libs\peewee.py", line 3339, in execute_sql
    self.commit()
  File "C:\nzbhydra-master\libs\peewee.py", line 3185, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "C:\nzbhydra-master\libs\peewee.py", line 3331, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked

**Comment by bleachjt** [comment]
The actual error message in the webinterface:
An error occured :
500: INTERNAL SERVER ERROR

database is locked

**Comment by Cozza38** [comment]
I just had this on a fresh install as well:

``` 
2015-12-11 23:41:11,838 - INFO - web - Using memory based cache
2015-12-11 23:43:20,110 - ERROR - search_module - An error error occurred while searching: database is locked
Traceback (most recent call last):
  File "/home/hydra/nzbhydra/nzbhydra/search_module.py", line 245, in execute_queries
    request, papiaccess = self.get_url_with_papi_access(query, "search")
  File "/home/hydra/nzbhydra/nzbhydra/search_module.py", line 211, in get_url_with_papi_access
    self.handle_indexer_success()
  File "/home/hydra/nzbhydra/nzbhydra/search_module.py", line 160, in handle_indexer_success
    indexer_status = self.indexer.status.get()
  File "/home/hydra/nzbhydra/nzbhydra/search_module.py", line 49, in indexer
    return Indexer.get(fn.lower(Indexer.name) == self.settings.name.get().lower())
  File "/home/hydra/nzbhydra/libs/peewee.py", line 4300, in get
    return sq.get()
  File "/home/hydra/nzbhydra/libs/peewee.py", line 2792, in get
    return clone.execute().next()
  File "/home/hydra/nzbhydra/libs/peewee.py", line 2839, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/hydra/nzbhydra/libs/peewee.py", line 2535, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/hydra/nzbhydra/libs/peewee.py", line 3339, in execute_sql
    self.commit()
  File "/home/hydra/nzbhydra/libs/peewee.py", line 3185, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/hydra/nzbhydra/libs/peewee.py", line 3331, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
2015-12-11 23:43:20,310 - ERROR - web - database is locked
Traceback (most recent call last):
  File "/home/hydra/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hydra/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hydra/nzbhydra/nzbhydra/web.py", line 175, in decorated
    return f(*args, **kwargs)
  File "/home/hydra/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/home/hydra/nzbhydra/nzbhydra/web.py", line 350, in internalapi_search
    results = search.search(True, search_request)
  File "/home/hydra/nzbhydra/nzbhydra/search.py", line 146, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "/home/hydra/nzbhydra/nzbhydra/search.py", line 204, in search_and_handle_db
    results_by_indexer = start_search_futures(indexers_and_search_requests)
  File "/home/hydra/nzbhydra/nzbhydra/search.py", line 230, in start_search_futures
    results = f.result()
  File "/home/hydra/nzbhydra/libs/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/home/hydra/nzbhydra/libs/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/hydra/nzbhydra/nzbhydra/search_module.py", line 116, in search
    queries_execution_result = self.execute_queries(urls)
  File "/home/hydra/nzbhydra/nzbhydra/search_module.py", line 233, in execute_queries
    psearch = IndexerSearch(indexer=self.indexer)
  File "/home/hydra/nzbhydra/nzbhydra/search_module.py", line 49, in indexer
    return Indexer.get(fn.lower(Indexer.name) == self.settings.name.get().lower())
  File "/home/hydra/nzbhydra/libs/peewee.py", line 4300, in get
    return sq.get()
  File "/home/hydra/nzbhydra/libs/peewee.py", line 2792, in get
    return clone.execute().next()
  File "/home/hydra/nzbhydra/libs/peewee.py", line 2839, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/home/hydra/nzbhydra/libs/peewee.py", line 2535, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/hydra/nzbhydra/libs/peewee.py", line 3339, in execute_sql
    self.commit()
  File "/home/hydra/nzbhydra/libs/peewee.py", line 3185, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/hydra/nzbhydra/libs/peewee.py", line 3331, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
```

**Comment by theotherp** [comment]
Hmmm, in the three months I've been developing I haven't experienced this so far so I'm kinda at a loss.

**Comment by FailOPS** [comment]
For me also on a Debian Jessie.

I'm using Default BS since LXML doesn't work together with Binsearch and nzbindex.
Also I cache everything in file system instead of the memory.

```
2016-01-10 10:43:47,170 - INFO - newznab - Query at Indexer1 returned no results
2016-01-10 10:43:47,180 - ERROR - search_module - Unable to access Indexer2: Unknown error while trying to access the indexer.
2016-01-10 10:43:47,206 - ERROR - search_module - Unable to access Indexer3: Unknown error while trying to access the indexer.
2016-01-10 10:43:47,420 - ERROR - search_module - Unable to access Indexer4: Unknown error while trying to access the indexer.
2016-01-10 10:43:47,535 - INFO - newznab - Query at Indexer5 returned no results
2016-01-10 10:43:47,752 - INFO - newznab - Query at Indexer6 returned no results
2016-01-10 10:43:47,918 - INFO - newznab - Query at Indexer7 returned no results
2016-01-10 10:43:52,931 - INFO - binsearch - Last results count 0
2016-01-10 10:43:53,096 - INFO - newznab - Query at Indexer8 returned no results
2016-01-10 10:43:53,205 - WARNING - newznab - Indexer returned a result page without total results and offset. Shame! *rings bell*
2016-01-10 10:43:53,266 - INFO - newznab - Query at Indexer9 returned no results
2016-01-10 10:43:53,642 - INFO - newznab - Query at Indexer10 returned no results
2016-01-10 10:44:15,376 - ERROR - web - database is locked
Traceback (most recent call last):
  File "/stor1/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/stor1/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/stor1/nzbhydra/nzbhydra/web.py", line 184, in decorated
    return f(*args, **kwargs)
  File "/stor1/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/stor1/nzbhydra/nzbhydra/web.py", line 393, in internalapi_search
    results = search.search(True, search_request)
  File "/stor1/nzbhydra/nzbhydra/search.py", line 175, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "/stor1/nzbhydra/nzbhydra/search.py", line 232, in search_and_handle_db
    results_by_indexer = start_search_futures(indexers_and_search_requests)
  File "/stor1/nzbhydra/nzbhydra/search.py", line 258, in start_search_futures
    results = f.result()
  File "/stor1/nzbhydra/libs/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/stor1/nzbhydra/libs/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/stor1/nzbhydra/nzbhydra/search_module.py", line 117, in search
    queries_execution_result = self.execute_queries(urls)
  File "/stor1/nzbhydra/nzbhydra/search_module.py", line 235, in execute_queries
    psearch.save()
  File "/stor1/nzbhydra/nzbhydra/database.py", line 84, in save
    super(IndexerSearch, self).save(*args, **kwargs)
  File "/stor1/nzbhydra/libs/peewee.py", line 4461, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/stor1/nzbhydra/libs/peewee.py", line 3113, in execute
    cursor = self._execute()
  File "/stor1/nzbhydra/libs/peewee.py", line 2535, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/stor1/nzbhydra/libs/peewee.py", line 3339, in execute_sql
    self.commit()
  File "/stor1/nzbhydra/libs/peewee.py", line 3185, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/stor1/nzbhydra/libs/peewee.py", line 3331, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
```

**Comment by theotherp** [comment]
@FailOPS Could you please try the develop branch code? I hope to have it fixed but as I never encountered that error I can hardly test... :-/

**Comment by theotherp** [comment]
Apparently still not fixed. As I cannot reproduce the error on my machine I have no idea what to do :-(

**Comment by theotherp** [comment]
Has anybody had this problem lately?

**Comment by theotherp** [comment]
If you guys could please check your start scripts. I assume everybody who had this problem is running it on linux?  @Mirabis was able to solve his issues by changing his systemd script. See #202 

I'm running Hydra on windows when developing and on linux in tmux and never had any problems. My code should not lock any databases. It might be possible that two instances are running and both try to lock the database.

**Comment by FailOPS** [comment]
Sorry that I didn't replied yet. Currently I move my stuff to another server and install a new instance of the Hydra.
I'm running it on a Debian Jessie and start the process within a screen-session. If everything is fine, I won't reply ;)

**Comment by wizzy99** [comment]
Running on 2.91 fc23 via a .service file.  Tried adding the PID file per Mirabis's recommendation, but still no luck.  I've seen the lock show in at least two situations.

2016-05-15 09:20:24,855 - ERROR - web - database is locked
2016-05-15 09:22:30,932 - ERROR - search - Error while calling search module

[Unit]
Description=NZBHydra Daemon
Documentation=https://github.com/theotherp/nzbhydra
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/python /home/yyy/nzbhydra/nzbhydra/nzbhydra.py -D --pidfile='/home/yyy/nzbhydra/nzbhydra.pid' --nobrowser
PIDFile=/home/yyy/nzbhydra/nzbhydra.pid
KillMode=process
Restart=on-failure
User=yyy
Group=yyy

[Install]
WantedBy=multi-user.target

-----

2016-05-15 09:20:24,855 - ERROR - web - database is locked
Traceback (most recent call last):
  File "/home/yyy/nzbhydra/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yyy/nzbhydra/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/yyy/nzbhydra/nzbhydra/nzbhydra/web.py", line 264, in wrapped_function
    return f(*args, **kwargs)
  File "/home/yyy/nzbhydra/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/home/yyy/nzbhydra/nzbhydra/nzbhydra/web.py", line 489, in getnzb
    return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"])
  File "/home/yyy/nzbhydra/nzbhydra/nzbhydra/web.py", line 663, in extract_nzb_infos_and_return_response
    link, _, _ = get_indexer_nzb_link(searchResultId, "redirect", True)
  File "/home/yyy/nzbhydra/nzbhydra/nzbhydra/api.py", line 229, in get_indexer_nzb_link
    papiaccess.save()
  File "/home/yyy/nzbhydra/nzbhydra/nzbhydra/database.py", line 134, in save
    super(IndexerApiAccess, self).save(*args, **kwargs)
  File "/home/yyy/nzbhydra/nzbhydra/libs/peewee.py", line 4920, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/home/yyy/nzbhydra/nzbhydra/libs/peewee.py", line 3373, in execute
    cursor = self._execute()
  File "/home/yyy/nzbhydra/nzbhydra/libs/peewee.py", line 2774, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/yyy/nzbhydra/nzbhydra/libs/peewee.py", line 3645, in execute_sql
    self.commit()
  File "/home/yyy/nzbhydra/nzbhydra/libs/peewee.py", line 3466, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/yyy/nzbhydra/nzbhydra/libs/peewee.py", line 3638, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked

-----
2016-05-15 09:22:30,932 - ERROR - search - Error while calling search module
Traceback (most recent call last):
  File "/home/yyy/nzbhydra/nzbhydra/nzbhydra/search.py", line 357, in start_search_futures
    results = f.result()
  File "/home/yyy/nzbhydra/nzbhydra/libs/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/home/yyy/nzbhydra/nzbhydra/libs/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yyy/nzbhydra/nzbhydra/nzbhydra/search_module.py", line 126, in search
    queries_execution_result = self.execute_queries(urls, search_request)
  File "/home/yyy/nzbhydra/nzbhydra/nzbhydra/search_module.py", line 353, in execute_queries
    self.logger.error(json.dumps(e))
  File "/usr/lib64/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: OperationalError('database is locked',) is not JSON serializable

**Comment by theotherp** [comment]
@Failops please reply anyway so I know that running it in screen does indeed help.
