### ISSUE TITLE
NZBClub not returning results (intermittently) - Error parsing XML

### ISSUE THREAD

**Issue by permster** [theotherp/nzbhydra#383]
nzbhydra 0.2.147 running on Linux Mint 17.

* What do you expect to happen? What does happen? 
On occasion when searching for something that should bring back results from nzbclub I get no results.  See snippet from debug log below.

* Have you searched for this problem? 
Yes, I found some similar references to "error parsing XML" but they were old and not directly related to nzbclub.

* Can the problem be reproduced? How?
The only way I've managed to reproduce this issue outside of the intermittent issue is to keep hitting refresh (in browser) when testing the nzbhydra API manually.  Make sure nzbclub indexer is enabled for API searches and then try this in the browser:  /api?t=search&apikey=<apikey>&q=The%20Weeknd%20Starboy%20Daft%20Punk&cat=3010&maxage=2000

This scenario should match 1 result from nzbclub.  Now refresh the browser page every 5 seconds or so.  After about the 6th or 7th refresh you will get no results from the API and in the debug log you will have an "Error parsing XML" message.  I realize this isn't normal to search like this but it's the only way I've been able to reproduce this when I want to make it happen.

2016-10-10 01:55:18,961 - DEBUG - search - Retrieved 1 of 3 calls from executor
2016-10-10 01:55:19,361 - DEBUG - search_module - NZBClub: HTTP request to indexer completed in 1169ms
2016-10-10 01:55:19,364 - DEBUG - search_module - NZBClub: Successfully loaded URL https://www.nzbclub.com/nzbrss.aspx?rpp=250&ns=1&sn=1&ig=2&st=5&q=The+Weeknd+Starboy+Daft+Punk
2016-10-10 01:55:19,365 - DEBUG - search_module - NZBClub: Started processing results
2016-10-10 01:55:19,365 - ERROR - search_module - NZBClub: Error parsing XML: ...
Traceback (most recent call last):
  File "/home/automation/.nzbhydra/nzbhydra/searchmodules/nzbclub.py", line 208, in process_query_result
    tree = ET.fromstring(xml)
  File "/usr/local/lib/python2.7.11/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/local/lib/python2.7.11/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/local/lib/python2.7.11/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0

I suspect this issue is some sort of flood control on the nzbclub side but it doesn't look like nzbhydra can handle the response correctly when this occurs.

**Comment by theotherp** [comment]
I'll check what that page contains and try to handle it better.

**Comment by theotherp** [comment]
Funny, it's an empty page without any content.

**Comment by theotherp** [comment]
Thanks for the report, is fixed in next version.

**Comment by permster** [comment]
Wow that was fast.  Thank you and congrats on your one year mark!
