### ISSUE TITLE
error when searching for a tv series in the browser interface

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#384]
* What do you expect to happen? What does happen? 

I am on the develop branch 70123cd.  I've noticed this error when doing searches within the browser interface.  I haven't noticed it through an api call yet.  It halts the call and returns a popup that says: `An error occured : 500: indexer`.  It has always happened in the part of the log that returns how many unique nzbs each indexer has.

log file: [logfile.txt](https://github.com/theotherp/nzbhydra/files/522440/logfile.txt)

```
Traceback (most recent call last):
  File "/root/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/nzbhydra/nzbhydra/web.py", line 339, in wrapped_function
    return f(*args, **kwargs)
  File "/root/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/root/nzbhydra/nzbhydra/web.py", line 756, in internalapi_tvsearch
    searchResult = startSearch(search_request)
  File "/root/nzbhydra/nzbhydra/web.py", line 633, in startSearch
    results = search.search(search_request)
  File "/root/nzbhydra/nzbhydra/search.py", line 372, in search
    if infos["indexer"] in uniqueResultsPerIndexer.keys(): #If the search failed it isn't contained in the duplicates list
KeyError: u'indexer'
```
* Can the problem be reproduced? How?

It seems to happen only when I search for a TV series for the first time using the TV category. I tried several different series and it always happened on the first search. Doesn't happen on the second attempt.

**Comment by theotherp** [comment]
Hm, cannot reproduce that. Could you try again with the latest changes?

**Comment by judhat2** [comment]
Not happening anymore after updating. Thanks for the quick fix!
