### ISSUE TITLE
Broken Pipe Error

### ISSUE THREAD

**Issue by djh82uk** [theotherp/nzbhydra#39]
Running on an ubuntu machine under a screen session (headless server, so otherwise process ends when disconnecting from SSH).  Everything set up and working fine, but the web page stopped loading after 24 hours and the below error was taken from the console:
```
self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('213.205.###.###', 37635)
Traceback (most recent call last):
  File "/root/nzbhydra/libs/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/root/nzbhydra/libs/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/root/nzbhydra/libs/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/root/nzbhydra/libs/SocketServer.py", line 657, in __init__
    self.finish()
  File "/root/nzbhydra/libs/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/root/nzbhydra/libs/socket.py", line 283, in close
    self.flush()
  File "/root/nzbhydra/libs/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe```

**Comment by theotherp** [comment]
To be honest no real idea what's going on. Perhaps somebody else has ideas? I will do some research.

Not to self: 

Try http://stackoverflow.com/questions/12591760/flask-broken-pipe-with-requests

Perhaps deploy waitress or uwsgi as proper servers.

**Comment by Mirabis** [comment]
This might help http://stackoverflow.com/questions/14207708/ioerror-errno-32-broken-pipe-python

**Comment by judhat2** [comment]
I get this exact same error when I try to make an RSS feed pointed to NZB Hydra from within NZBget.  Is NZB Hydra set up to be used as an RSS feed?  I used this `http://localhost:5075/rss?apikey=<api_key>&cat=5060` I am also using Ubuntu, NZBget 16.4, and the latest pull of NZB Hydra as of this post.

**Comment by theotherp** [comment]
Uhm no, currently no RSS. Shouldn't be too hard, though.

**Comment by alienx2** [comment]
same here problem broken pipe... error here:

`2016-01-11 16:15:08,955 - INFO - binsearch - Last results count 0
2016-01-11 16:15:23,673 - WARNING - search_module - Drunken Slug: Indexer returned a result page without total results and offset. Shame! rings bell
2016-01-11 16:15:34,245 - WARNING - search_module - NZBCat: Indexer returned a result page without total results and offset. Shame! rings bell

Exception happened during processing of request from ('192.168.1.123', 52258)
Traceback (most recent call last):
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/SocketServer.py", line 657, in __init__
    self.finish()
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/socket.py", line 283, in close
    self.flush()
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe`

**Comment by theotherp** [comment]
@alienx2 Could you please "Run threaded server" in the main settings and restart? To be honest I'm not even sure what that does, but it might help ;-)

**Comment by alienx2** [comment]
@theotherp  still same problem.. but i did tested working without NZBIndex.. then i tested NZBindex alone except all is fine. I think NZBIndex is culprit and guess NZBIndex dont like to be with group.

**Comment by theotherp** [comment]
Uhm ok. Will do some tests.

**Comment by alienx2** [comment]
@theotherp there is still same error and other error but didnt get crashed. here:

Traceback (most recent call last):
File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/nzbhydra/search_module.py", line 271, in execute_queries
self.handle_indexer_success()
File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/nzbhydra/search_module.py", line 161, in handle_indexer_success
indexer_status = self.indexer.status.get()
File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/peewee.py", line 2792, in get
return clone.execute().next()
File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/peewee.py", line 2839, in execute
self.qr = ResultWrapper(model_class, self.execute(), query_meta)
File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/peewee.py", line 2535, in _execute
return self.database.execute_sql(sql, params, self.require_commit)
File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/peewee.py", line 3339, in execute_sql
self.commit()
File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/peewee.py", line 3185, in __exit
reraise(new_type, new_type(*exc_args), traceback)
File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/peewee.py", line 3331, in execute_sql
cursor.execute(sql, params or ())
OperationalError: database is locked

**Comment by theotherp** [comment]
That's another issue that I had hoped to have fixed. Oh well...

**Comment by theotherp** [comment]
How many indexers are you running?

**Comment by alienx2** [comment]
@theotherp  6box, Binsearch, Drunken Slug, NZBCat, NZBClub, OZNZB, UsenetCrawler

**Comment by theotherp** [comment]
Closing for now. If you have this please reopen.
