### ISSUE TITLE
start fails on new installed Ubunut 16.04

### ISSUE THREAD

**Issue by count00zero** [theotherp/nzbhydra#392]
Hi there,

on a fresh install (Ubunut 16.04 @ Odroid-C2) I can't get nzbhydra (actual git master clone) to operate.
>python -V = Python 2.7.12

when running:
>python nzbhydra.py --nobrowser

```
Traceback (most recent call last):
  File "nzbhydra.py", line 24, in <module>
    from nzbhydra import indexers
  File "/xxx/nzbhydra/nzbhydra/indexers.py", line 16, in <module>
    from nzbhydra.searchmodules import newznab, womble, nzbclub, nzbindex, binsearch, omgwtf, jackett, anizb #Actually used but referenced dynamically
  File "/xxx/nzbhydra/nzbhydra/searchmodules/nzbindex.py", line 15, in <module>
    from bs4 import BeautifulSoup
  File "/xxx/nzbhydra/libs/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/xxx/nzbhydra/libs/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/xxx/nzbhydra/libs/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

Do you have any idea what the reason might be?

Tanks in advance and BR,
count

**Comment by judhat2** [comment]
I had the same problem in #371 

Try running this in the terminal and change `/xxx/` to wherever nzbhydra is installed.
```
sed -i 's/treebuilders._base/treebuilders.base/g' /xxx/nzbhydra/libs/bs4/builder/_html5lib.py
python nzbhydra.py --nobrowser
```

**Comment by count00zero** [comment]
Hi judhat2,

that's fantastic!
Worked like a charm!
Thank you very, very much!!!

BR,
Rob

**Comment by theotherp** [comment]
Awesome, thanks @judhat2

**Comment by theotherp** [comment]
I'll check if updating bs4 solves this in general.

**Comment by brumle80** [comment]
since it's not solved, at least not on F24:

updating bs4 does not solve this on Fedora Server 24
just did an update in webui and now I have to manually insert this again for nzbhydra to work again.
```

Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra.py", line 24, in <module>
    from nzbhydra import indexers
  File "/opt/nzbhydra/nzbhydra/indexers.py", line 16, in <module>
    from nzbhydra.searchmodules import newznab, womble, nzbclub, nzbindex, binsearch, jackett, anizb #Actually used but referenced dynamically
  File "/opt/nzbhydra/nzbhydra/searchmodules/nzbindex.py", line 15, in <module>
    from bs4 import BeautifulSoup
  File "/opt/nzbhydra/libs/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/opt/nzbhydra/libs/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/opt/nzbhydra/libs/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

**Comment by slug1982** [comment]
A recent Debian Jessie update broken hydra with the same error, @judhat2  patch fixed it.

Cheers
