### ISSUE TITLE
Develop:  Database disk image is malformed.

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra#393]
Swapped to develop last night and pulled in the last two commits done yesterday.   This morning on my first search I get the following error:
[nzbhydra-debuginfo-2016-10-15-11-56.zip](https://github.com/theotherp/nzbhydra/files/531253/nzbhydra-debuginfo-2016-10-15-11-56.zip)

`2016-10-15 11:50:18,157 - ERROR - web - Thread-149 - database disk image is malformed
Traceback (most recent call last):
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/www/nginx-dist/nzbhydra-develop/nzbhydra/web.py", line 339, in wrapped_function
    return f(*args, **kwargs)
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/usr/local/www/nginx-dist/nzbhydra-develop/nzbhydra/web.py", line 759, in internalapi_tvsearch
    searchResult = startSearch(search_request)
  File "/usr/local/www/nginx-dist/nzbhydra-develop/nzbhydra/web.py", line 633, in startSearch
    results = search.search(search_request)
  File "/usr/local/www/nginx-dist/nzbhydra-develop/nzbhydra/search.py", line 227, in search
    oldSearchResultsCount = countOldSearchResults(keepFor)
  File "<decorator-gen-18>", line 2, in countOldSearchResults
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/retry/api.py", line 74, in retry_decorator
    logger)
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/retry/api.py", line 33, in __retry_internal
    return f()
  File "/usr/local/www/nginx-dist/nzbhydra-develop/nzbhydra/search.py", line 408, in countOldSearchResults
    return SearchResult.select().where(SearchResult.firstFound < (datetime.date.today() - datetime.timedelta(days=keepFor))).count()
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/peewee.py", line 3203, in count
    return self.aggregate(convert=False) or 0
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/peewee.py", line 3196, in aggregate
    return self._aggregate(aggregation).scalar(convert=convert)
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/peewee.py", line 2961, in scalar
    row = self._execute().fetchone()
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/playhouse/sqliteq.py", line 101, in fetchone
    self._wait()
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/playhouse/sqliteq.py", line 54, in _wait
    raise self._exc
DatabaseError: database disk image is malformed`

![nzbhydra4](https://cloud.githubusercontent.com/assets/4558832/19411390/b92edecc-92ce-11e6-9d50-beb5beb85261.png)

Swapped back to master.  (can retest whatever..I just have to change a symbolic link)

**Comment by theotherp** [comment]
This doesn't occur on master?

**Comment by theotherp** [comment]
Had Hydra previously crashed? It seems the database is corrupt which means unfortunately you will probably need to restore an older version from the backups.

**Comment by famewolf** [comment]
It didn't occur on master and I have them in totally separate folders with their own copies of the database so I'm up and running fine with master.  The problem occured right after the database was upgraded to allow for the additional indexer stats....that and the commit for the blank entries were the only two commits.

**Comment by theotherp** [comment]
Might be caused by a bug in the migration. Please check out, restore the database backup and try again.

**Comment by famewolf** [comment]
The change you just did appears to have corrected it

# ./sync_develop.sh 
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/theotherp/nzbhydra
 * branch            develop    -> FETCH_HEAD
   97431ed..8dd5a1d  develop    -> origin/develop
Updating 97431ed..8dd5a1d
Fast-forward
 changelog.md         | 2 ++
 nzbhydra/database.py | 3 +++
 2 files changed, 5 insertions(+)


Searches working as expected in develop now.
