### ISSUE TITLE
Latest develop commit for ebook causes fatal error.

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra#397]
2016-10-17 11:37:32,514 - INFO - nzbhydra - MainThread - Started
2016-10-17 11:37:32,514 - INFO - nzbhydra - MainThread - Daemonizing...
2016-10-17 11:37:32,519 - INFO - nzbhydra - MainThread - Loading database file /usr/local/www/nginx-dist/nzbhydra-develop/nzbhydra.db
2016-10-17 11:37:32,642 - INFO - database - MainThread - Migrating database
2016-10-17 11:37:32,642 - INFO - database - MainThread - Upgrading database to version 12
2016-10-17 11:37:32,642 - INFO - database - MainThread - Adding columns to store author and title in search history
2016-10-17 11:37:32,643 - INFO - database - MainThread - Database migration completed successfully
2016-10-17 11:37:52,644 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "/usr/local/www/nginx/nzbhydra/nzbhydra.py", line 121, in run
    database.update_db(database_file)
  File "/usr/local/www/nginx-dist/nzbhydra-develop/nzbhydra/database.py", line 460, in update_db
    vi.save()
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/peewee.py", line 5195, in save
    rows = self.update(**field_dict).where(self._pk_expr()).execute()
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/peewee.py", line 3446, in execute
    return self.database.rows_affected(self._execute())
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/peewee.py", line 3824, in rows_affected
    return cursor.rowcount
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/playhouse/sqliteq.py", line 86, in rowcount
    self._wait()
  File "/usr/local/www/nginx-dist/nzbhydra-develop/libs/playhouse/sqliteq.py", line 52, in _wait
    raise ResultTimeout('results not ready, timed out.')
ResultTimeout: results not ready, timed out.

**Comment by theotherp** [comment]
Just restart,

**Comment by famewolf** [comment]
I'll add that to my "List of things to try before you look stupid opening up a ticket". ;)

**Comment by theotherp** [comment]
Well, it would be better if that error didn't happen, but I don't know why it does.
