### ISSUE TITLE
Error while updating to newest version, DB column titles not found

### ISSUE THREAD

**Issue by securos** [theotherp/nzbhydra#401]
* What do you expect to happen?
Starting the update process via the button on the Website should update it to the newest version
* What does happen? 
NZBHydra is no longer available. NZBHydra.log shows the following errors:
```

2016-10-19 16:53:40,117 - INFO - nzbhydra - MainThread - Started
2016-10-19 16:53:40,118 - INFO - nzbhydra - MainThread - Loading database file /opt/nzbhydra/nzbhydra.db
2016-10-19 16:53:40,130 - INFO - database - MainThread - Migrating database
2016-10-19 16:53:40,131 - INFO - database - MainThread - Upgrading database to version 9
2016-10-19 16:53:40,133 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "nzbhydra.py", line 121, in run
    database.update_db(database_file)
  File "/opt/nzbhydra/nzbhydra/database.py", line 370, in update_db
    rows = list(cursor.fetchall())
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 97, in fetchall
    return list(self)  # Iterating implies waiting until populated.
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 59, in __iter__
    self._wait()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 54, in _wait
    raise self._exc
OperationalError: no such table: search

```
* Have you searched for this problem? 
Yes, no results.
* Can the problem be reproduced? How?
Unsure

**Comment by theotherp** [comment]
That's a very old version. Not sure I ever expected any to update from that. If you don't have that table in the database you might as well delete nzbhydra.db and start again.

**Comment by securos** [comment]
I did end up reinstalling it, thanks. What would be your recommendation for updating NZBHydra? Should I install every new version or can I jump over a few versions?

Thanks for your great project by the way!

**Comment by theotherp** [comment]
There was an issue with older update steps for the database so I removed them. Usually it shouldn't be a problem to update even from older versions, in this case it unfortunately was.

**Comment by securos** [comment]
No worries, reinstall was fast and I remembered all my Indexer logins, so no damage done. Again, thanks for this great software!
