### ISSUE TITLE
Error: 500: INTERNAL SERVER ERROR search_ids

### ISSUE THREAD

**Issue by seanvree** [theotherp/nzbhydra#409]
When I search for a TV episode and select the proper TVDB title that is generated, it searches for a second then I get this error.  This happens with any TV series

--------------------------------------
An error occured :
500: INTERNAL SERVER ERROR

search_ids
---------------------------------------
Logs:

2016-10-25 02:11:48,122 - INFO - infos - Thread-1434 - Converting from tvdbid value 139961 to title 
2016-10-25 02:11:48,131 - INFO - infos - Thread-1434 - Successfully converted from tvdb value 139961 to title 
2016-10-25 02:11:52,138 - INFO - search - Thread-1434 - Did not pick miatrix because its API hit limit of 10 was reached. Next possible hit at 2016-10-26 08:07
2016-10-25 02:11:52,144 - ERROR - web - Thread-1434 - search_ids
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "nzbhydra\web.py", line 339, in wrapped_function
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 761, in internalapi_tvsearch
  File "nzbhydra\web.py", line 635, in startSearch
  File "nzbhydra\search.py", line 244, in search
  File "nzbhydra\search.py", line 179, in pick_indexers
  File "nzbhydra\search.py", line 87, in canUseIdKey
  File "site-packages\bunch\__init__.py", line 121, in __getattr__
AttributeError: search_ids

Running NZBhydra as a service on Windows 10
Current version: 0.2.155

**Comment by theotherp** [comment]
One of your indexers is not properly initialized. Post your debug info (as described in the template you just saw...).

**Comment by seanvree** [comment]
@theotherp See below Sir:

2016-10-25 02:38:10,921 - ERROR - web - Thread-169 - search_ids
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "nzbhydra\web.py", line 339, in wrapped_function
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 761, in internalapi_tvsearch
  File "nzbhydra\web.py", line 635, in startSearch
  File "nzbhydra\search.py", line 244, in search
  File "nzbhydra\search.py", line 179, in pick_indexers
  File "nzbhydra\search.py", line 87, in canUseIdKey
  File "site-packages\bunch\__init__.py", line 121, in __getattr__
AttributeError: search_ids
2016-10-25 02:38:12,519 - INFO - search - Thread-170 - Did not pick miatrix because its API hit limit of 10 was reached. Next possible hit at 2016-10-26 08:07
2016-10-25 02:38:12,523 - INFO - search - Thread-170 - Did not pick OMGWTFNZBs.org because it is disabled temporarily due to an error: Connection failed: HTTPConnectionPool(host='omgwtfnzbs.cme', port=80): Max retries exceeded with url: /api-docs (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x07C380F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2016-10-25 02:38:13,178 - ERROR - web - Thread-170 - search_ids
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 496, in api
  File "nzbhydra\web.py", line 570, in api_search
  File "nzbhydra\search.py", line 244, in search
  File "nzbhydra\search.py", line 179, in pick_indexers
  File "nzbhydra\search.py", line 87, in canUseIdKey
  File "site-packages\bunch\__init__.py", line 121, in __getattr__
AttributeError: search_ids
2016-10-25 02:38:13,246 - INFO - web - Thread-171 - API search request: SearchRequest [ type "movie", identifier_key "imdbid" , identifier_value "0271538", forbiddenWords "[]", requiredWords "[]", category "Movies", offset "0", loadAll "False", limit "100" ]
2016-10-25 02:38:13,305 - INFO - infos - Thread-171 - Converting from imdbid value 0271538 to title 
2016-10-25 02:38:13,308 - INFO - infos - Thread-171 - Successfully converted from imdb value 0271538 to title 
2016-10-25 02:38:13,312 - INFO - search - Thread-171 - Did not pick omgwtfnzbs.org because it is disabled temporarily due to an error: Connection failed: HTTPConnectionPool(host='omgwtfnzbs.cme', port=80): Max retries exceeded with url: /api-docs (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x07C380F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
2016-10-25 02:38:16,598 - INFO - search - Thread-171 - Did not pick nzbs2go.com/ because it is disabled temporarily due to an error: Connection failed: HTTPConnectionPool(host='nzbs2go.com', port=80): Max retries exceeded with url: /api?apikey=<APIKEY>&t=tvsearch&extended=1&offset=0&limit=100&cat=5000&password=<PASSWORD> (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x02AB7B50>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed',))
2016-10-25 02:38:16,674 - INFO - search - Thread-171 - Did not pick casstormnzb.com because it is disabled temporarily due to an error: Connection failed: 429 Client Error: Too Many Requests for url: http://nzb.casstormnzb.com/api?apikey=<APIKEY>&t=tvsearch&extended=1&offset=0&limit=100&cat=5000&password=<PASSWORD>

**Comment by theotherp** [comment]
Noooo, send your debug info. See http://127.0.0.1:5075/system/bugreport

**Comment by seanvree** [comment]
@theotherp , sorry about that. 

Log file: https://drive.google.com/file/d/0B7OujkYtbxFNYXAwckxreWNRTTQ/view?usp=sharing

Settings:  https://drive.google.com/file/d/0B7OujkYtbxFNd3FiUmhoYUtuTzQ/view?usp=sharing

**Comment by theotherp** [comment]
Open your settings.cfg, find the entry for omgwtfnzbs and add a new line
`"search_ids": [],`
Restart Hydra.

Not sure why that is missing, will check the code

**Comment by seanvree** [comment]
@theotherp ... okay, it looked like it was missing a "]," after that entry, 

so I added that but now the NZBHydra Service won't start now. 

Getting this Windows Service error:
------------The description for Event ID 7023 from source Service Control Manager cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

User Energy Server Service WILLAMETTE
%%268439640

The resource loader failed to find MUI file
------------------

Here is my settings.conf file:

https://drive.google.com/file/d/0B7OujkYtbxFNdDcwVnR5cXk1eW8/view?usp=sharing

**Comment by theotherp** [comment]
Oops, sorry, that was the wrong advice. Revert to the old settings. I'll do some tests later tonight.

**Comment by seanvree** [comment]
@theotherp ...Shoot, I stupidly didn't make a backup of the .cfg file when I made the change and now I can find out where I made the change??!! I've tried a couple entries, but it's not working.  I can't access the GUI now because the service won't start.

**Comment by theotherp** [comment]
See the one attached. That should work.

**Comment by theotherp** [comment]
Also, 30 indexers? Holy shit...

**Comment by theotherp** [comment]
Post or send me your mail address and I'll send you the file.

**Comment by theotherp** [comment]
By the way, you should delete the settings file from your google drive. Whoever watched this issue might still be able to download it.

**Comment by theotherp** [comment]
Also, you have omgwtf added as newznab indexer. You should delete that one.

**Comment by seanvree** [comment]
@theotherp seanvree@gmail.com

**Comment by seanvree** [comment]
@theotherp 

Got the .CFG file. THANKS!

So, are you still working on the original problem? or did you make changes to the .CFG file?

**Comment by seanvree** [comment]
hey @theotherp , I updated with the new version today, and now I'm back with the service unable to start. 

I replaced the setting.cfg you sent me but I'm still stuck!

Any advice?

**Comment by theotherp** [comment]
Huh. So you were able to start the program, then made an update and then you cannot search again? The log shows the same error? Did you change anything in the settings?

**Comment by seanvree** [comment]
@theotherp , once I replaced the settings.cfg you sent me it worked great, then I saw there was an update, so I updated, didn't change anything and now the service won't start?

**Comment by seanvree** [comment]
Update #2:  I went back to version  0.2.154 and its now working even with the old settings.cfg file. 

So something in the new release is broken on windows. Has nothing to do with my settings or .db

**Comment by theotherp** [comment]
Never thought to test it with the binary release. Will do so tomorrow.

**Comment by theotherp** [comment]
Sorry about that, should work with 0.2.159.

**Comment by seanvree** [comment]
BOOM!  Thanks brotha.
