### ISSUE TITLE
askForCategory Error on Windows

### ISSUE THREAD

**Issue by Corrupta** [theotherp/nzbhydra#42]
An error occured :
500: INTERNAL SERVER ERROR

askForCategory

2015-12-11 06:23:25,259 - ERROR - web - u'askForCategory'

send to sab doesn't work even when specifying a category in downloader settings. Without specifying a category you are only shown "No Category" as an option and that doesn't work either.

**Comment by Corrupta** [comment]
send to sab doesn't work even when specifying a category in downloader settings. Without specifying a category you are only shown "No Category" as an option and that doesn't work either.

**Comment by theotherp** [comment]
Works fine for me, with preset category and without.

You sure the connection to sabnzbd works? Also please make sure that you checked out all the code and that your settings.cfg is correct (check if the setting "askForCategory" is set in the downloader category).

**Comment by Corrupta** [comment]
older version is working but new version even without settings (clean install) does this:

2015-12-11 07:04:58,686 - ERROR - web - u'askForCategory'
Traceback (most recent call last):
  File "D:\nzbhydra-master\libs\flask\app.py", line 1475, in full_dispatch_reque
st
    rv = self.dispatch_request()
  File "D:\nzbhydra-master\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\nzbhydra-master\nzbhydra\web.py", line 173, in decorated
    return f(*args, **kwargs)
  File "D:\nzbhydra-master\libs\flask_cache\__init__.py", line 537, in decorated
_function
    rv = f(*args, **kwargs)
  File "D:\nzbhydra-master\nzbhydra\web.py", line 664, in internalapi_getsafecon
fig
    return jsonify(config.getSafeConfig())
  File "D:\nzbhydra-master\nzbhydra\config.py", line 560, in getSafeConfig
    "downloader": {"downloader": cfg["downloader"]["downloader"], "askForCategor
y": cfg["downloader"]["askForCategory"]}
KeyError: u'askForCategory'

**Comment by theotherp** [comment]
Yeah, sorry, my fault. Should be fixed now, but I'm on mobile and cannot actually test. Will do so later.

**Comment by theotherp** [comment]
Fixed with 642ad274fb688b0e9814bb3bd204dcd1de6fa7ef.

**Comment by Corrupta** [comment]
Yep it's working now, now just really need omgwtf working to get rid of mega, really liking hydra :)
