### ISSUE TITLE
Hydra Docker error

### ISSUE THREAD

**Issue by DCPDad** [theotherp/nzbhydra#423]
Hello-
I am not familiar with github, but thought I would post my error. Everything has been working great until my Hydra Docker upgraded this morning. OS is unRaid.

The nzbhydra.log shows this:

2016-11-08 22:19:35,933 - INFO - nzbhydra - MainThread - Started
2016-11-08 22:19:35,933 - INFO - nzbhydra - MainThread - Loading database file /config/hydra/nzbhydra.db
2016-11-08 22:19:35,937 - INFO - database - MainThread - Migrating database
2016-11-08 22:19:35,937 - INFO - database - MainThread - Upgrading database to version 9
2016-11-08 22:19:35,938 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "/opt/hydra/nzbhydra.py", line 121, in run
    database.update_db(database_file)
  File "/opt/hydra/nzbhydra/database.py", line 366, in update_db
    rows = list(cursor.fetchall())
  File "/opt/hydra/libs/playhouse/sqliteq.py", line 89, in fetchall
    return list(self)  # Iterating implies waiting until populated.
  File "/opt/hydra/libs/playhouse/sqliteq.py", line 56, in __iter__
    self._wait()
  File "/opt/hydra/libs/playhouse/sqliteq.py", line 53, in _wait
    raise self._exc
OperationalError: no such table: search

Any thoughts to help a novice?

Many thx-
D

**Comment by theotherp** [comment]
That lines don't match my code so I'm not sure at what point the update fails. I cannot provide proper support for the docker installations. To fix this error shutdown hydra, delete nzbhydra.db and restart hydra. You will lose all your history and stats but none of your settings. Sorry about that.

**Comment by DCPDad** [comment]
Excellent! That worked. I very much appreciate your help and more importantly, I appreciate Hydra!!
TY!
