### ISSUE TITLE
nzbhydra does not start after update

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra#424]
* What do you expect to happen? What does happen? 
I expect nzbhydra to start on my Synology ;-)

* Have you searched for this problem? 
Yes, simular problems but with different errors

* Can the problem be reproduced? How?
Yes, start nzbhydra:
> python2.7 nzbhydra.py --nobrowser

```
2016-11-11 10:18:14,787 - NOTICE - nzbhydra - MainThread - Starting NZBHydra 0.2.165
2016-11-11 10:18:14,788 - NOTICE - nzbhydra - MainThread - Base path is /volume1/web/nzbhydra
2016-11-11 10:18:14,786 - NOTICE - nzbhydra - MainThread - Starting NZBHydra 0.2.165
2016-11-11 10:18:14,790 - NOTICE - nzbhydra - MainThread - Loading settings from /volume1/web/nzbhydra/settings.cfg
2016-11-11 10:18:14,789 - NOTICE - nzbhydra - MainThread - Base path is /volume1/web/nzbhydra
2016-11-11 10:18:14,791 - NOTICE - nzbhydra - MainThread - Loading settings from /volume1/web/nzbhydra/settings.cfg
2016-11-11 10:18:33,258 - NOTICE - nzbhydra - MainThread - Starting NZBHydra 0.2.165
2016-11-11 10:18:33,259 - NOTICE - nzbhydra - MainThread - Base path is /volume1/web/nzbhydra
2016-11-11 10:18:33,260 - NOTICE - nzbhydra - MainThread - Loading settings from /volume1/web/nzbhydra/settings.cfg
An error occured during migrating the old config. Sorry about that...:
Traceback (most recent call last):
  File "nzbhydra.py", line 92, in run
    config.load(settings_file)
  File "/volume1/web/nzbhydra/nzbhydra/config.py", line 753, in load
    raise e
ValueError: No JSON object could be decoded
Trying to log messages from migration...
2016-11-11 10:18:33,405 - WARNING - config - MainThread - An error occurred while migrating the settings: Traceback (most recent call last):
  File "/volume1/web/nzbhydra/nzbhydra/config.py", line 747, in load
    migratedConfig = loadAndMigrateSettingsFile(filename)
  File "/volume1/web/nzbhydra/nzbhydra/config.py", line 466, in loadAndMigrateSettingsFile
    config = json.load(settingsFile, encoding="utf-8")
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by pven** [comment]
Btw: running at the last updat according to git

```
DiskStation> /volume1/@appstore/git/bin/git pull
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
From git://github.com/theotherp/nzbhydra
   a3ece9b..cc41e72  develop    -> origin/develop
Already up-to-date.
DiskStation>
```

**Comment by pven** [comment]
Oh damn, by playing with git I deleted my original settings.cfg. Sorry for that! After deleting settings.cfg and reconfiguring nzbhydra everything works fine again.

**Comment by theotherp** [comment]
Don't worry, at least it works now. Cheers.
