### ISSUE TITLE
[Errno 98] Address in use

### ISSUE THREAD

**Issue by vurtomatic** [theotherp/nzbhydra#442]
Hydra seems to be working fine but this keeps appearing in the log:

2016-11-26 12:21:51,257 - INFO - nzbhydra - MainThread - Started
2016-11-26 12:21:51,258 - INFO - nzbhydra - MainThread - Loading database file /config/hydra/nzbhydra.db  
2016-11-26 12:21:51,259 - INFO - nzbhydra - MainThread - Starting db
2016-11-26 12:21:51,262 - INFO - indexers - MainThread - Activated indexer Binsearch
2016-11-26 12:21:51,264 - INFO - indexers - MainThread - Activated indexer NZBClub
2016-11-26 12:21:51,266 - INFO - indexers - MainThread - Activated indexer NZBIndex
2016-11-26 12:21:51,267 - INFO - indexers - MainThread - Activated indexer Womble
2016-11-26 12:21:51,269 - INFO - indexers - MainThread - Activated indexer DogNZB
2016-11-26 12:21:51,271 - INFO - indexers - MainThread - Activated indexer NZBGeek
2016-11-26 12:21:51,273 - INFO - indexers - MainThread - Activated indexer NZBCat
2016-11-26 12:21:51,274 - INFO - indexers - MainThread - Activated indexer SimplyNZBs
2016-11-26 12:21:51,275 - NOTICE - nzbhydra - MainThread - Starting web app on 0.0.0.0:5075
2016-11-26 12:21:51,275 - NOTICE - nzbhydra - MainThread - Go to https://advurt.net/hydra/ for the frontend
2016-11-26 12:21:51,276 - INFO - web - MainThread - Running threaded server

2016-11-26 12:21:51,278 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "/opt/hydra/nzbhydra.py", line 189, in run
    web.run(host, port, basepath)
  File "/opt/hydra/nzbhydra/web.py", line 1341, in run
    app.run(host=host, port=port, debug=config.settings.main.debug, threaded=config.settings.main.runThreaded, use_reloader=config.settings.main.flaskReloader)
  File "/opt/hydra/libs/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/opt/hydra/libs/werkzeug/serving.py", line 625, in run_simple
    inner()
  File "/opt/hydra/libs/werkzeug/serving.py", line 603, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/opt/hydra/libs/werkzeug/serving.py", line 506, in make_server
    passthrough_errors, ssl_context)
  File "/opt/hydra/libs/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/opt/hydra/libs/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/opt/hydra/libs/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/opt/hydra/libs/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/opt/hydra/libs/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use

**Comment by judhat2** [comment]
Do you happen to run nzbhydra as a service and have it set to restart on a failure?  Since I started using a service file to start Hydra at system boot, this happens when I update Hydra and it restarts itself.  My machine sees it as a failure since it wasn't stopped using systemctl, such as `systemctl stop nzbhydra.service`.  So Hydra ends up being restarted by Hydra's update process and systemctl causing this error and a shutdown.  I end up having to start Hydra again manually after each update.  Here's a log to what I am referring to: 
[logfile.txt](https://github.com/theotherp/nzbhydra/files/614373/logfile.txt)  

Maybe NZBHydra can try to check if the system commands stop/restart are available, then do what it does now if it can't be stopped that way?

**Comment by theotherp** [comment]
I don't know anything about unix services and to be honest don't want to... It's a PITA to debug. I would relatively specific instructions what to do...

**Comment by vurtomatic** [comment]
Hydra is running as a docker in unRAID so yes I think that qualifies as a service.

I just did a comparison and it seems to prove @judhat2 's theory.

Stop and start Hydra docker from the unRAID interface, no error.
Restart from within Hydra, the error appears.

As long as it's not some kinda critical error, Hydra seems to run alright.

**Comment by theotherp** [comment]
I have no idea how to prevent that stuff from happening. Do you guys use SB or sabnzbd? I think both use a similar mechanism to restart.

I could add an option to shutdown Hydra instead of restarting it so that the service manager does the actual restart. Would that help?

**Comment by vurtomatic** [comment]
Yes I use sabnzbd as a docker in unraid too, but haven't encountered this error.

I'm even less versed than you are in this so I can't say if that will help, sorry.

**Comment by theotherp** [comment]
Let me know if that helps.

**Comment by judhat2** [comment]
That fixed the error doing just a restart.  I'll see what happens on the next update and restart and let you know.
