### ISSUE TITLE
nzbhydra and couchpotato does not work after update

### ISSUE THREAD

**Issue by nizce** [theotherp/nzbhydra#443]
Just updated my nzbhydra version from 168 -> 171.
I don't know that I changed anything after the update but couchpotato and nzbhydra no long work together.
Searching and sending NZBs directly from nzbhydra->sabnzbd  still works. 
But when I try to grab something via couchpotato I get this in the couchpotato log and nzbhydra log:

nzbhydra:
---------------------------------------------------------------------------
2016-11-27 17:53:28,270 - DEBUG - web - Thread-136 - Call to method internalapi_getlogs
2016-11-27 17:53:28,270 - DEBUG - web - Thread-136 - Requiring auth for method internalapi_getlogs
2016-11-27 17:53:28,271 - DEBUG - log - Thread-136 - Reading log file /config/hydra/nzbhydra.log
2016-11-27 17:53:40,048 - DEBUG - web - Thread-137 - http://192.168.3.20:5075/api?t=get&id=a33690e282029c5f5e80b6578ddc8fe7acf5dd5a&apikey=<APIKEY>
2016-11-27 17:53:40,048 - DEBUG - web - Thread-137 - API request: {u'minsize': None, u'raw': 0, u'attrs': None, u'query': None, u'rid': None, u'id': u'a33690e282029c5f5e80b6578ddc8fe7acf5dd5a', u'dbsearchid': None, u'category': None, u'group': None, u'author': None, u'imdbid': None, u'maxage': None, u'indexer': None, u'ep': None, u'maxsize': None, u'input': None, u'indexers': None, u'extended': None, u'offsets': None, u'season': None, u'minage': None, u'offset': 0, u'genre': None, 'apikey':<APIKEY>', u'episode': None, u'tvdbid': None, u'title': None, u'o': u'XML', u'cat': None, u'q': None, u'del': None, u't': u'get', u'limit': 100}
2016-11-27 17:53:40,049 - ERROR - web - Thread-137 - API NZB download request with invalid id a33690e282029c5f5e80b6578ddc8fe7acf5dd5a
2016-11-27 17:53:42,772 - DEBUG - web - Thread-138 - Call to method base
2016-11-27 17:53:42,773 - DEBUG - web - Thread-138 - Sending index.html
2016-11-27 17:53:43,046 - DEBUG - web - Thread-144 - Call to method base
2016-11-27 17:53:43,047 - DEBUG - web - Thread-144 - Sending index.html
2016-11-27 17:53:43,077 - DEBUG - web - Thread-146 - Call to method internalapi_getsafeconfig
2016-11-27 17:53:43,083 - DEBUG - web - Thread-147 - Call to method internalapi_askAdmin
2016-11-27 17:53:43,084 - DEBUG - web - Thread-147 - Requiring auth for method internalapi_askAdmin
2016-11-27 17:53:43,085 - DEBUG - web - Thread-147 - Get askadmin request
2016-11-27 17:53:43,149 - DEBUG - web - Thread-149 - Call to method internalapi_getlogs
2016-11-27 17:53:43,149 - DEBUG - web - Thread-149 - Requiring auth for method internalapi_getlogs
2016-11-27 17:53:43,152 - DEBUG - log - Thread-149 - Reading log file /config/hydra/nzbhydra.log
------------------------------------------------------------------------------------------

Couchpotato:
-----------------------------------------------------------------------------------------------
11-27 17:53:40
ERROR
[ase.providers.nzb.newznab] Failed download from 192.168.3.20: Traceback (most recent call last):
  File "/usr/lib/couchpotato/couchpotato/core/media/_base/providers/nzb/newznab.py", line 190, in download
    data = self.urlopen(url, show_error = False, headers = {'User-Agent': Env.getIdentifier()})
  File "/usr/lib/couchpotato/couchpotato/core/plugins/base.py", line 221, in urlopen
    response.raise_for_status()
  File "/usr/lib/couchpotato/libs/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://192.168.3.20:5075/api?t=get&id=a33690e282029c5f5e80b6578ddc8fe7acf5dd5a&apikey=xxx
--------------------------------------------------------------------------------

I can see that nzbhydra complains about: **"API NZB download request with invalid id"**.
Don't know what that means though. There is a search generated in nzbhydra and when I check the 'search history', but it does not show up under 'download history'.

**Comment by theotherp** [comment]
Oops.

**Comment by nizce** [comment]
haha wow that was fast!! :)

**Comment by nizce** [comment]
Thanks, works like a charm!
