### ISSUE TITLE
recheck indexers capabilities fails

### ISSUE THREAD

**Issue by sumofatguy** [theotherp/nzbhydra#477]
Hello,

I noticed some of my indexers have the wrong capabilities enabled (ex: pfmonkey did not have IMDB search ids enabled). I tried clicking the check capabilities button, but it just spins away without actually checking the indexers capabilities. 

The function works properly on newly added indexers, I just don't want to lose all the stats I have by removing/readding every indexer.

run on windows7 from source, url base /hydra, version 0.2.179

It does not produce any debug log errors. I get a console error in chrome/firefox/ie though:

`Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ReferenceError: settings is not defined
    at Scope.$scope.checkCaps (http://localhost:5075/hydra/static/js/nzbhydra.js:3605:25)
    at fn (eval at compile (http://localhost:5075/hydra/static/js/alllibs.js:23643:15), <anonymous>:4:218)
    at expensiveCheckFn (http://localhost:5075/hydra/static/js/alllibs.js:24696:18)
    at callback (http://localhost:5075/hydra/static/js/alllibs.js:34229:17)
    at Scope.$eval (http://localhost:5075/hydra/static/js/alllibs.js:26440:28)
    at Scope.$apply (http://localhost:5075/hydra/static/js/alllibs.js:26540:25)
    at HTMLButtonElement.<anonymous> (http://localhost:5075/hydra/static/js/alllibs.js:34234:23)
    at HTMLButtonElement.dispatch (http://localhost:5075/hydra/static/js/alllibs.js:4435:9)
    at HTMLButtonElement.elemData.handle (http://localhost:5075/hydra/static/js/alllibs.js:4121:28) undefined
ReferenceError: settings is not defined(…)`

Any idea what this is? 
![untitled-2](https://cloud.githubusercontent.com/assets/228393/21165452/ae8b85c6-c15c-11e6-9a57-3f1d8098dae3.png)
[logfile.txt](https://github.com/theotherp/nzbhydra/files/650556/logfile.txt)

**Comment by jaywk** [comment]
I can confirm this bug on my end as well. Running version 0.2.179.

**Comment by seanvree** [comment]
Yeah, glad we got this bug figured out.  Also related to https://github.com/theotherp/nzbhydra/issues/432
