### ISSUE TITLE
'NoneType' object has no attribute error

### ISSUE THREAD

**Issue by Poag** [theotherp/nzbhydra#49]
Running on version 0.0.1a36 my log is full of the errors below this morning. I've included the newshost failures for information incase its related.

```
2015-12-14 08:10:19,440 - INFO - web - API search request: SearchRequest [ type "tv", category "5000", offset "0", limit "100"
2015-12-14 08:10:19,543 - ERROR - search_module - Error while connecting to URL https://newshost.co.za/rss?fr=false&sec=tv-hd:                                                                                             ('Connection aborted.', error(104, 'Connection reset by peer'))
2015-12-14 08:10:19,641 - ERROR - search_module - Error while connecting to URL https://newshost.co.za/rss?fr=false&sec=tv-x26                                                                                            4: ('Connection aborted.', error(104, 'Connection reset by peer'))
2015-12-14 08:10:19,731 - ERROR - search_module - Error while connecting to URL https://newshost.co.za/rss?fr=false&sec=tv-sd:                                                                                             ('Connection aborted.', error(104, 'Connection reset by peer'))
2015-12-14 08:10:19,791 - ERROR - search_module - Error while connecting to URL https://newshost.co.za/rss?fr=false&sec=tv-dvd                                                                                            : ('Connection aborted.', error(104, 'Connection reset by peer'))
2015-12-14 08:10:20,711 - ERROR - web - 'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/home/nzb/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nzb/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nzb/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/home/nzb/nzbhydra/nzbhydra/web.py", line 304, in api
    result = search.search(False, search_request)
  File "/home/nzb/nzbhydra/nzbhydra/search.py", line 170, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "/home/nzb/nzbhydra/nzbhydra/search.py", line 227, in search_and_handle_db
    results_by_indexer = start_search_futures(indexers_and_search_requests)
  File "/home/nzb/nzbhydra/nzbhydra/search.py", line 253, in start_search_futures
    results = f.result()
  File "/home/nzb/nzbhydra/libs/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/home/nzb/nzbhydra/libs/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nzb/nzbhydra/nzbhydra/search_module.py", line 91, in search
    urls = self.get_showsearch_urls(search_request)
  File "/home/nzb/nzbhydra/nzbhydra/searchmodules/omgwtf.py", line 193, in get_showsearch_urls
    return self.get_search_urls(search_request)
  File "/home/nzb/nzbhydra/nzbhydra/searchmodules/omgwtf.py", line 176, in get_search_urls
    f.host = f.host.replace("api", "rss") #Haaaaacky
```

**Comment by theotherp** [comment]
Shouldn't be related. I don't understand the womble errors, I can connect fine on my home PC and connection fails on my dedicated server.

For some reason your omgtwfnzbs host is not found in the config or cannot be read. Please check if your settings.cfg contains "https://api.omgwtfnzbs.org". I'll check the code in the evening.

**Comment by Poag** [comment]
Righto, disabled omgwtf and error has gone away. Its odd i don't recall enabling it. :/

**Comment by theotherp** [comment]
Oops, it's enabled by default.
