### ISSUE TITLE
Unable to update from 0.2.150 to most recent version.

### ISSUE THREAD

**Issue by whispy** [theotherp/nzbhydra#505]
Sorry for this, I know it's a pain to go back and worry about such an old version. I've tried restarting after the update, but it still fails.

```
Checking out files: 100% (1326/1326), done.
HEAD is now at 8dd5a1d Fixed: Database migration of 0.2.149 would not store new database version meaning the migration might've been done on every startup. See #393.
2017-01-12 14:24:28,845 - INFO - update - Thread-37 - git output: From https://github.com/theotherp/nzbhydra
 * branch            master     -> FETCH_HEAD
Updating 8dd5a1d..2723b7d
error: Your local changes to the following files would be overwritten by merge:
	...[snip]...
Please, commit your changes or stash them before you can merge.
Aborting
2017-01-12 14:24:32,160 - INFO - nzbhydra - MainThread - Started
2017-01-12 14:24:32,162 - INFO - nzbhydra - MainThread - Loading database file /config/hydra/nzbhydra.db
2017-01-12 14:24:32,230 - INFO - nzbhydra - MainThread - Starting db
... [snip] ...
2017-01-12 14:24:32,270 - INFO - web - MainThread - Running threaded server
2017-01-12 14:24:32,381 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "/config/hydra/nzbhydra.py", line 179, in run
    web.run(host, port, basepath)
  File "/config/hydra/nzbhydra/web.py", line 1354, in run
    app.run(host=host, port=port, debug=config.settings.main.debug, threaded=config.settings.main.runThreaded, use_reloader=config.settings.main.flaskReloader)
  File "/config/hydra/libs/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/config/hydra/libs/werkzeug/serving.py", line 625, in run_simple
    inner()
  File "/config/hydra/libs/werkzeug/serving.py", line 603, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/config/hydra/libs/werkzeug/serving.py", line 506, in make_server
    passthrough_errors, ssl_context)
  File "/config/hydra/libs/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/config/hydra/libs/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/config/hydra/libs/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/config/hydra/libs/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/config/hydra/libs/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
```

**Comment by whispy** [comment]
I just deleted the Docker image, updated to the newest image, and restarted my container. That updated it fine for me. This can be closed.

**Comment by theotherp** [comment]
That's what I would've recommended anyway... ;-)
