### ISSUE TITLE
tvidcache.tvrage Can't be null

### ISSUE THREAD

**Issue by Mirabis** [theotherp/nzbhydra#53]
2015-12-16 00:33:30,142 - ERROR - web - NOT NULL constraint failed: tvidcache.tvrage
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 178, in decorated
    return f(*args, **kwargs)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 436, in internalapi_tvsearch
    results = search.search(True, search_request)
  File "/opt/nzbhydra/nzbhydra/search.py", line 170, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "/opt/nzbhydra/nzbhydra/search.py", line 227, in search_and_handle_db
    results_by_indexer = start_search_futures(indexers_and_search_requests)
  File "/opt/nzbhydra/nzbhydra/search.py", line 253, in start_search_futures
    results = f.result()
  File "/opt/nzbhydra/libs/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/opt/nzbhydra/libs/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/nzbhydra/nzbhydra/search_module.py", line 85, in search
    urls = self.get_showsearch_urls(search_request)
  File "/opt/nzbhydra/nzbhydra/searchmodules/newznab.py", line 162, in get_showsearch_urls
    search_request.identifier_value = infos.tvdbid_to_rid(search_request.identifier_value)
  File "/opt/nzbhydra/nzbhydra/infos.py", line 62, in tvdbid_to_rid
    id.save()
  File "/opt/nzbhydra/libs/peewee.py", line 4461, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/opt/nzbhydra/libs/peewee.py", line 3113, in execute
    cursor = self._execute()
  File "/opt/nzbhydra/libs/peewee.py", line 2535, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/opt/nzbhydra/libs/peewee.py", line 3339, in execute_sql
    self.commit()
  File "/opt/nzbhydra/libs/peewee.py", line 3185, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/opt/nzbhydra/libs/peewee.py", line 3331, in execute_sql
    cursor.execute(sql, params or ())
IntegrityError: NOT NULL constraint failed: tvidcache.tvrage

**Comment by Mirabis** [comment]
If key is present, but tvRage = None => crash.

Will do a PR soon.
