### ISSUE TITLE
NZB downloads fail

### ISSUE THREAD

**Issue by anonvoy** [theotherp/nzbhydra#543]
When trying to download a NZB, the program fails, and the error message "NOT NULL constraint failed: indexernzbdownload.time" is displayed in the browser. Only this message as plain text, nothing else. I'm on 0.2.199, Linux. This started today after the latest updates.

Log:

    2017-02-11 15:25:37,325 - DEBUG - web - Thread-69 - Call to method getnzb  
    2017-02-11 15:25:37,325 - DEBUG - web - Thread-69 - Requiring auth for method getnzb
    2017-02-11 15:25:37,325 - DEBUG - web - Thread-69 - Get NZB request with args {u'internal': True, u'searchresultid': u'88d001423e657f96ad798a1bdc445eb6cff49c72', u'downloader': None}
    2017-02-11 15:25:37,328 - INFO - web - Thread-69 - Internal request from 127.0.0.1 to download *****
    2017-02-11 15:25:37,349 - ERROR - web - Thread-69 - NOT NULL constraint failed: indexernzbdownload.time
    Traceback (most recent call last):
    File "/home/abc/.nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
    File "/home/abc/.nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "/home/abc/.nzbhydra/nzbhydra/web.py", line 379, in wrapped_function
    return f(*args, **kwargs)
    File "/home/abc/.nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
    File "/home/abc/.nzbhydra/nzbhydra/web.py", line 675, in getnzb
    return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
    File "/home/abc/.nzbhydra/nzbhydra/web.py", line 875, in extract_nzb_infos_and_return_response
    link, _, _ = get_indexer_nzb_link(searchResultId, mode="redirect", log_api_access=True, internal=internal)
    File "/home/abc/.nzbhydra/nzbhydra/api.py", line 257, in get_indexer_nzb_link
    pnzbdl.save()
    File "/home/abc/.nzbhydra/nzbhydra/database.py", line 146, in save
    super(IndexerNzbDownload, self).save(*args, **kwargs)
    File "/home/abc/.nzbhydra/libs/peewee.py", line 4990, in save
    pk_from_cursor = self.insert(**field_dict).execute()
    File "/home/abc/.nzbhydra/libs/peewee.py", line 3454, in execute
    return self.database.last_insert_id(cursor, self.model_class)
    File "/home/abc/.nzbhydra/libs/peewee.py", line 3665, in last_insert_id
    return cursor.lastrowid
    File "/home/abc/.nzbhydra/libs/playhouse/sqliteq.py", line 73, in lastrowid
    self._wait()
    File "/home/abc/.nzbhydra/libs/playhouse/sqliteq.py", line 53, in _wait
    raise self._exc
    IntegrityError: NOT NULL constraint failed: indexernzbdownload.time

**Comment by theotherp** [comment]
Oops, sorry.

**Comment by seanvree** [comment]
I'm on 0.2.200  but i'm still getting these errors:

OS: Windows 10 E
NZBH: 0.2.200 (windows service)

Issue: Getting a lot of Python Errors when I try to download either from Sonarr/Radarr or directly from the UI.

NZBH Logs:

File "C:\nzbhydra\libs\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\nzbhydra\libs\flask\app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\nzbhydra\nzbhydra\web.py", line 379, in wrapped_function
return f(*args, **kwargs)
File "C:\nzbhydra\libs\webargs\core.py", line 368, in wrapper
return func(*new_args, **kwargs)
File "C:\nzbhydra\nzbhydra\web.py", line 675, in getnzb
return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
File "C:\nzbhydra\nzbhydra\web.py", line 875, in extract_nzb_infos_and_return_response
link, _, _ = get_indexer_nzb_link(searchResultId, mode="redirect", log_api_access=True, internal=internal)
File "C:\nzbhydra\nzbhydra\api.py", line 257, in get_indexer_nzb_link
pnzbdl.save()
File "C:\nzbhydra\nzbhydra\database.py", line 146, in save
super(IndexerNzbDownload, self).save(*args, **kwargs)
File "C:\nzbhydra\libs\peewee.py", line 4990, in save
pk_from_cursor = self.insert(**field_dict).execute()
File "C:\nzbhydra\libs\peewee.py", line 3454, in execute
return self.database.last_insert_id(cursor, self.model_class)
File "C:\nzbhydra\libs\peewee.py", line 3665, in last_insert_id
return cursor.lastrowid
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 73, in lastrowid
self._wait()
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 53, in _wait
raise self._exc
IntegrityError: NOT NULL constraint failed: indexernzbdownload.time
2017-02-11 16:51:16,729 - DEBUG - web - Thread-222 - Call to method getnzb
2017-02-11 16:51:16,730 - DEBUG - web - Thread-222 - Access granted by API key
2017-02-11 16:51:16,730 - DEBUG - web - Thread-222 - Get NZB request with args {u'internal': False, u'searchresultid': u'65671ff57f8a9fbef7110dfd72faa433bd1d5fd4', u'downloader': None}
2017-02-11 16:51:16,733 - INFO - web - Thread-222 - API request from 192.168.1.20 to download Iraq.In.Fragments.2006.LiMiTED.DVDRip.XviD-SiNK from Tabula-Rasa
2017-02-11 16:51:16,740 - ERROR - web - Thread-222 - NOT NULL constraint failed: indexernzbdownload.time
Traceback (most recent call last):
File "C:\nzbhydra\libs\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\nzbhydra\libs\flask\app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\nzbhydra\nzbhydra\web.py", line 379, in wrapped_function
return f(*args, **kwargs)
File "C:\nzbhydra\libs\webargs\core.py", line 368, in wrapper
return func(*new_args, **kwargs)
File "C:\nzbhydra\nzbhydra\web.py", line 675, in getnzb
return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
File "C:\nzbhydra\nzbhydra\web.py", line 875, in extract_nzb_infos_and_return_response
link, _, _ = get_indexer_nzb_link(searchResultId, mode="redirect", log_api_access=True, internal=internal)
File "C:\nzbhydra\nzbhydra\api.py", line 257, in get_indexer_nzb_link
pnzbdl.save()
File "C:\nzbhydra\nzbhydra\database.py", line 146, in save
super(IndexerNzbDownload, self).save(*args, **kwargs)
File "C:\nzbhydra\libs\peewee.py", line 4990, in save
pk_from_cursor = self.insert(**field_dict).execute()
File "C:\nzbhydra\libs\peewee.py", line 3454, in execute
return self.database.last_insert_id(cursor, self.model_class)
File "C:\nzbhydra\libs\peewee.py", line 3665, in last_insert_id
return cursor.lastrowid
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 73, in lastrowid
self._wait()
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 53, in _wait
raise self._exc
IntegrityError: NOT NULL constraint failed: indexernzbdownload.time
2017-02-11 16:51:18,737 - DEBUG - web - Thread-223 - Call to method getnzb
2017-02-11 16:51:18,739 - DEBUG - web - Thread-223 - Access granted by API key
2017-02-11 16:51:18,740 - DEBUG - web - Thread-223 - Get NZB request with args {u'internal': False, u'searchresultid': u'853299cbb29bb1d4a71c3b27edfe622e40ee0554', u'downloader': None}
2017-02-11 16:51:18,753 - INFO - web - Thread-223 - API request from 192.168.1.20 to download Iraq.In.Fragments.2006.LiMiTED.DVDRip.HebSubs.XviD-SiNK from Tabula-Rasa
2017-02-11 16:51:18,772 - ERROR - web - Thread-223 - NOT NULL constraint failed: indexernzbdownload.time
Traceback (most recent call last):
File "C:\nzbhydra\libs\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\nzbhydra\libs\flask\app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\nzbhydra\nzbhydra\web.py", line 379, in wrapped_function
return f(*args, **kwargs)
File "C:\nzbhydra\libs\webargs\core.py", line 368, in wrapper
return func(*new_args, **kwargs)
File "C:\nzbhydra\nzbhydra\web.py", line 675, in getnzb
return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
File "C:\nzbhydra\nzbhydra\web.py", line 875, in extract_nzb_infos_and_return_response
link, _, _ = get_indexer_nzb_link(searchResultId, mode="redirect", log_api_access=True, internal=internal)
File "C:\nzbhydra\nzbhydra\api.py", line 257, in get_indexer_nzb_link
pnzbdl.save()
File "C:\nzbhydra\nzbhydra\database.py", line 146, in save
super(IndexerNzbDownload, self).save(*args, **kwargs)
File "C:\nzbhydra\libs\peewee.py", line 4990, in save
pk_from_cursor = self.insert(**field_dict).execute()
File "C:\nzbhydra\libs\peewee.py", line 3454, in execute
return self.database.last_insert_id(cursor, self.model_class)
File "C:\nzbhydra\libs\peewee.py", line 3665, in last_insert_id
return cursor.lastrowid
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 73, in lastrowid
self._wait()
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 53, in _wait
raise self._exc
IntegrityError: NOT NULL constraint failed: indexernzbdownload.time
2017-02-11 16:51:20,726 - DEBUG - web - Thread-224 - Call to method getnzb
2017-02-11 16:51:20,726 - DEBUG - web - Thread-224 - Access granted by API key
2017-02-11 16:51:20,727 - DEBUG - web - Thread-224 - Get NZB request with args {u'internal': False, u'searchresultid': u'e236ad45a81e67c62db4d3741e203a6cef0ff216', u'downloader': None}
2017-02-11 16:51:20,733 - INFO - web - Thread-224 - API request from 192.168.1.20 to download Galaxy.Quest.1999.1080p.Bluray.X264-DIMENSION from omgwtfnzbs
2017-02-11 16:51:20,744 - ERROR - web - Thread-224 - NOT NULL constraint failed: indexernzbdownload.time
Traceback (most recent call last):
File "C:\nzbhydra\libs\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\nzbhydra\libs\flask\app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\nzbhydra\nzbhydra\web.py", line 379, in wrapped_function
return f(*args, **kwargs)
File "C:\nzbhydra\libs\webargs\core.py", line 368, in wrapper
return func(*new_args, **kwargs)
File "C:\nzbhydra\nzbhydra\web.py", line 675, in getnzb
return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
File "C:\nzbhydra\nzbhydra\web.py", line 875, in extract_nzb_infos_and_return_response
link, _, _ = get_indexer_nzb_link(searchResultId, mode="redirect", log_api_access=True, internal=internal)
File "C:\nzbhydra\nzbhydra\api.py", line 257, in get_indexer_nzb_link
pnzbdl.save()
File "C:\nzbhydra\nzbhydra\database.py", line 146, in save
super(IndexerNzbDownload, self).save(*args, **kwargs)
File "C:\nzbhydra\libs\peewee.py", line 4990, in save
pk_from_cursor = self.insert(**field_dict).execute()
File "C:\nzbhydra\libs\peewee.py", line 3454, in execute
return self.database.last_insert_id(cursor, self.model_class)
File "C:\nzbhydra\libs\peewee.py", line 3665, in last_insert_id
return cursor.lastrowid
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 73, in lastrowid
self._wait()
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 53, in _wait
raise self._exc
IntegrityError: NOT NULL constraint failed: indexernzbdownload.time
2017-02-11 16:51:24,638 - DEBUG - web - Thread-225 - Call to method getnzb
2017-02-11 16:51:24,638 - DEBUG - web - Thread-225 - Access granted by API key
2017-02-11 16:51:24,640 - DEBUG - web - Thread-225 - Get NZB request with args {u'internal': False, u'searchresultid': u'206ad91633c8a2da702ebc5ed11fcc6c4f838359', u'downloader': None}
2017-02-11 16:51:24,644 - INFO - web - Thread-225 - API request from 192.168.1.20 to download Galaxy.Quest.1999.1080p.Bluray.X264-DIMENSION from omgwtfnzbs
2017-02-11 16:51:24,653 - ERROR - web - Thread-225 - NOT NULL constraint failed: indexernzbdownload.time
Traceback (most recent call last):
File "C:\nzbhydra\libs\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\nzbhydra\libs\flask\app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\nzbhydra\nzbhydra\web.py", line 379, in wrapped_function
return f(*args, **kwargs)
File "C:\nzbhydra\libs\webargs\core.py", line 368, in wrapper
return func(*new_args, **kwargs)
File "C:\nzbhydra\nzbhydra\web.py", line 675, in getnzb
return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
File "C:\nzbhydra\nzbhydra\web.py", line 875, in extract_nzb_infos_and_return_response
link, _, _ = get_indexer_nzb_link(searchResultId, mode="redirect", log_api_access=True, internal=internal)
File "C:\nzbhydra\nzbhydra\api.py", line 257, in get_indexer_nzb_link
pnzbdl.save()
File "C:\nzbhydra\nzbhydra\database.py", line 146, in save
super(IndexerNzbDownload, self).save(*args, **kwargs)
File "C:\nzbhydra\libs\peewee.py", line 4990, in save
pk_from_cursor = self.insert(**field_dict).execute()
File "C:\nzbhydra\libs\peewee.py", line 3454, in execute
return self.database.last_insert_id(cursor, self.model_class)
File "C:\nzbhydra\libs\peewee.py", line 3665, in last_insert_id
return cursor.lastrowid
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 73, in lastrowid
self._wait()
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 53, in _wait
raise self._exc
IntegrityError: NOT NULL constraint failed: indexernzbdownload.time
2017-02-11 16:51:26,644 - DEBUG - web - Thread-226 - Call to method getnzb
2017-02-11 16:51:26,644 - DEBUG - web - Thread-226 - Access granted by API key
2017-02-11 16:51:26,647 - DEBUG - web - Thread-226 - Get NZB request with args {u'internal': False, u'searchresultid': u'001ae5388149df82a0fcd101c8de84089838b360', u'downloader': None}
2017-02-11 16:51:26,654 - INFO - web - Thread-226 - API request from 192.168.1.20 to download Galaxy.Quest.1999.1080p.Blu-ray.AVC.DTS-HD.MA.5.1-iFPD from Usenet-Crawler
2017-02-11 16:51:26,688 - ERROR - web - Thread-226 - NOT NULL constraint failed: indexernzbdownload.time
Traceback (most recent call last):
File "C:\nzbhydra\libs\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\nzbhydra\libs\flask\app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\nzbhydra\nzbhydra\web.py", line 379, in wrapped_function
return f(*args, **kwargs)
File "C:\nzbhydra\libs\webargs\core.py", line 368, in wrapper
return func(*new_args, **kwargs)
File "C:\nzbhydra\nzbhydra\web.py", line 675, in getnzb
return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
File "C:\nzbhydra\nzbhydra\web.py", line 875, in extract_nzb_infos_and_return_response
link, _, _ = get_indexer_nzb_link(searchResultId, mode="redirect", log_api_access=True, internal=internal)
File "C:\nzbhydra\nzbhydra\api.py", line 257, in get_indexer_nzb_link
pnzbdl.save()
File "C:\nzbhydra\nzbhydra\database.py", line 146, in save
super(IndexerNzbDownload, self).save(*args, **kwargs)
File "C:\nzbhydra\libs\peewee.py", line 4990, in save
pk_from_cursor = self.insert(**field_dict).execute()
File "C:\nzbhydra\libs\peewee.py", line 3454, in execute
return self.database.last_insert_id(cursor, self.model_class)
File "C:\nzbhydra\libs\peewee.py", line 3665, in last_insert_id
return cursor.lastrowid
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 73, in lastrowid
self._wait()
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 53, in _wait
raise self._exc
IntegrityError: NOT NULL constraint failed: indexernzbdownload.time
2017-02-11 16:51:29,157 - DEBUG - web - Thread-227 - Call to method getnzb
2017-02-11 16:51:29,157 - DEBUG - web - Thread-227 - Access granted by API key
2017-02-11 16:51:29,157 - DEBUG - web - Thread-227 - Get NZB request with args {u'internal': False, u'searchresultid': u'8b32ed35ce8b2afa7c0a0d21f25107afbf2212aa', u'downloader': None}
2017-02-11 16:51:29,161 - INFO - web - Thread-227 - API request from 192.168.1.20 to download Galaxy.Quest.1999.BluRay.1080p.TrueHD.5.1.AVC.REMUX-FraMeSToR from Drunken Slug
2017-02-11 16:51:29,173 - ERROR - web - Thread-227 - NOT NULL constraint failed: indexernzbdownload.time
Traceback (most recent call last):
File "C:\nzbhydra\libs\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\nzbhydra\libs\flask\app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\nzbhydra\nzbhydra\web.py", line 379, in wrapped_function
return f(*args, **kwargs)
File "C:\nzbhydra\libs\webargs\core.py", line 368, in wrapper
return func(*new_args, **kwargs)
File "C:\nzbhydra\nzbhydra\web.py", line 675, in getnzb
return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
File "C:\nzbhydra\nzbhydra\web.py", line 875, in extract_nzb_infos_and_return_response
link, _, _ = get_indexer_nzb_link(searchResultId, mode="redirect", log_api_access=True, internal=internal)
File "C:\nzbhydra\nzbhydra\api.py", line 257, in get_indexer_nzb_link
pnzbdl.save()
File "C:\nzbhydra\nzbhydra\database.py", line 146, in save
super(IndexerNzbDownload, self).save(*args, **kwargs)
File "C:\nzbhydra\libs\peewee.py", line 4990, in save
pk_from_cursor = self.insert(**field_dict).execute()
File "C:\nzbhydra\libs\peewee.py", line 3454, in execute
return self.database.last_insert_id(cursor, self.model_class)
File "C:\nzbhydra\libs\peewee.py", line 3665, in last_insert_id
return cursor.lastrowid
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 73, in lastrowid
self._wait()
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 53, in _wait
raise self._exc
IntegrityError: NOT NULL constraint failed: indexernzbdownload.time
2017-02-11 16:51:31,163 - DEBUG - web - Thread-228 - Call to method getnzb
2017-02-11 16:51:31,164 - DEBUG - web - Thread-228 - Access granted by API key
2017-02-11 16:51:31,165 - DEBUG - web - Thread-228 - Get NZB request with args {u'internal': False, u'searchresultid': u'40a7148941ec7d24efa3d49afba33f404a3b71a4', u'downloader': None}
2017-02-11 16:51:31,174 - INFO - web - Thread-228 - API request from 192.168.1.20 to download Galaxy.Quest.1999.BluRay.1080p.TrueHD.5.1.AVC.REMUX-FraMeSToR-Chamele0n from NZBGeek
2017-02-11 16:51:31,194 - ERROR - web - Thread-228 - NOT NULL constraint failed: indexernzbdownload.time
Traceback (most recent call last):
File "C:\nzbhydra\libs\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\nzbhydra\libs\flask\app.py", line 1461, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\nzbhydra\nzbhydra\web.py", line 379, in wrapped_function
return f(*args, **kwargs)
File "C:\nzbhydra\libs\webargs\core.py", line 368, in wrapper
return func(*new_args, **kwargs)
File "C:\nzbhydra\nzbhydra\web.py", line 675, in getnzb
return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
File "C:\nzbhydra\nzbhydra\web.py", line 875, in extract_nzb_infos_and_return_response
link, _, _ = get_indexer_nzb_link(searchResultId, mode="redirect", log_api_access=True, internal=internal)
File "C:\nzbhydra\nzbhydra\api.py", line 257, in get_indexer_nzb_link
pnzbdl.save()
File "C:\nzbhydra\nzbhydra\database.py", line 146, in save
super(IndexerNzbDownload, self).save(*args, **kwargs)
File "C:\nzbhydra\libs\peewee.py", line 4990, in save
pk_from_cursor = self.insert(**field_dict).execute()
File "C:\nzbhydra\libs\peewee.py", line 3454, in execute
return self.database.last_insert_id(cursor, self.model_class)
File "C:\nzbhydra\libs\peewee.py", line 3665, in last_insert_id
return cursor.lastrowid
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 73, in lastrowid
self._wait()
File "C:\nzbhydra\libs\playhouse\sqliteq.py", line 53, in _wait
raise self._exc
IntegrityError: NOT NULL constraint failed: indexernzbdownload.time

Radarr logs:

Component	Message	Time
ReleaseModule	Downloading nzb failed: Downloading nzb failed	4:51pm
Sabnzbd	Downloading nzb for episode 'Galaxy.Quest.1999.BluRay.1080p.TrueHD.5.1.AVC.REMUX-FraMeSToR-Chamele0n' failed (https://192.168.1.20:5075/getnzb?apikey=(removed)&searchresultid=40a7148941ec7d24efa3d49afba33f404a3b71a4): HTTP request failed: [500:InternalServerError] [GET] at [https://192.168.1.20:5075/getnzb?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423&searchresultid=40a7148941ec7d24efa3d49afba33f404a3b71a4]	4:51pm
HttpClient	HTTP Error - Res: [GET] https://192.168.1.20:5075/getnzb?apikey=(removed)&searchresultid=40a7148941ec7d24efa3d49afba33f404a3b71a4: 500.InternalServerError
NOT NULL constraint failed: indexernzbdownload.time	4:51pm
ReleaseModule	Downloading nzb failed: Downloading nzb failed	4:51pm
Sabnzbd	Downloading nzb for episode 'Galaxy.Quest.1999.BluRay.1080p.TrueHD.5.1.AVC.REMUX-FraMeSToR' failed (https://192.168.1.20:5075/getnzb?apikey=(removed)&searchresultid=8b32ed35ce8b2afa7c0a0d21f25107afbf2212aa): HTTP request failed: [500:InternalServerError] [GET] at [https://192.168.1.20:5075/getnzb?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423&searchresultid=8b32ed35ce8b2afa7c0a0d21f25107afbf2212aa]	4:51pm
HttpClient	HTTP Error - Res: [GET] https://192.168.1.20:5075/getnzb?apikey=(removed)&searchresultid=8b32ed35ce8b2afa7c0a0d21f25107afbf2212aa: 500.InternalServerError
NOT NULL constraint failed: indexernzbdownload.time	4:51pm
ReleaseModule	Downloading nzb failed: Downloading nzb failed	4:51pm
Sabnzbd	Downloading nzb for episode 'Galaxy.Quest.1999.1080p.Blu-ray.AVC.DTS-HD.MA.5.1-iFPD' failed (https://192.168.1.20:5075/getnzb?apikey=(removed)&searchresultid=001ae5388149df82a0fcd101c8de84089838b360): HTTP request failed: [500:InternalServerError] [GET] at [https://192.168.1.20:5075/getnzb?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423&searchresultid=001ae5388149df82a0fcd101c8de84089838b360]	4:51pm
HttpClient	HTTP Error - Res: [GET] https://192.168.1.20:5075/getnzb?apikey=(removed)&searchresultid=001ae5388149df82a0fcd101c8de84089838b360: 500.InternalServerError
NOT NULL constraint failed: indexernzbdownload.time

**Comment by theotherp** [comment]
Sorry about that.
