### ISSUE TITLE
nzb links not working after update to 0.2.201

### ISSUE THREAD

**Issue by apiontek** [theotherp/nzbhydra#547]
I am new to nzbhydra and had a fresh install working flawlessly just a day ago. Yesterday did the in-browser update from, I think, 0.2.197 or 198 to 0.2.201 and now nzbget is failing to retrieve nzbs. Searches still work in sonarr and radarr, but no nzb downloads work.

sonarr reports:

> ReleaseModule Downloading nzb failed: Downloading nzb failed  9:33am
> Nzbget  Downloading nzb for episode 'Murdoch.Mysteries.S10E15.720p.WEB-DL.DD5.1.h264-jAh' failed (http://172.22.1.63:5075/nzbhydra/getnzb?apikey=(removed)&searchresultid=97d9635c7206f4ff6794b4bd1474eab662c9a392): HTTP request failed: [500:InternalServerError] [GET] at [http://172.22.1.63:5075/nzbhydra/getnzb?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423&searchresultid=97d9635c7206f4ff6794b4bd1474eab662c9a392]    9:33am
> HttpClient  HTTP Error - Res: [GET] http://172.22.1.63:5075/nzbhydra/getnzb?apikey=(removed)&searchresultid=97d9635c7206f4ff6794b4bd1474eab662c9a392: 500.InternalServerError no such table: indexernzbdownload 9:33am

Indeed, in nzbhydra, under History & Stats > Download History, and > Stats -- I see 

> An error occured :
> 500: 
> no such table: indexernzbdownload

When I try to send direct to nzbget from nzbhydra, nzbget then reports fetch failure, and the URL that nzbhydra sent for nzbget to download the nzb is wrong:

> http://dl.example.com:5075/nzbhydra/getnzb?apikey=(removed)&searchresultid=7c666d446354d4323b6f47c0cdadd1b72f1376a4&downloader=NZBGet

I was browsing nzbhydra at dl.example.com when I did that, but not with the port. Seems to me it shouldn't add the port, right? But it also shouldn't use that domain -- my nzbhydra instance is configured with a different "External URL" under hosting: https://dl.ex.do/nzbhydra -- no port. This points to the same instance. Seems to me it should use this domain, without port (as written), since I configured it there, right?

**Comment by apiontek** [comment]
Rereading my own report this seems like two separate issues.

And the first issue perhaps is related to https://github.com/theotherp/nzbhydra/issues/543 ... except I'm on the version that should fix that issue?

Log:

`2017-02-14 09:43:40,977 - INFO - web - Thread-95 - API request from 172.22.1.63 to download The.Imitation.Game.2014.1080p.BluRay.X264-AMIABLE  from NZBCat
2017-02-14 09:43:40,985 - ERROR - web - Thread-95 - no such table: indexernzbdownload
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 379, in wrapped_function
    return f(*args, **kwargs)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 675, in getnzb
    return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
  File "/opt/nzbhydra/nzbhydra/web.py", line 875, in extract_nzb_infos_and_return_response
    link, _, _ = get_indexer_nzb_link(searchResultId, mode="redirect", log_api_access=True, internal=internal)
  File "/opt/nzbhydra/nzbhydra/api.py", line 257, in get_indexer_nzb_link
    pnzbdl.save()
  File "/opt/nzbhydra/nzbhydra/database.py", line 146, in save
    super(IndexerNzbDownload, self).save(*args, **kwargs)
  File "/opt/nzbhydra/libs/peewee.py", line 4990, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/opt/nzbhydra/libs/peewee.py", line 3454, in execute
    return self.database.last_insert_id(cursor, self.model_class)
  File "/opt/nzbhydra/libs/peewee.py", line 3665, in last_insert_id
    return cursor.lastrowid
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 73, in lastrowid
    self._wait()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 53, in _wait
    raise self._exc
OperationalError: no such table: indexernzbdownload
2017-02-14 09:52:43,868 - ERROR - web - Thread-98 - no such table: indexernzbdownload
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 379, in wrapped_function
    return f(*args, **kwargs)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 1041, in internalapi_getnzb_downloads
    return jsonify(get_nzb_downloads(page=args["page"], limit=args["limit"], filterModel=filterModel, sortModel=args["sortModel"]))
  File "/opt/nzbhydra/nzbhydra/stats.py", line 323, in get_nzb_downloads
    total_downloads = query.count()
  File "/opt/nzbhydra/libs/peewee.py", line 3077, in count
    return self.aggregate(convert=False) or 0
  File "/opt/nzbhydra/libs/peewee.py", line 3070, in aggregate
    return self._aggregate(aggregation).scalar(convert=convert)
  File "/opt/nzbhydra/libs/peewee.py", line 2842, in scalar
    row = self._execute().fetchone()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 53, in _wait
    raise self._exc
OperationalError: no such table: indexernzbdownload
2017-02-14 09:52:59,181 - ERROR - web - Thread-99 - no such table: indexernzbdownload
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 379, in wrapped_function
    return f(*args, **kwargs)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 1041, in internalapi_getnzb_downloads
    return jsonify(get_nzb_downloads(page=args["page"], limit=args["limit"], filterModel=filterModel, sortModel=args["sortModel"]))
  File "/opt/nzbhydra/nzbhydra/stats.py", line 323, in get_nzb_downloads
    total_downloads = query.count()
  File "/opt/nzbhydra/libs/peewee.py", line 3077, in count
    return self.aggregate(convert=False) or 0
  File "/opt/nzbhydra/libs/peewee.py", line 3070, in aggregate
    return self._aggregate(aggregation).scalar(convert=convert)
  File "/opt/nzbhydra/libs/peewee.py", line 2842, in scalar
    row = self._execute().fetchone()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 53, in _wait
    raise self._exc
OperationalError: no such table: indexernzbdownload
2017-02-14 09:53:10,143 - ERROR - web - Thread-104 - no such table: indexernzbdownload
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 379, in wrapped_function
    return f(*args, **kwargs)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 1008, in internalapi_getstats
    return jsonify(getStats(args["after"], args["before"]))
  File "/opt/nzbhydra/nzbhydra/stats.py", line 45, in getStats
    "indexerDownloadShares": getIndexerBasedDownloadStats(afterSql, beforeSql),
  File "/opt/nzbhydra/nzbhydra/stats.py", line 297, in getIndexerBasedDownloadStats
    stats = database.db.execute_sql(query).fetchall()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 89, in fetchall
    return list(self)  # Iterating implies waiting until populated.
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 56, in __iter__
    self._wait()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 53, in _wait
    raise self._exc
OperationalError: no such table: indexernzbdownload
`

**Comment by theotherp** [comment]
The database table error should not happen in any version. If you don't mind losing your search / download history and stats, shutdown Hydra, delete all nzbhydra.db* files and start Hydra. It should work then.

Otherwise you'll need to manually fix the database and that's a bit complicated. I currently don't have enough time to walk you through it. 

If you have a backup from a previous version you could try and restore that.

**Comment by apiontek** [comment]
Thank you. In my case, deleting the db files was OK, and that did fix the problem. The other issue of the wrong URL sent to nzbget, I'll try the "upload nzb" option, and having that work is less important to me anyway so I'll resubmit an issue if it becomes a problem for me.

Thanks again!
