### ISSUE TITLE
Error when sending nzb to NZBget

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#55]
When I click on the small nzb icon to send a nzb file to nzbget, I get this error on the web page: 
An error occured :
500: INTERNAL SERVER ERROR

The log has this:
2015-12-17 00:20:02,882 - ERROR - web - <Fault 2: 'Invalid parameter (AddTop)'>
Traceback (most recent call last):
  File "/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nzbhydra/nzbhydra/web.py", line 178, in decorated
    return f(*args, **kwargs)
  File "/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/nzbhydra/nzbhydra/web.py", line 533, in internalapi_addnzb
    add_success = downloader.add_link(guid, guid["title"], args["category"])
  File "/nzbhydra/nzbhydra/downloader.py", line 97, in add_link
    rcode = rpc.append(title, link, category, 0, False, False, "", 0, "SCORE")
  File "/nzbhydra/libs/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/nzbhydra/libs/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/nzbhydra/libs/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/nzbhydra/libs/xmlrpclib.py", line 1313, in single_request
    return self.parse_response(response)
  File "/nzbhydra/libs/xmlrpclib.py", line 1490, in parse_response
    return u.close()
  File "/nzbhydra/libs/xmlrpclib.py", line 799, in close
    raise Fault(**self._stack[0])
Fault: Fault 2: 'Invalid parameter (AddTop)'

Sending a nzb to NZBget works fine, if I change the NZB adding type to "Upload NZB".  I only get the error when I have the "Send link" option enabled.

**Comment by theotherp** [comment]
Which version of nzbget do you use?

**Comment by judhat2** [comment]
Currently installed: 16.4

**Comment by theotherp** [comment]
Alright, I'll check it out tomorrow.

**Comment by judhat2** [comment]
Works great, thanks!
