### ISSUE TITLE
500: Internal Server Error - TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by YenForYang** [theotherp/nzbhydra#555]
Trying to launch nzbhydra for the first time on my router--I've managed to get it running, but when I load 127.0.0.1:5075 I get errors.

First one I got was:

```
Exception happened during processing of request from ('_ip address I'm connecting with goes here_', 60726)
Traceback (most recent call last):
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/SocketServer.py", line 610, in process_request
    t.start()
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread
```

This error happens each time I try to load the page "127.0.0.1:5075"--almost always. When I get really lucky, the above error doesn't occur after a few attempts, but then I get this error instead: 

```
2017-02-17 18:30:24,584 - ERROR - update - Thread-14 - Command "git" version didn't work
2017-02-17 18:30:24,585 - ERROR - web - Thread-14 - cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/web.py", line 379, in wrapped_function
    return f(*args, **kwargs)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/web.py", line 1230, in internalapi_getversions
    rep_version, rep_version_readable = get_rep_version()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 49, in get_rep_version
    return getUpdateManager().getLatestVersionFromRepository()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 137, in getUpdateManager
    updateManager = GitUpdateManager()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 194, in __init__
    self._git_path = self._find_working_git()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 211, in _find_working_git
    output, err, exit_status = self._run_git(main_git, test_cmd)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 279, in _run_git
    logger.error(cmd + " returned : " + output)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

The second error is more concerning, as I cant get past it with just more connecting attempts. The webpage I'm loading either is all grey (for the first error) or the page is partially/fully loaded, for the second error, with the popup:

> An error occured :
>500: INTERNAL SERVER ERROR
>
>cannot concatenate 'str' and 'NoneType' objects

How can I fix this? Given this "git" version error, I made sure I installed all the git packages on Entware-ng (which is two): 
> git	2.11.0-1	net	Git is a free & open source, distributed version control system designed to handle everything from small to very large projects with speed and efficiency.
> git-http	2.11.0-1	net	Git is a free & open source, distributed......

EDIT: It seems that the error doesn't block the page (which was my mistake) if the page is fully loaded--that is, I can click outside the popup box and use nzbhydra. I'm still wondering about the second (and first) error though..Also I'll mention that when I do click outside the popup box and check the command output, I see:
```
/tmp/mnt/sda1/entware/nzbhydra/libs/webargs/core.py:239: UserWarning: It is highly recommended that you set strict=True on your schema so that the parser's error handler will be invoked when expected.
  "so that the parser's error handler will be invoked when expected.", UserWarning)
```
And I'm not sure what this means as well.

EDIT2:
I enabled debugging once I figure out I could click outside the box (don't think it'll help much though): 
```
2017-02-16 21:25:32,358 - INFO - log - MainThread - None
2017-02-16 21:25:32,359 - INFO - nzbhydra - MainThread - Started
2017-02-16 21:25:32,361 - INFO - nzbhydra - MainThread - Loading database file /tmp/mnt/sda1/entware/nzbhydra/nzbhydra.db
2017-02-16 21:25:32,363 - INFO - database - MainThread - Initializing database and creating tables
2017-02-16 21:25:32,551 - INFO - database - MainThread - Created new version info entry with database version 18
2017-02-16 21:25:32,619 - INFO - nzbhydra - MainThread - Starting db
2017-02-16 21:25:32,625 - INFO - indexers - MainThread - Unable to find indexer with name anizb in database. Will add it
2017-02-16 21:25:32,642 - INFO - indexers - MainThread - Unable to find indexer with name Binsearch in database. Will add it
2017-02-16 21:25:32,655 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-02-16 21:25:32,662 - INFO - indexers - MainThread - Unable to find indexer with name NZBClub in database. Will add it
2017-02-16 21:25:32,675 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-02-16 21:25:32,681 - INFO - indexers - MainThread - Unable to find indexer with name NZBIndex in database. Will add it
2017-02-16 21:25:32,694 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-02-16 21:25:32,697 - NOTICE - nzbhydra - MainThread - Starting web app on 0.0.0.0:5075
2017-02-16 21:25:32,702 - NOTICE - nzbhydra - MainThread - Go to http://127.0.0.1:5075 for the frontend
2017-02-16 21:25:32,708 - INFO - web - MainThread - Running threaded server
2017-02-16 21:26:27,984 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-16 21:26:28,041 - INFO - nzbhydra - Dummy-3 - Database shut down
2017-02-16 22:28:16,873 - INFO - log - MainThread - Logging to file /opt/nzbhydra/nzbhydra.log as defined in the command line
2017-02-16 22:28:16,875 - INFO - nzbhydra - MainThread - Started
2017-02-16 22:28:16,876 - INFO - nzbhydra - MainThread - Daemonizing...
2017-02-16 22:28:16,885 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-16 23:36:37,683 - INFO - log - MainThread - Logging to file /opt/nzbhydra/nzbhydra.log as defined in the command line
2017-02-16 23:36:37,685 - INFO - nzbhydra - MainThread - Started
2017-02-16 23:36:37,686 - INFO - nzbhydra - MainThread - Daemonizing...
2017-02-16 23:36:37,694 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-16 23:42:34,397 - INFO - log - MainThread - Logging to file /opt/nzbhydra/nzbhydra.log as defined in the command line
2017-02-16 23:42:34,399 - INFO - nzbhydra - MainThread - Started
2017-02-16 23:42:34,401 - INFO - nzbhydra - MainThread - Daemonizing...
2017-02-16 23:42:34,453 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-16 23:44:30,296 - INFO - log - MainThread - None
2017-02-16 23:44:30,297 - INFO - nzbhydra - MainThread - Started
2017-02-16 23:44:30,299 - INFO - nzbhydra - MainThread - Loading database file /tmp/mnt/sda1/entware/nzbhydra/nzbhydra.db
2017-02-16 23:44:30,318 - INFO - nzbhydra - MainThread - Starting db
2017-02-16 23:44:30,328 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-02-16 23:44:30,334 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-02-16 23:44:30,339 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-02-16 23:44:30,342 - NOTICE - nzbhydra - MainThread - Starting web app on 0.0.0.0:5075
2017-02-16 23:44:30,347 - NOTICE - nzbhydra - MainThread - Go to http://127.0.0.1:5075 for the frontend
2017-02-16 23:44:30,353 - INFO - web - MainThread - Running threaded server
2017-02-16 23:44:59,347 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-16 23:44:59,350 - INFO - nzbhydra - Dummy-3 - Database shut down
2017-02-16 23:47:42,134 - INFO - log - MainThread - Logging to file /opt/nzbhydra/nzbhydra.log as defined in the command line
2017-02-16 23:47:42,136 - INFO - nzbhydra - MainThread - Started
2017-02-16 23:47:42,138 - INFO - nzbhydra - MainThread - Daemonizing...
2017-02-16 23:47:42,149 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-16 23:49:25,709 - INFO - log - MainThread - Logging to file /opt/nzbhydra/nzbhydra.log as defined in the command line
2017-02-16 23:49:25,711 - INFO - nzbhydra - MainThread - Started
2017-02-16 23:49:25,712 - INFO - nzbhydra - MainThread - Daemonizing...
2017-02-16 23:49:25,721 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-16 23:56:58,146 - INFO - log - MainThread - Logging to file /opt/nzbhydra/nzbhydra.log as defined in the command line
2017-02-16 23:56:58,148 - INFO - nzbhydra - MainThread - Started
2017-02-16 23:56:58,149 - INFO - nzbhydra - MainThread - Daemonizing...
2017-02-16 23:56:58,158 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-17 00:00:01,242 - INFO - log - MainThread - Logging to file /opt/nzbhydra/nzbhydra.log as defined in the command line
2017-02-17 00:00:01,244 - INFO - nzbhydra - MainThread - Started
2017-02-17 00:00:01,245 - INFO - nzbhydra - MainThread - Daemonizing...
2017-02-17 00:00:01,254 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-17 00:02:06,481 - INFO - log - MainThread - None
2017-02-17 00:02:06,483 - INFO - nzbhydra - MainThread - Started
2017-02-17 00:02:06,484 - INFO - nzbhydra - MainThread - Loading database file /tmp/mnt/sda1/entware/nzbhydra/nzbhydra.db
2017-02-17 00:02:06,504 - INFO - nzbhydra - MainThread - Starting db
2017-02-17 00:02:06,514 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-02-17 00:02:06,521 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-02-17 00:02:06,525 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-02-17 00:02:06,529 - NOTICE - nzbhydra - MainThread - Starting web app on 0.0.0.0:5075
2017-02-17 00:02:06,535 - NOTICE - nzbhydra - MainThread - Go to http://127.0.0.1:5075 for the frontend
2017-02-17 00:02:06,541 - INFO - web - MainThread - Running threaded server
2017-02-17 18:19:17,221 - INFO - nzbhydra - MainThread - Restarting process after shutdown: /opt/bin/python /opt/nzbhydra/nzbhydra.py --nobrowser --restarted
2017-02-17 18:19:17,229 - INFO - nzbhydra - Dummy-38 - Exit registered. Shutting down database...
2017-02-17 18:19:17,247 - INFO - nzbhydra - Dummy-38 - Database shut down
2017-02-17 18:19:39,003 - INFO - log - MainThread - None
2017-02-17 18:19:39,004 - INFO - nzbhydra - MainThread - Started
2017-02-17 18:19:39,005 - INFO - nzbhydra - MainThread - Loading database file /tmp/mnt/sda1/entware/nzbhydra/nzbhydra.db
2017-02-17 18:19:39,025 - INFO - nzbhydra - MainThread - Starting db
2017-02-17 18:19:39,035 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-02-17 18:19:39,042 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-02-17 18:19:39,047 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-02-17 18:19:39,051 - NOTICE - nzbhydra - MainThread - Starting web app on 0.0.0.0:5075
2017-02-17 18:19:39,057 - NOTICE - nzbhydra - MainThread - Go to http://127.0.0.1:5075 for the frontend
2017-02-17 18:19:39,062 - INFO - web - MainThread - Running threaded server
2017-02-17 18:24:27,086 - ERROR - update - Thread-14 - Command "git" version didn't work
2017-02-17 18:24:27,088 - ERROR - web - Thread-14 - cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/web.py", line 379, in wrapped_function
    return f(*args, **kwargs)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/web.py", line 1230, in internalapi_getversions
    rep_version, rep_version_readable = get_rep_version()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 49, in get_rep_version
    return getUpdateManager().getLatestVersionFromRepository()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 137, in getUpdateManager
    updateManager = GitUpdateManager()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 194, in __init__
    self._git_path = self._find_working_git()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 211, in _find_working_git
    output, err, exit_status = self._run_git(main_git, test_cmd)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 279, in _run_git
    logger.error(cmd + " returned : " + output)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2017-02-17 18:29:30,430 - INFO - nzbhydra - MainThread - Restarting process after shutdown: /opt/bin/python /opt/nzbhydra/nzbhydra.py --nobrowser --restarted
2017-02-17 18:29:30,438 - INFO - nzbhydra - Dummy-20 - Exit registered. Shutting down database...
2017-02-17 18:29:30,455 - INFO - nzbhydra - Dummy-20 - Database shut down
2017-02-17 18:30:01,056 - INFO - log - MainThread - None
2017-02-17 18:30:01,057 - INFO - nzbhydra - MainThread - Started
2017-02-17 18:30:01,059 - INFO - nzbhydra - MainThread - Loading database file /tmp/mnt/sda1/entware/nzbhydra/nzbhydra.db
2017-02-17 18:30:01,079 - INFO - nzbhydra - MainThread - Starting db
2017-02-17 18:30:01,089 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-02-17 18:30:01,095 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-02-17 18:30:01,100 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-02-17 18:30:01,104 - NOTICE - nzbhydra - MainThread - Starting web app on 0.0.0.0:5075
2017-02-17 18:30:01,111 - NOTICE - nzbhydra - MainThread - Go to http://127.0.0.1:5075 for the frontend
2017-02-17 18:30:01,117 - INFO - web - MainThread - Running threaded server
2017-02-17 18:30:24,584 - ERROR - update - Thread-14 - Command "git" version didn't work
2017-02-17 18:30:24,585 - ERROR - web - Thread-14 - cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/web.py", line 379, in wrapped_function
    return f(*args, **kwargs)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/web.py", line 1230, in internalapi_getversions
    rep_version, rep_version_readable = get_rep_version()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 49, in get_rep_version
    return getUpdateManager().getLatestVersionFromRepository()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 137, in getUpdateManager
    updateManager = GitUpdateManager()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 194, in __init__
    self._git_path = self._find_working_git()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 211, in _find_working_git
    output, err, exit_status = self._run_git(main_git, test_cmd)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 279, in _run_git
    logger.error(cmd + " returned : " + output)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2017-02-17 18:35:58,402 - ERROR - update - Thread-25 - Command "git" version didn't work
2017-02-17 18:35:58,404 - ERROR - web - Thread-25 - cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/mnt/sda1/entware/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/web.py", line 379, in wrapped_function
    return f(*args, **kwargs)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/web.py", line 1230, in internalapi_getversions
    rep_version, rep_version_readable = get_rep_version()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 49, in get_rep_version
    return getUpdateManager().getLatestVersionFromRepository()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 137, in getUpdateManager
    updateManager = GitUpdateManager()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 194, in __init__
    self._git_path = self._find_working_git()
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 211, in _find_working_git
    output, err, exit_status = self._run_git(main_git, test_cmd)
  File "/tmp/mnt/sda1/entware/nzbhydra/nzbhydra/update.py", line 279, in _run_git
    logger.error(cmd + " returned : " + output)
TypeError: cannot concatenate 'str' and 'NoneType' objects
2017-02-17 18:51:24,646 - INFO - indexers - Thread-41 - Activated indexer Binsearch
2017-02-17 18:51:24,653 - INFO - indexers - Thread-41 - Activated indexer NZBClub
2017-02-17 18:51:24,658 - INFO - indexers - Thread-41 - Activated indexer NZBIndex
2017-02-17 18:57:05,617 - INFO - indexers - Thread-43 - Activated indexer Binsearch
2017-02-17 18:57:05,625 - INFO - indexers - Thread-43 - Activated indexer NZBClub
2017-02-17 18:57:05,630 - INFO - indexers - Thread-43 - Activated indexer NZBIndex
```

**Comment by theotherp** [comment]
New version should prevent the git error. But I've never seen `error: can't start new thread`.

**Comment by YenForYang** [comment]
Updated, thanks. It appears to be working now without errors being reported.
