### ISSUE TITLE
local variable 'showIndexerSelection' referenced before assignment

### ISSUE THREAD

**Issue by tonymorella** [theotherp/nzbhydra#558]
Using the docker image from linuxserver.io, just upgraded to latest and received following when I open the main page in logs:

2017-02-18 07:14:47,499 - ERROR - web - Thread-10 - local variable 'showIndexerSelection' referenced before assignment
Traceback (most recent call last):
  File "/config/hydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/config/hydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/config/hydra/nzbhydra/web.py", line 394, in wrapped_function
    return f(*args, **kwargs)
  File "/config/hydra/nzbhydra/web.py", line 446, in base
    bootstrapped = getUserInfos(user)
  File "/config/hydra/nzbhydra/web.py", line 189, in getUserInfos
    cookie["showIndexerSelection"] = showIndexerSelection
UnboundLocalError: local variable 'showIndexerSelection' referenced before assignment

**Comment by theotherp** [comment]
That's what you get for using the develop branch ;-) Should be fixed in next push.

**Comment by tonymorella** [comment]
Cool thanks for the quick update, really just and FYI assume you are on the case :)

**Comment by theotherp** [comment]
You can try the latest version by forcing an update (or pulling using git).
