### ISSUE TITLE
After latest update I can't connect from Sonarr/Radarr: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by seanvree** [theotherp/nzbhydra#560]
Windows10E
NZBH: Current version: 0.2.206 

Seems searchers can't connect via SSL? Started today, not sure which update broke it. 

I CAN get to the webUI via SSL.  

Error from Sonarr and Radarr:
Unable to connect to indexer: The request was aborted: Could not create SSL/TLS secure channel

System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 311
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 295
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 32

**Comment by theotherp** [comment]
I didn't change anything that I'm aware of.

Do you use Hydra's SSL or are you behind a reverse proxy?

If they're on the same machine and you use a reverse proxy I'd recommend just connecting via the local address and HTTP.

**Comment by seanvree** [comment]
@theotherp Nope, no reverse proxy.  Connecting straight to NZBhydra from a local install of Sonarr and Radarr -  all on the same box.

**Comment by theotherp** [comment]
Well I strongly recommend using a reverse proxy instead.

Anyway, I have no idea what could cause that change in behavior. You could ask the sonarr devs why that error is thrown when you can connect to Hydra in the browser.

**Comment by seanvree** [comment]
Yes, I normally do, but I disabled it to check this problem. 

okay, I'll ping them.

**Comment by theotherp** [comment]
Wait, you normally use a reverse proxy? Then how did you encounter this error?

**Comment by seanvree** [comment]
@theotherp Yeah, I turned it off to t-shoot another issue with my box.

**Comment by theotherp** [comment]
By the way, it works on my machine. Perhaps you need a newer / better cert or something.

**Comment by seanvree** [comment]
@theotherp - hummm.....weird. Wouldn't all my other SSL tools stop working then?  Not saying it's not, just wondering.

**Comment by theotherp** [comment]
No idea, I'm no expert and that's why I recommend offloading the encryption part to other tools ;-)

**Comment by seanvree** [comment]
@theotherp  - gotcha. I'll let you know

**Comment by seanvree** [comment]
@theotherp 

Libcurl3 needs to be installed now on Windows.  Not sure why. 

https://github.com/Radarr/Radarr/issues/802#issuecomment-280918628
