### ISSUE TITLE
"./nzbhydra.py --help" gives a Traceback Exception: Error, database not properly initialized before closing connection

### ISSUE THREAD

**Issue by sanderjo** [theotherp/nzbhydra#563]
As title says: "./nzbhydra.py --help" gives a Traceback `Exception: Error, database not properly initialized before closing connection`

Happens on a working nzbhydra, and on a fresh install.

Platform: both Ubuntu 14.04 (with python 2.7.11) and 17.04
```
sander@Streamer13:~/git$ git clone https://github.com/theotherp/nzbhydra.git hydra-blabla
Cloning into 'hydra-blabla'...
remote: Counting objects: 13559, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 13559 (delta 0), reused 0 (delta 0), pack-reused 13555
Receiving objects: 100% (13559/13559), 27.72 MiB | 169.00 KiB/s, done.
Resolving deltas: 100% (8725/8725), done.

sander@Streamer13:~/git$ cd hydra-blabla/

sander@Streamer13:~/git/hydra-blabla$ ./nzbhydra.py --help
usage: nzbhydra.py [-h] [--config CONFIG] [--database DATABASE]
                   [--logfile LOGFILE] [--host HOST] [--port PORT]
                   [--nobrowser] [--daemon] [--quiet] [--pidfile PIDFILE]
                   [--socksproxy SOCKSPROXY]

NZBHydra

optional arguments:
  -h, --help            show this help message and exit
  --config CONFIG       Settings file to load
  --database DATABASE   Database file to load
  --logfile LOGFILE     Log file. If set overwrites config value
  --host HOST, -H HOST  Host to run on
  --port PORT, -p PORT  Port to run on
  --nobrowser           Don't open URL on startup
  --daemon, -D          Run as daemon. *nix only
  --quiet, -q           Quiet (no output)
  --pidfile PIDFILE     PID file. Only relevant with daemon argument
  --socksproxy SOCKSPROXY
                        SOCKS proxy to use in format
                        socks5://user:pass@host:port
2017-02-19 22:23:10,531 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "./nzbhydra.py", line 210, in _stop_worker_threads
    database.db.close()
  File "/home/sander/git/hydra-blabla/libs/peewee.py", line 3610, in close
    raise Exception('Error, database not properly initialized '
Exception: Error, database not properly initialized before closing connection
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "./nzbhydra.py", line 210, in _stop_worker_threads
    database.db.close()
  File "/home/sander/git/hydra-blabla/libs/peewee.py", line 3610, in close
    raise Exception('Error, database not properly initialized '
Exception: Error, database not properly initialized before closing connection
sander@Streamer13:~/git/hydra-blabla$ 
```

**Comment by theotherp** [comment]
Hah.
