### ISSUE TITLE
Error migrating to latest release 207

### ISSUE THREAD

**Issue by siuside** [theotherp/nzbhydra#568]
Trying to restore a backup zip file from 01-24 to the latest release 207 and the server won't come up 

2017-02-24 07:06:27,838 - NOTICE - nzbhydra - MainThread - Starting NZBHydra 0.2.207
2017-02-24 07:06:27,838 - NOTICE - nzbhydra - MainThread - Base path is /opt/nzbhydra
2017-02-24 07:06:27,838 - NOTICE - nzbhydra - MainThread - Loading settings from /opt/nzbhydra/settings.cfg
2017-02-24 07:06:27,848 - INFO - log - MainThread - None
2017-02-24 07:06:27,848 - INFO - nzbhydra - MainThread - Started
2017-02-24 07:06:27,848 - INFO - config - MainThread - Migrating config
2017-02-24 07:06:27,849 - INFO - config - MainThread - Migrating config to version 33
2017-02-24 07:06:27,849 - INFO - config - MainThread - Updating DrunkenSlug host
2017-02-24 07:06:27,849 - INFO - config - MainThread - Migration of config to version 33 finished
2017-02-24 07:06:27,849 - INFO - config - MainThread - Migrating config to version 35
2017-02-24 07:06:27,849 - INFO - config - MainThread - Adding empty download limit to all indexers
2017-02-24 07:06:27,849 - INFO - config - MainThread - Migration of config to version 35 finished
2017-02-24 07:06:27,850 - INFO - config - MainThread - Migrating config to version 37
2017-02-24 07:06:27,850 - INFO - config - MainThread - Adding new field to users
2017-02-24 07:06:27,850 - INFO - config - MainThread - Migration of config to version 37 finished
2017-02-24 07:06:27,850 - INFO - nzbhydra - MainThread - Loading database file /opt/nzbhydra/nzbhydra.db
2017-02-24 07:06:27,852 - INFO - database - MainThread - Migrating database
2017-02-24 07:06:27,852 - INFO - database - MainThread - Upgrading database to version 14. Migrating to hash based search result IDs
2017-02-24 07:06:27,862 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "nzbhydra.py", line 143, in run
    database.update_db(database_file)
  File "/opt/nzbhydra/nzbhydra/database.py", line 586, in update_db
    countSearchResults = SearchResultOld.select().count()
  File "/opt/nzbhydra/libs/peewee.py", line 3077, in count
    return self.aggregate(convert=False) or 0
  File "/opt/nzbhydra/libs/peewee.py", line 3070, in aggregate
    return self._aggregate(aggregation).scalar(convert=convert)
  File "/opt/nzbhydra/libs/peewee.py", line 2842, in scalar
    row = self._execute().fetchone()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 53, in _wait
    raise self._exc
OperationalError: no such table: searchresult
2017-02-24 07:06:27,863 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-24 07:06:27,866 - INFO - nzbhydra - Dummy-3 - Database shut down

**Comment by theotherp** [comment]
Hmm. Will need to check that out. Until then you can just remove nzbhydra.db and start Hydra. It should start up, albeit with an empty database.

**Comment by theotherp** [comment]
Sorry, no idea what's happening. To analyze it I would need your old database file (which contains all your indexer's API keys). If you'd be willing to give me that (I have no interest in your data) send me a mail, otherwise I can only close this.

**Comment by siuside** [comment]
I was able to manually import my settings. Doing a browse through SQLite browser I just see too much sensitive info and it will be a long time if I edit all of the history and other api info. Sorry about that and please feel free to close it.
