### ISSUE TITLE
Unicode error migrating settings

### ISSUE THREAD

**Issue by philborman** [theotherp/nzbhydra#570]
Getting the following error on restarting. settings.cfg seems to start with  block of non ascii data, followed by the expected json config which is incomplete.  Deleting settings.cfg and restarting solves the problem, but I have to re-enter all my settings.

An error occured during migrating the old config. Sorry about that...
Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra.py", line 91, in run
    config.load(settings_file)
  File "/opt/nzbhydra/nzbhydra/config.py", line 787, in load
    raise e
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd9 in position 4096: invalid continuation byte
Trying to log messages from migration...
2017-02-26 10:22:50,695 - WARNING - config - MainThread - An error occurred while migrating the settings: Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra/config.py", line 781, in load
    migratedConfig = loadAndMigrateSettingsFile(filename)
  File "/opt/nzbhydra/nzbhydra/config.py", line 468, in loadAndMigrateSettingsFile
    config = json.load(settingsFile, encoding="utf-8")
  File "/usr/lib/python2.7/json/__init__.py", line 286, in load
    return loads(fp.read(),
  File "/usr/lib/python2.7/codecs.py", line 668, in read
    return self.reader.read(size)
  File "/usr/lib/python2.7/codecs.py", line 474, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd9 in position 4096: invalid continuation byte

**Comment by theotherp** [comment]
And when you delete the crap at the beginning of the file? You could also
copy all the relevant stuff from the original settings file to the new one.

**Comment by philborman** [comment]
Yes, I filled in the missing data from a backup. Not sure what the original problem was, looks like the settings.cfg file starts with 4096 bytes of mostly 0x00, then the settings.cfg json starts, but missing the last 4096 bytes.
