### ISSUE TITLE
Loadlimitonrandom when searching

### ISSUE THREAD

**Issue by Gamer106** [theotherp/nzbhydra#571]
Running on windows (not windows client git), installed as a service using NSSM, python. Setup everything, ran a search, received this error in the log and search page:

An error occured :
500: INTERNAL SERVER ERROR

loadLimitOnRandom

2017-02-27 13:45:05,676 - INFO - nzbhydra - MainThread - Started
2017-02-27 13:45:05,676 - INFO - nzbhydra - MainThread - Loading database file c:\NZBHydra\nzbhydra.db
2017-02-27 13:45:05,691 - INFO - nzbhydra - MainThread - Starting db
2017-02-27 13:45:05,694 - INFO - indexers - MainThread - Activated indexer anizb
2017-02-27 13:45:05,696 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-02-27 13:45:05,697 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-02-27 13:45:05,697 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-02-27 13:45:05,698 - INFO - indexers - MainThread - Activated indexer Usenet-Crawler
2017-02-27 13:45:05,700 - INFO - indexers - MainThread - Activated indexer nzbplanet
2017-02-27 13:45:05,704 - NOTICE - nzbhydra - MainThread - Starting web app on 127.0.0.1:5075
2017-02-27 13:45:05,704 - NOTICE - nzbhydra - MainThread - Go to http://127.0.0.1:5075 for the frontend
2017-02-27 13:45:05,736 - INFO - web - MainThread - Running threaded server
2017-02-27 13:49:15,936 - INFO - search - Thread-35 - Starting new search: SearchRequest [ type "general", query "Dark Night: a true batman story", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100", indexers "anizb|Binsearch|NZBClub|NZBIndex|nzbplanet|Usenet-Crawler" ]
2017-02-27 13:49:15,943 - ERROR - web - Thread-35 - loadLimitOnRandom
Traceback (most recent call last):
  File "c:\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\NZBHydra\nzbhydra\web.py", line 407, in wrapped_function
    return f(*args, **kwargs)
  File "c:\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "c:\NZBHydra\nzbhydra\web.py", line 794, in internalapi_search
    searchResult = startSearch(search_request)
  File "c:\NZBHydra\nzbhydra\web.py", line 756, in startSearch
    results = search.search(search_request)
  File "c:\NZBHydra\nzbhydra\search.py", line 290, in search
    indexers_to_call = pick_indexers(search_request)
  File "c:\NZBHydra\nzbhydra\search.py", line 214, in pick_indexers
    if p.settings.loadLimitOnRandom and not search_request.internal and not random.randint(1, p.settings.loadLimitOnRandom) == 1:
  File "c:\NZBHydra\libs\bunch\__init__.py", line 121, in __getattr__
    raise AttributeError(k)
AttributeError: loadLimitOnRandom
2017-02-27 13:49:34,367 - INFO - search - Thread-36 - Starting new search: SearchRequest [ type "general", query "Batman", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100", indexers "anizb|Binsearch|NZBClub|NZBIndex|nzbplanet|Usenet-Crawler" ]
2017-02-27 13:49:34,371 - ERROR - web - Thread-36 - loadLimitOnRandom
Traceback (most recent call last):
  File "c:\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\NZBHydra\nzbhydra\web.py", line 407, in wrapped_function
    return f(*args, **kwargs)
  File "c:\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "c:\NZBHydra\nzbhydra\web.py", line 794, in internalapi_search
    searchResult = startSearch(search_request)
  File "c:\NZBHydra\nzbhydra\web.py", line 756, in startSearch
    results = search.search(search_request)
  File "c:\NZBHydra\nzbhydra\search.py", line 290, in search
    indexers_to_call = pick_indexers(search_request)
  File "c:\NZBHydra\nzbhydra\search.py", line 214, in pick_indexers
    if p.settings.loadLimitOnRandom and not search_request.internal and not random.randint(1, p.settings.loadLimitOnRandom) == 1:
  File "c:\NZBHydra\libs\bunch\__init__.py", line 121, in __getattr__
    raise AttributeError(k)
AttributeError: loadLimitOnRandom

**Comment by theotherp** [comment]
Please post your debug infos.

**Comment by theotherp** [comment]
For a quick fix add the line 
`"loadLimitOnRandom": null, `
to each of your indexers in settings.cfg

It should've added the setting automatically. Don't know why the migration sometimes fails for some users.

**Comment by theotherp** [comment]
Oh I see.

**Comment by theotherp** [comment]
Sorry about that, I should really make a todo list to prevent that from happening...

**Comment by Gamer106** [comment]
Resolved, thanks!

**Comment by samtrois** [comment]
I didn't have the "LoadLimitOnRandom" line for one of my indexers, and didn't permissions to save the line in my appdata folder, so I had to change the load limit in Hydra settings to 2, which worked, but as far as I understand this would use the indexer for only half of the searches. 
Anyway, I then deleted the '2' from the settings, and now the config file has "... : null" as intended and it seems to be working
