### ISSUE TITLE
SSL startup failure

### ISSUE THREAD

**Issue by dlardo** [theotherp/nzbhydra#572]
Upon starting the Windows binary release, I'm getting an error when "ssl": true in the settings.cfg. (Changing ssl: false does work). Looking at the code, it appears that the SSL library is returning None instead of an expected string. This exception isn't handled which causes the program to fatally exit.

2017-02-28 08:30:07,539 - ERROR - <string> - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "<string>", line 201, in run
  File "nzbhydra\web.py", line 1534, in run
  File "nzbhydra\web.py", line 1561, in create_context
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by theotherp** [comment]
Hm, thanks. Entirely possible that it doesn't work on windows but if that's the case of course it should be handled better. I'll do some tests.

**Comment by theotherp** [comment]
Works for me - no idea why, sorry.

**Comment by dlardo** [comment]
Just tried on a fresh machine, I was able to repro.

- git clone windows-release
- Set your settings.cfg to these values
```
        "ssl": true, 
        "sslcert": null, 
        "sslkey": null, 
```
- restart.
- crash occurs

```
2017-03-03 10:58:16,296 - INFO - log - MainThread - None
2017-03-03 10:58:16,296 - INFO - <string> - MainThread - Started
2017-03-03 10:58:16,298 - INFO - <string> - MainThread - Loading database file D:\development\github.com\theotherp\nzbhydra-windows-releases\nzbhydra.db
2017-03-03 10:58:16,306 - INFO - <string> - MainThread - Starting db
2017-03-03 10:58:16,309 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-03-03 10:58:16,311 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-03-03 10:58:16,312 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-03-03 10:58:16,313 - NOTICE - <string> - MainThread - Starting web app on 127.0.0.1:5075
2017-03-03 10:58:16,315 - INFO - <string> - MainThread - Opening browser to https://127.0.0.1:5075
2017-03-03 10:58:17,213 - ERROR - <string> - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "<string>", line 201, in run
  File "nzbhydra\web.py", line 1534, in run
  File "nzbhydra\web.py", line 1561, in create_context
IOError: [Errno 2] No such file or directory
2017-03-03 10:58:17,213 - INFO - <string> - Dummy-3 - Exit registered. Stopping and closing database
2017-03-03 10:58:17,216 - INFO - <string> - Dummy-3 - Database shut down
```

Putting a .crt and .key into the config causes the crash to stop, but I can't load the page at https://127.0.0.1:5075. Not sure if it's cert related or not.

changing to:
```
        "ssl": true,
        "sslcert": "certs/127.0.0.1.crt",
        "sslkey": "certs/127.0.0.1.key",
```

Log:
```
2017-03-03 11:04:14,526 - INFO - <string> - MainThread - Started
2017-03-03 11:04:14,526 - INFO - <string> - MainThread - Loading database file D:\development\github.com\theotherp\nzbhydra-windows-releases\nzbhydra.db
2017-03-03 11:04:14,536 - INFO - <string> - MainThread - Starting db
2017-03-03 11:04:14,539 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-03-03 11:04:14,542 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-03-03 11:04:14,543 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-03-03 11:04:14,546 - NOTICE - <string> - MainThread - Starting web app on 127.0.0.1:5075
2017-03-03 11:04:14,546 - INFO - <string> - MainThread - Opening browser to https://127.0.0.1:5075
```

What I'm doing to gen the cert and key:
```
#!/bin/bash

if [ $# -lt 1 ]; then
    echo "usage: $0 domain-name"
    exit 1
fi

# Domain being www.thegeekstuff.com for example. Can be an IP, localhost, etc.
DOMAIN=$1

# Stolen from: http://www.thegeekstuff.com/2009/07/linux-apache-mod-ssl-generate-key-csr-crt-file

echo "Generating a private key"
openssl genrsa -des3 -out $DOMAIN.key 1024

echo "Generating a Certificate Signing Request (CSR)"
openssl req -new -key $DOMAIN.key -out $DOMAIN.csr

echo "Generate a self-signed SSL certificate that is valid for 10 years. Lab or home use only."
openssl x509 -req -days 3650 -in $DOMAIN.csr -signkey $DOMAIN.key -out $DOMAIN.crt

echo "Key: $DOMAIN.key"
echo "CSR: $DOMAIN.csr"
echo "Self-signed Cert: $DOMAIN.crt"
```

This is all in a script I called gensshfiles.sh
`bash ./gensshfiles.sh 127.0.0.1`

**Comment by theotherp** [comment]
Yeah, not saying it might not be reproducable, just that it's working on my machine and I don't know why. Probably because something's installed. I don't have the time and resources to analyze this.

**Comment by dlardo** [comment]
Maybe just a check for the json values that cause the crash and a helpful error message?

**Comment by theotherp** [comment]
Sure, that I can do.
