### ISSUE TITLE
Error loadLimitOnRandom from fresh install of 0.2.0.210

### ISSUE THREAD

**Issue by fryfrog** [theotherp/nzbhydra#575]
If I disable NZBIndex, it is fine. Looks like a recent commit mentions this, so probably a known issue.

  Traceback (most recent call last):
    File "/usr/lib/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
      rv = self.dispatch_request()
    File "/usr/lib/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
      return self.view_functions[rule.endpoint](**req.view_args)
    File "/usr/lib/nzbhydra/nzbhydra/web.py", line 407, in wrapped_function
      return f(*args, **kwargs)
    File "/usr/lib/nzbhydra/libs/webargs/core.py", line 368, in wrapper
      return func(*new_args, **kwargs)
    File "/usr/lib/nzbhydra/nzbhydra/web.py", line 794, in internalapi_search
      searchResult = startSearch(search_request)
    File "/usr/lib/nzbhydra/nzbhydra/web.py", line 756, in startSearch
      results = search.search(search_request)
    File "/usr/lib/nzbhydra/nzbhydra/search.py", line 290, in search
      indexers_to_call = pick_indexers(search_request)
    File "/usr/lib/nzbhydra/nzbhydra/search.py", line 214, in pick_indexers
      if p.settings.loadLimitOnRandom and not search_request.internal and not random.randint(1, p.settings.loadLimitOnRandom) == 1:
    File "/usr/lib/nzbhydra/libs/bunch/__init__.py", line 121, in __getattr__
      raise AttributeError(k)
  AttributeError: loadLimitOnRandom

**Comment by theotherp** [comment]
Should be fixed in latest version. For fixing see https://github.com/theotherp/nzbhydra/issues/571#issuecomment-282855510
