### ISSUE TITLE
Unable to connect to indexer - Sonarr time out 

### ISSUE THREAD

**Issue by soupy14** [theotherp/nzbhydra#576]
Hey everyone

* What do you expect to happen? What does happen? - Searching tv shows 
* Can the problem be reproduced? How? - Have Sonnar search for an ep when testing indexer says it failed. When testing indexer says this - Unable to connect to indexer, check the log for more details

RUnning latest version of Sonarr & Hydra w10 64bit

Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 576, in api
  File "nzbhydra\web.py", line 650, in api_search
  File "nzbhydra\search.py", line 273, in search
  File "<decorator-gen-18>", line 2, in countOldSearchResults
  File "site-packages\retry\api.py", line 74, in retry_decorator
  File "site-packages\retry\api.py", line 33, in __retry_internal
  File "nzbhydra\search.py", line 504, in countOldSearchResults
  File "site-packages\peewee.py", line 3077, in count
  File "site-packages\peewee.py", line 3070, in aggregate
  File "site-packages\peewee.py", line 2842, in scalar
  File "site-packages\playhouse\sqliteq.py", line 92, in fetchone
  File "site-packages\playhouse\sqliteq.py", line 51, in _wait
ResultTimeout: results not ready, timed out.
2017-03-02 00:01:20,017 - INFO - web - Thread-56 - API search request: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2017-03-02 00:01:20,019 - INFO - search - Thread-56 - Starting new search: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2017-03-02 00:01:40,022 - ERROR - web - Thread-56 - results not ready, timed out.
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 576, in api
  File "nzbhydra\web.py", line 650, in api_search
  File "nzbhydra\search.py", line 273, in search
  File "<decorator-gen-18>", line 2, in countOldSearchResults
  File "site-packages\retry\api.py", line 74, in retry_decorator
  File "site-packages\retry\api.py", line 33, in __retry_internal
  File "nzbhydra\search.py", line 504, in countOldSearchResults
  File "site-packages\peewee.py", line 3077, in count
  File "site-packages\peewee.py", line 3070, in aggregate
  File "site-packages\peewee.py", line 2842, in scalar
  File "site-packages\playhouse\sqliteq.py", line 92, in fetchone
  File "site-packages\playhouse\sqliteq.py", line 51, in _wait
ResultTimeout: results not ready, timed out.
2017-03-02 00:01:56,967 - INFO - web - Thread-57 - API search request: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2017-03-02 00:01:56,969 - INFO - search - Thread-57 - Starting new search: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2017-03-02 00:02:17,005 - ERROR - web - Thread-57 - results not ready, timed out.
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 576, in api
  File "nzbhydra\web.py", line 650, in api_search
  File "nzbhydra\search.py", line 273, in search
  File "<decorator-gen-18>", line 2, in countOldSearchResults
  File "site-packages\retry\api.py", line 74, in retry_decorator
  File "site-packages\retry\api.py", line 33, in __retry_internal
  File "nzbhydra\search.py", line 504, in countOldSearchResults
  File "site-packages\peewee.py", line 3077, in count
  File "site-packages\peewee.py", line 3070, in aggregate
  File "site-packages\peewee.py", line 2842, in scalar
  File "site-packages\playhouse\sqliteq.py", line 92, in fetchone
  File "site-packages\playhouse\sqliteq.py", line 51, in _wait
ResultTimeout: results not ready, timed out.
2017-03-02 00:02:38,130 - INFO - web - Thread-60 - API search request: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2017-03-02 00:02:38,131 - INFO - search - Thread-60 - Starting new search: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2017-03-02 00:02:40,232 - INFO - search - Thread-60 - Deleting 7439 search results from database that are older than 7 days
2017-03-02 00:03:00,233 - ERROR - web - Thread-60 - results not ready, timed out.
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 576, in api
  File "nzbhydra\web.py", line 650, in api_search
  File "nzbhydra\search.py", line 276, in search
  File "site-packages\peewee.py", line 3472, in execute
  File "site-packages\peewee.py", line 3668, in rows_affected
  File "site-packages\playhouse\sqliteq.py", line 78, in rowcount
  File "site-packages\playhouse\sqliteq.py", line 51, in _wait
ResultTimeout: results not ready, timed out.

**Comment by theotherp** [comment]
Does it work with regular queries via the GUI? That error is a bad one but I thought I had solved it a long time ago.

**Comment by soupy14** [comment]
Seems fine, oddly it will go some days fine other days I get those errors.

**Comment by adchevrier** [comment]
Same problem here:
Happens with sonarr, radarr, when searching with the gui, and when viewing stats (popup with message 
An error occured :
500: INTERNAL SERVER ERROR

results not ready, timed out.)

api:

2017-03-17 11:47:42,154 - INFO - web - Thread-422 - API search request: SearchRequest [ type "movie", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2017-03-17 11:47:42,169 - INFO - search - Thread-422 - Starting new search: SearchRequest [ type "movie", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2017-03-17 11:48:15,959 - ERROR - web - Thread-422 - results not ready, timed out.
Traceback (most recent call last):
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 576, in api
    searchResult = api_search(args)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 650, in api_search
    result = search.search(search_request)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/search.py", line 273, in search
    oldSearchResultsCount = countOldSearchResults(keepFor)
  File "<decorator-gen-18>", line 2, in countOldSearchResults
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/retry/api.py", line 74, in retry_decorator
    logger)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/retry/api.py", line 33, in __retry_internal
    return f()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/search.py", line 504, in countOldSearchResults
    return SearchResult.select().where(SearchResult.firstFound < (datetime.date.today() - datetime.timedelta(days=keepFor))).count()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 3077, in count
    return self.aggregate(convert=False) or 0
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 3070, in aggregate
    return self._aggregate(aggregation).scalar(convert=convert)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 2842, in scalar
    row = self._execute().fetchone()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/playhouse/sqliteq.py", line 51, in _wait
    raise ResultTimeout('results not ready, timed out.')
ResultTimeout: results not ready, timed out.

search : 

2017-03-17 11:53:36,329 - INFO - search - Thread-432 - Starting new search: SearchRequest [ type "general", query "xxxx", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100", indexers "altHub|DogNZB|Nzbcat|pfmonkey|Usenet Crawler" ]
2017-03-17 11:53:56,473 - ERROR - web - Thread-432 - results not ready, timed out.
Traceback (most recent call last):
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 407, in wrapped_function
    return f(*args, **kwargs)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 794, in internalapi_search
    searchResult = startSearch(search_request)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 756, in startSearch
    results = search.search(search_request)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/search.py", line 273, in search
    oldSearchResultsCount = countOldSearchResults(keepFor)
  File "<decorator-gen-18>", line 2, in countOldSearchResults
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/retry/api.py", line 74, in retry_decorator
    logger)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/retry/api.py", line 33, in __retry_internal
    return f()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/search.py", line 504, in countOldSearchResults
    return SearchResult.select().where(SearchResult.firstFound < (datetime.date.today() - datetime.timedelta(days=keepFor))).count()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 3077, in count
    return self.aggregate(convert=False) or 0
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 3070, in aggregate
    return self._aggregate(aggregation).scalar(convert=convert)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 2842, in scalar
    row = self._execute().fetchone()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/playhouse/sqliteq.py", line 51, in _wait
    raise ResultTimeout('results not ready, timed out.')
ResultTimeout: results not ready, timed out.

stats:

2017-03-17 11:57:26,603 - ERROR - web - Thread-441 - results not ready, timed out.
Traceback (most recent call last):
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 407, in wrapped_function
    return f(*args, **kwargs)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 1075, in internalapi_getstats
    return jsonify(getStats(args["after"], args["before"]))
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/stats.py", line 42, in getStats
    "avgResponseTimes": get_avg_indexer_response_times(after, before),
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/stats.py", line 64, in get_avg_indexer_response_times
    avg_response_time = IndexerApiAccess().select(fn.AVG(IndexerApiAccess.response_time)).where(where).tuples()[0][0]
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 3169, in __getitem__
    res.fill_cache(index)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 2285, in fill_cache
    next(self)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 2271, in next
    obj = self.iterate()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 2248, in iterate
    row = self.cursor.fetchone()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/playhouse/sqliteq.py", line 51, in _wait
    raise ResultTimeout('results not ready, timed out.')
ResultTimeout: results not ready, timed out.

**Comment by ewascome** [comment]
Same as @adchevrier

**Comment by bassrock** [comment]
Seeing the same issue.

**Comment by extremeshok** [comment]
+1 same issue, manual searching does work.

**Comment by theotherp** [comment]
There's nothing I can currently do to fix this. I'm working on some kind of solution but that will still take some time.

**Comment by theotherp** [comment]
Check the newest version. I don't think it'll help but who knows.

**Comment by docwho76** [comment]
I too, have this issue, even with newest versions of both radarr and hydra, What gives?

**Comment by theotherp** [comment]
The only explanation why internal and API search may differ is that sonarr might execute multiple searches at once while you usually only do one search at a time using the GUI.

**Comment by theotherp** [comment]
Please change the branch in the config to "develop". Do an update. See if it works now.

**Comment by docwho76** [comment]
YESSSS, develop branch and latest works

**Comment by theotherp** [comment]
Awesome. I'll do some more tests to verify that I don't break something else here.

**Comment by theotherp** [comment]
Unfortunately this decreases database write performance massively...

**Comment by theotherp** [comment]
Latest commit should fix most performance problems.
