### ISSUE TITLE
'list' object has no attribute 'didsearch'

### ISSUE THREAD

**Issue by extremeshok** [theotherp/nzbhydra#585]
2017-03-21 23:13:58,052 - ERROR - web - Thread-21 - 'list' object has no attribute 'didsearch'
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 576, in api
    searchResult = api_search(args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 650, in api_search
    result = search.search(search_request)
  File "/opt/nzbhydra/nzbhydra/search.py", line 358, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "/opt/nzbhydra/nzbhydra/search.py", line 528, in search_and_handle_db
    if result.didsearch:
AttributeError: 'list' object has no attribute 'didsearch'

**Comment by extremeshok** [comment]
Sanarr returns error 500
nzbhydra HTTP request failed: [500:InternalServerError] [GET] at [http://127.0.0.1:5075/api?t=tvsearch&cat=5000&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=254292&rid=28120&season=7&ep=7]

**Comment by theotherp** [comment]
Does this happen every time? Can you search from the GUI?

Post the debug infos.

**Comment by extremeshok** [comment]
GUI (nzbhydra) search works
Sonarr searches generally fail

--- Those are the debug infos, or is there something else you require ?

**Comment by theotherp** [comment]
Jesus christ, when you created this issue you deleted a long list of stuff that I ask users to provide.

Enable debug log level, restart, do a search from sonarr and post the full log not, just an excerpt.
