### ISSUE TITLE
althub.co.za "Access error: Error while parsing the results from indexer"

### ISSUE THREAD

**Issue by 0naicuL** [theotherp/nzbhydra#591]
Hi,

I'm getting an error when trying to search althub through NZBHydra:

"Access error: Error while parsing the results from indexer"

Any suggestions?

Here's my setup:
http://i.imgur.com/KvXD0eN.png

Other people seem to use althub with NZBhydra just fine. (https://github.com/theotherp/nzbhydra/issues/433), (https://github.com/theotherp/nzbhydra/issues/588)

**Comment by theotherp** [comment]
Send debugging info.

**Comment by 0naicuL** [comment]
`2017-03-30 17:47:13,255 - ERROR - search_module - Thread-12 - althub: Error while processing search results from indexer althub
Traceback (most recent call last):
  File "/usr/pbi/nzbhydra-amd64/share/nzbhydra/nzbhydra/nzbhydra/search_module.py", line 400, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/usr/pbi/nzbhydra-amd64/share/nzbhydra/nzbhydra/nzbhydra/searchmodules/jackett.py", line 84, in process_query_result
    entries, total, offset = self.parseXml(xml_response, maxResults)
  File "/usr/pbi/nzbhydra-amd64/share/nzbhydra/nzbhydra/nzbhydra/searchmodules/jackett.py", line 109, in parseXml
    entry = self.parseItem(item)
  File "/usr/pbi/nzbhydra-amd64/share/nzbhydra/nzbhydra/nzbhydra/searchmodules/jackett.py", line 131, in parseItem
    entry.category = getByNewznabCats(categories)
  File "/usr/pbi/nzbhydra-amd64/share/nzbhydra/nzbhydra/nzbhydra/categories.py", line 57, in getByNewznabCats
    cats = getListFromNewznabCats(cats)
  File "/usr/pbi/nzbhydra-amd64/share/nzbhydra/nzbhydra/nzbhydra/categories.py", line 52, in getListFromNewznabCats
    cats = [int(x) for x in cats]
ValueError: invalid literal for int() with base 10: 'TV > HD'
2017-03-30 17:47:13,256 - ERROR - search_module - Thread-12 - althub: Access error: Error while parsing the results from indexer`

**Comment by theotherp** [comment]
You added althub as a jackett (which is for torrents). Delete it and add it as newznab indexer. Try if that works.

**Comment by 0naicuL** [comment]
Interesting. It seems to work now. I didn't intentionally add it as Jackett. I added it as another newznab indexer, but I seem to remember having an actual option for that. Now I only see this:

http://i.imgur.com/H9lMeYC.png

**Comment by theotherp** [comment]
Just click the button (where it says "Add new indexer"...).
