### ISSUE TITLE
Can't communicate with Sabnzbd

### ISSUE THREAD

**Issue by sogeniusio** [theotherp/nzbhydra#592]
When trying to add a downloader Sabnzbd to be exact, I receive several errors:

- Sab is not responding
- Wrong credentials

I confirmed that my api_key is correct and have removed my authentication.
After checking hydra's logs, I see:

2017/04/04 16:20:42 [error] 14309#14309: *126 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 70.214.73.230, server: media.sogenius.org, request: "GET /search/ HTTP/2.0", upstream: "http://127.0.0.1:5075/search/", host: "media.sogenius.org"`
`hosnelg@media:~$ sudo tail -f /var/log/media-services/nzbhydra/*.log
2017-04-04 18:00:02,973 - INFO - nzbhydra - MainThread - Loading database file /opt/nzbhydra/nzbhydra.db
2017-04-04 18:00:02,987 - INFO - nzbhydra - MainThread - Starting db
2017-04-04 18:00:02,989 - INFO - indexers - MainThread - Activated indexer anizb
2017-04-04 18:00:02,991 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-04-04 18:00:02,995 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-04-04 18:00:02,997 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-04-04 18:00:02,999 - NOTICE - nzbhydra - MainThread - Starting web app on 0.0.0.0:5075
2017-04-04 18:00:03,000 - NOTICE - nzbhydra - MainThread - Go to https://media.sogenius.org/search for the frontend
2017-04-04 18:00:03,002 - INFO - web - MainThread - Running threaded server
2017-04-04 18:00:03,002 - INFO - web - MainThread - Running Hydra with SSL
2017-04-04 18:00:58,703 - INFO - web - Thread-27 - Form login form user hosnelg successful
2017-04-04 18:00:58,782 - WARNING - update - Thread-28 - Configured git path git doesn't exist. Will try to call globally
2017-04-04 18:00:58,802 - INFO - update - Thread-28 - git output: git version 2.7.4
2017-04-04 18:02:43,570 - INFO - downloader - Thread-56 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:03:00,883 - ERROR - downloader - Thread-61 - Error while trying to connect to sabnzbd: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-04-04 18:03:11,079 - INFO - downloader - Thread-64 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:03:19,632 - INFO - downloader - Thread-67 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:03:30,336 - ERROR - downloader - Thread-70 - Error while trying to connect to sabnzbd: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-04-04 18:03:42,132 - INFO - downloader - Thread-74 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:03:58,482 - ERROR - downloader - Thread-78 - Error while trying to connect to sabnzbd: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-04-04 18:04:07,758 - INFO - downloader - Thread-81 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:04:14,671 - ERROR - downloader - Thread-83 - Error while trying to connect to sabnzbd: 400 Client Error: Bad Request for url: http://localhost:9090/api?apikey=<APIKEY>&output=json&mode=qstatus
2017-04-04 18:04:33,040 - INFO - downloader - Thread-88 - Access to sabnzbd failed, probably due to wrong credentials

Not sure what could be causing these unwanted errors. Please advise.

**Comment by theotherp** [comment]
Open http://localhost:9090/api?apikey=YOURAPIKEY&output=json&mode=qstatus in a private window of your browser. Does it work?

**Comment by sogeniusio** [comment]
I can't use localhost, as Sab runs on a Ubuntu server. But I'll attempt to call it by IP. I'll let you know my findings...

**Comment by sogeniusio** [comment]
I get an output over http but not https.

**Comment by theotherp** [comment]
So it works with http and the IP but not with HTTPS and localhost? Why don't you just enter the IP as sabnzbd host?

**Comment by sogeniusio** [comment]
I tried all combinations of with/without username/password, http/https, http,https port... Do you think this could be attributed to a setting in nginx?

2017-04-04 18:00:02,968 - INFO - log - MainThread - None
2017-04-04 18:00:02,968 - INFO - nzbhydra - MainThread - Started
2017-04-04 18:00:02,968 - INFO - nzbhydra - MainThread - Daemonizing...
2017-04-04 18:00:02,973 - INFO - nzbhydra - MainThread - Loading database file /opt/nzbhydra/nzbhydra.db
2017-04-04 18:00:02,987 - INFO - nzbhydra - MainThread - Starting db
2017-04-04 18:00:02,989 - INFO - indexers - MainThread - Activated indexer anizb
2017-04-04 18:00:02,991 - INFO - indexers - MainThread - Activated indexer Binsearch
2017-04-04 18:00:02,995 - INFO - indexers - MainThread - Activated indexer NZBClub
2017-04-04 18:00:02,997 - INFO - indexers - MainThread - Activated indexer NZBIndex
2017-04-04 18:00:02,999 - NOTICE - nzbhydra - MainThread - Starting web app on 0.0.0.0:5075
2017-04-04 18:00:03,000 - NOTICE - nzbhydra - MainThread - Go to https://media.sogenius.org/search for the frontend
2017-04-04 18:00:03,002 - INFO - web - MainThread - Running threaded server
2017-04-04 18:00:03,002 - INFO - web - MainThread - Running Hydra with SSL
2017-04-04 18:00:58,703 - INFO - web - Thread-27 - Form login form user hosnelg successful
2017-04-04 18:00:58,782 - WARNING - update - Thread-28 - Configured git path git doesn't exist. Will try to call globally
2017-04-04 18:00:58,802 - INFO - update - Thread-28 - git output: git version 2.7.4
2017-04-04 18:02:43,570 - INFO - downloader - Thread-56 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:03:00,883 - ERROR - downloader - Thread-61 - Error while trying to connect to sabnzbd: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-04-04 18:03:11,079 - INFO - downloader - Thread-64 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:03:19,632 - INFO - downloader - Thread-67 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:03:30,336 - ERROR - downloader - Thread-70 - Error while trying to connect to sabnzbd: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-04-04 18:03:42,132 - INFO - downloader - Thread-74 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:03:58,482 - ERROR - downloader - Thread-78 - Error while trying to connect to sabnzbd: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-04-04 18:04:07,758 - INFO - downloader - Thread-81 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:04:14,671 - ERROR - downloader - Thread-83 - Error while trying to connect to sabnzbd: 400 Client Error: Bad Request for url: http://localhost:9090/api?apikey=<APIKEY>&output=json&mode=qstatus
2017-04-04 18:04:33,040 - INFO - downloader - Thread-88 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-04 18:12:03,962 - WARNING - web - Thread-147 - Unsuccessful form login for user Hosnelg from IP 70.214.73.230
2017-04-04 18:12:14,882 - INFO - web - Thread-148 - Form login form user hosnelg successful
2017-04-05 07:18:08,278 - INFO - downloader - Thread-908 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-05 07:18:21,342 - INFO - downloader - Thread-910 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-05 07:18:29,909 - ERROR - web - Thread-911 - No host specified.
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 407, in wrapped_function
    return f(*args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 1014, in internalapi_testdownloader
    success, message = downloader.test(settings)
  File "/opt/nzbhydra/nzbhydra/downloader.py", line 211, in test
    r = webaccess.get(f.tostr(), timeout=15)
  File "/opt/nzbhydra/nzbhydra/webaccess.py", line 35, in get
    return requests.get(url, proxies=myproxies, verify=False, **kwargs)
  File "/opt/nzbhydra/libs/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/nzbhydra/libs/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/nzbhydra/libs/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/nzbhydra/libs/requests/sessions.py", line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/opt/nzbhydra/libs/requests/sessions.py", line 190, in resolve_redirects
    **adapter_kwargs
  File "/opt/nzbhydra/libs/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/opt/nzbhydra/libs/requests/adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "/opt/nzbhydra/libs/requests/adapters.py", line 296, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/opt/nzbhydra/libs/requests/packages/urllib3/poolmanager.py", line 222, in connection_from_url
    return self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/opt/nzbhydra/libs/requests/packages/urllib3/poolmanager.py", line 167, in connection_from_host
    raise LocationValueError("No host specified.")
LocationValueError: No host specified.
2017-04-05 07:19:03,811 - INFO - downloader - Thread-912 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-05 07:19:10,904 - ERROR - downloader - Thread-913 - Error while trying to connect to sabnzbd: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
2017-04-05 07:19:18,284 - INFO - downloader - Thread-914 - Access to sabnzbd failed, probably due to wrong credentials
2017-04-05 07:20:03,756 - INFO - downloader - Thread-915 - Access to sabnzbd failed, probably due to wrong credentials

**Comment by theotherp** [comment]
What did you enter as host, "http://localhost:9090/<sabnzbd/>"or "http://YOURDOMAIN:9090/<sabnzbd/>"?

**Comment by theotherp** [comment]
To make this short, find the URL with which you can reach sabnzbd from the machine on which hydra is running. Enter that.

**Comment by theotherp** [comment]
Do you use the newest release candidate of sabnzbd?

**Comment by alexplattfuss** [comment]
I get the same thing. Downloads appear to send to SABnzbd fine, but no status is ever recorded (all my history says 'unknown') and I have to click "I know what I'm doing" when adding/modifying the downloader.

Log: 2017-04-10 12:08:38,583 - INFO - downloader - Thread-187 - Access to sabnzbd failed, probably due to wrong credentials
NZBHydra: 0.2.213
SABnzbd: 2.0.0RC2 [afd1b19]

**Comment by theotherp** [comment]
Have you updated? The last version should've fixed that.

**Comment by alexplattfuss** [comment]
I'm now on
NZBHydra: 0.2.213
SABnzbd: 2.0.0 [55c4bef]
Still no luck, same message.

**Comment by theotherp** [comment]
That's weird, tested it and it worked on my machine. Will do some more tests tonight or tomorrow.

**Comment by theotherp** [comment]
@sogeniusio In the future when you use an RC or beta version or something like that of a software please say so.
