### ISSUE TITLE
Issues with NZB.su and NZB Finder

### ISSUE THREAD

**Issue by spylex** [theotherp/nzbhydra#606]
I'm having some issues with 2 indexers, out of the 8 i have added in total

6 out of 8 work, so it isn't an issue with setup (all VIP accounts, confirmed)
I have added the capabilities based on the wiki for each of the failing indexers
I've searched for the errors but no luck
I have reinstalled Hydra a few times but still the same

Please see the error log attached.

I am not sure why this is happening, the error is below:

2017-05-26 23:52:19,977 - ERROR - search_module - Thread-5273 - nzb.su: Error while processing search results from indexer nzb.su
Traceback (most recent call last):
  File "/opt/hydra/nzbhydra/search_module.py", line 425, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/opt/hydra/nzbhydra/searchmodules/newznab.py", line 502, in process_query_result
    entries, total, offset = self.parseXml(xml_response, maxResults)
  File "/opt/hydra/nzbhydra/searchmodules/newznab.py", line 527, in parseXml
    entry = self.parseItem(item)
  File "/opt/hydra/nzbhydra/searchmodules/newznab.py", line 614, in parseItem
    if self.settings.backend.lower() in ["nzedb", "nntmux"] and entry.has_nfo == NzbSearchResult.HAS_NFO_MAYBE:
AttributeError: 'NoneType' object has no attribute 'lower'
2017-05-26 23:52:19,978 - ERROR - search_module - Thread-5273 - nzb.su: Access error: Error while parsing the results from indexer
2017-05-26 23:52:20,037 - INFO - search_module - Thread-5273 - nzb.su: Disabling indexer temporarily due to access problems. Will be reenabled in a day

[nzbhydra-debuginfo-2017-05-26-23-50.zip](https://github.com/theotherp/nzbhydra/files/1033104/nzbhydra-debuginfo-2017-05-26-23-50.zip)

**Comment by icetail** [comment]
Having that same error

2017-05-27 02:21:37,580 - ERROR - search_module - Thread-3953 - nzb.su: Error while processing search results from indexer nzb.su
Traceback (most recent call last):
  File "/opt/hydra/nzbhydra/search_module.py", line 425, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/opt/hydra/nzbhydra/searchmodules/newznab.py", line 502, in process_query_result
    entries, total, offset = self.parseXml(xml_response, maxResults)
  File "/opt/hydra/nzbhydra/searchmodules/newznab.py", line 527, in parseXml
    entry = self.parseItem(item)
  File "/opt/hydra/nzbhydra/searchmodules/newznab.py", line 614, in parseItem
    if self.settings.backend.lower() in ["nzedb", "nntmux"] and entry.has_nfo == NzbSearchResult.HAS_NFO_MAYBE:
AttributeError: 'NoneType' object has no attribute 'lower'
2017-05-27 02:21:37,596 - ERROR - search_module - Thread-3953 - nzb.su: Access error: Error while parsing the results from indexer
2017-05-27 02:21:37,598 - INFO - search_module - Thread-3953 - nzb.su: Disabling indexer temporarily due to access problems. Will be reenabled in 14 minutes

**Comment by theotherp** [comment]
Try clicking "Check capabilities" in the indexer config again. This error can only occurs if the initial check was not executed completely.

**Comment by icetail** [comment]
I keep getting this error.
Restart -> error
Add again -> error
Re-test -> error

**Comment by spylex** [comment]
Exactly the same issue here. It won't detect capabilities of either of
those indexers.

**Comment by theotherp** [comment]
Post a complete log with debug level

**Comment by spylex** [comment]
Does this work?
[nzbhydra-debuginfo-2017-05-27-18-17.zip](https://github.com/theotherp/nzbhydra/files/1033678/nzbhydra-debuginfo-2017-05-27-18-17.zip)

**Comment by theotherp** [comment]
It seems that NZBFinder (I don't have an account for nzb.su) doesn't like too many requests being executed at once. 

For now you can shut down Hydra, open the settings.cfg, find the affected indexers and change the "backend" setting to "nZEDb":
`"backend": "nZEDb", `

Start Hydra and it should work. I'll try to figure something out.

**Comment by spylex** [comment]
This is what the support request i sent to nzb.su said as well, that
possibly the indexer 'was hit too fast' or something.

I will try that, thank you. I have sent you a PM regarding nzb.su :)

**Comment by spylex** [comment]
Here is another log after i did the change on both. It seems to have fixed nzb.su but NZB Finder still lags behind (even though it now seems to get the fastest responses).

[nzbhydra-debuginfo-2017-05-28-08-38.zip](https://github.com/theotherp/nzbhydra/files/1034009/nzbhydra-debuginfo-2017-05-28-08-38.zip)

**Comment by theotherp** [comment]
Thanks, but this will need some code modification to get it to work properly. Not sure when I will have the time and motivation...

**Comment by spylex** [comment]
Damn, what's the issue? Not sure I can help somehow? Motivation...
Cheerleaders? :)

**Comment by theotherp** [comment]
You know how to fix it for you, what's the rush...

**Comment by weirdcrap** [comment]
@theotherp I saw this issue and wanted to pop in and say I can provide you with an nzb.su invite if you want to make an account and do some extra testing.

**Comment by theotherp** [comment]
In the meantime I found out that I actually have an account... I'm kinda
losing overview over all of my indexers. But thank you and everyone who
messaged me on reddit, willing to provide me with an invite!
