### ISSUE TITLE
Error binding parameter 0 - probably unsupported type (Traceback)

### ISSUE THREAD

**Issue by mitchelp** [theotherp/nzbhydra#621]
nzbhydra seems to crash once in a while, is this caused by a known issue, config failure or something?

The only thing I currently can find in the logging is this:

```
2017-06-22 08:05:16,366 - ERROR - web - Thread-3792 - Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name" FROM "indexer" AS t1 WHERE ("t1"."id" = ?)
PARAMS: [17]
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 982, in getnzb
    logger.info("%s request from %s to download %s from %s" % ("Internal" if args["internal"] else "API", getIp(), searchResult.title, searchResult.indexer.name))
  File "/opt/nzbhydra/libs/peewee.py", line 1311, in __get__
    return self.get_object_or_id(instance)
  File "/opt/nzbhydra/libs/peewee.py", line 1302, in get_object_or_id
    obj = self.rel_model.get(self.field.to_field == rel_id)
  File "/opt/nzbhydra/libs/peewee.py", line 4795, in get
    return sq.get()
  File "/opt/nzbhydra/libs/peewee.py", line 3101, in get
    % self.sql())
IndexerDoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name" FROM "indexer" AS t1 WHERE ("t1"."id" = ?)
PARAMS: [17]
```

```
2017-06-22 08:05:16,506 - INFO - web - Thread-3785 - API search request completed in 2146 ms
2017-06-22 08:05:18,320 - ERROR - web - Thread-3793 - Error binding parameter 0 - probably unsupported type.
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 982, in getnzb
    logger.info("%s request from %s to download %s from %s" % ("Internal" if args["internal"] else "API", getIp(), searchResult.title, searchResult.indexer.name))
  File "/opt/nzbhydra/libs/peewee.py", line 1311, in __get__
    return self.get_object_or_id(instance)
  File "/opt/nzbhydra/libs/peewee.py", line 1302, in get_object_or_id
    obj = self.rel_model.get(self.field.to_field == rel_id)
  File "/opt/nzbhydra/libs/peewee.py", line 4795, in get
    return sq.get()
  File "/opt/nzbhydra/libs/peewee.py", line 3097, in get
    return next(clone.execute())
  File "/opt/nzbhydra/libs/peewee.py", line 2271, in next
    obj = self.iterate()
  File "/opt/nzbhydra/libs/peewee.py", line 2248, in iterate
    row = self.cursor.fetchone()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 53, in _wait
    raise self._exc
InterfaceError: Error binding parameter 0 - probably unsupported type.
```

I have switched it to debug mode, I will drop the info here as soon as it happens again.

**Comment by theotherp** [comment]
The database is corrupt for some reason. An indexer is missing in the database. If you don't need your history / stats it's easiest to shutdown, delete the database file(s) and restart.

**Comment by mitchelp** [comment]
Oke, removed the .db* files and will keep an eye on the logging.
(restarted also)

Thanks for the help @theotherp
