### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE in FreeNAS Jail

### ISSUE THREAD

**Issue by claym** [theotherp/nzbhydra#630]
Running latest versions on a FreeBSD / FreeNAS jail.

Tends to happen if I search through the web ui, with a type of content selected (i'm guessing it's calling out to IMDB or something?)

I've updated openssl, pyOpenSSL, requests[security] and about everything else I can think of.
```

2017-07-09 21:23:55,366 - DEBUG - web - Thread-20 - Autocomplete request with args {u'input': u'twin peaks ', u'type': u'tv'}
2017-07-09 21:23:55,725 - ERROR - web - Thread-20 - [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)
Traceback (most recent call last):
  File "/usr/local/share/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/share/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/share/nzbhydra/nzbhydra/web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "/usr/local/share/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/usr/local/share/nzbhydra/libs/flask_cache/__init__.py", line 537, in decorated_function
    rv = f(*args, **kwargs)
  File "/usr/local/share/nzbhydra/nzbhydra/web.py", line 1679, in internalapi_autocomplete
    results = infos.find_series_ids(args["input"])
  File "/usr/local/share/nzbhydra/nzbhydra/infos.py", line 116, in find_series_ids
    info = webaccess.get("https://api.tvmaze.com/search/shows?q=%s" % input)
  File "/usr/local/share/nzbhydra/nzbhydra/webaccess.py", line 38, in get
    return requests.get(url, proxies=myproxies, verify=config.settings.main.verifySsl, **kwargs)
  File "/usr/local/share/nzbhydra/libs/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/share/nzbhydra/libs/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/share/nzbhydra/libs/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/share/nzbhydra/libs/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/share/nzbhydra/libs/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)
```

**Comment by theotherp** [comment]
You can disable SSL verification in the config as a quickf ix.

I'm currently encountering the same issue with anizb but haven't had time to take a closer look at it.

You can try running `pip install certifi` (with sudo) or `pip2.7 install certifi` if you've also installed python 3.

**Comment by theotherp** [comment]
Perhaps @cjthornton can chime in, he contributed the SSL verification always-on change.

**Comment by claym** [comment]
I've tried disabling ssl verification, and installed certifi, and it still does it.

**Comment by theotherp** [comment]
That is unexpected. No idea what's happening...

**Comment by theotherp** [comment]
I'm at a loss here. Everything that's supposed to fix this doesn't...

**Comment by sanderjo** [comment]
Hi @claym  api.tvmaze.com uses Let's Encrypt Authority X3. According to https://www.sslshopper.com/ssl-checker.html#hostname=api.tvmaze.com their SSL setup is correct.

So my guess is that the problem is on your site, and more specific that your FreeBSD / FreeNAS jail hasn't got the root certificate for Let's Encrypt Authority X3.

A brute force check on my Linux for X3 is:
```
$ locate -i x3 | grep -i -e certs -e ca-certificates
/etc/ssl/certs/DST_Root_CA_X3.pem
/usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt
```

BRB with a python check.

**Comment by theotherp** [comment]
I'm having the same problem with Anizb.

**Comment by sanderjo** [comment]
One-liner Python check of a SSL/TLS connection:

``
python -c "import urllib2; response = urllib2.urlopen('https://api.tvmaze.com/') "
````
If you run that on your FreeBSD / FreeNAS, what do you get?



For a bad SSL/TLS connection (client side or server side), with python 2.7.9+, you will get:
```
$ python -c "import urllib2; response = urllib2.urlopen('https://self-signed.badssl.com/') "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/python2711/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python2711/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/opt/python2711/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/opt/python2711/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/opt/python2711/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/opt/python2711/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

**Comment by sanderjo** [comment]
> I'm having the same problem with Anizb.

1. Which URL exactly?
2. What does https://www.sslshopper.com/ssl-checker.html say about that URL?
3. What does the python one-liner say about the your SSL/TLS connection to that URL?

**Comment by claym** [comment]
I get that error as well

```
root@blackbeard:/ # python2.7 -c "import urllib2; response = urllib2.urlopen('https://api.tvmaze.com/') "
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:661)>

```

**Comment by sanderjo** [comment]
@claym As explained in https://github.com/theotherp/nzbhydra/issues/630#issuecomment-316977025, that means your root certificate store is missing the root certificate for Let's Encrypt Authority X3. 

You have to solve that. Maybe http://www.freshports.org/security/ca_root_nss helps?

**Comment by claym** [comment]
I didn't install or do anything additional - ca_root_nss was already installed

Here's my results:

root@blackbeard:/mnt/media/comics # ll /usr/local/share/certs/ca-root-nss.crt
-rw-r--r--  1 root  wheel  897851 Dec 25  2016 /usr/local/share/certs/ca-root-nss.crt

root@blackbeard:/mnt/media/comics # cat /usr/local/share/certs/ca-root-nss.crt | grep "^ .*X3"
        Issuer: O=Digital Signature Trust Co., CN=DST Root CA X3
        Subject: O=Digital Signature Trust Co., CN=DST Root CA X3

**Comment by sanderjo** [comment]
Ah, I see. And the output of `cat /etc/ssl/cert.pem | grep "^ .*X3"`


```
$ cat /etc/ssl/cert.pem | grep "^ .*X3"
        Issuer: O=Digital Signature Trust Co., CN=DST Root CA X3
        Subject: O=Digital Signature Trust Co., CN=DST Root CA X3
```

**Comment by claym** [comment]
```
root@blackbeard:/mnt/media/comics # cat /etc/ssl/cert.pem | grep "^ .*X3"
        Issuer: O=Digital Signature Trust Co., CN=DST Root CA X3
        Subject: O=Digital Signature Trust Co., CN=DST Root CA X3

```
