### ISSUE TITLE
Pickle.UnpicklingError: Suddenly can't access nzbhydra on OS X 

### ISSUE THREAD

**Issue by strafer** [theotherp/nzbhydra#636]
I have nzbhydra running on OS X 10.6.8 Server. It's been working perfectly until I tried to connect to the web gui this morning. Unable to connect to the server. I rebooted nzbhydra using the launchctl unload/load command. The log file shows nothing wrong but the process doesn't appear in Activity Monitor. I then enabled debug mode via editing the settings.cfg file and tried to connect to the web gui. The browser gave the following message:

> Pickle.UnpicklingError

> UnpicklingError: unpickling stack underflow
Traceback (most recent call last)

> The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

> Traceback (most recent call last):
  File "/Users/ladmin/nzbhydra/libs/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ladmin/nzbhydra/nzbhydra/web.py", line 90, in __call__
    return self.app(environ, start_response)
  File "/Users/ladmin/nzbhydra/libs/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/ladmin/nzbhydra/libs/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ladmin/nzbhydra/libs/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ladmin/nzbhydra/libs/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/Users/ladmin/nzbhydra/libs/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/Users/ladmin/nzbhydra/libs/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/Users/ladmin/nzbhydra/libs/flask_session/sessions.py", line 337, in save_session
    total_seconds(app.permanent_session_lifetime))
  File "/Users/ladmin/nzbhydra/libs/werkzeug/contrib/cache.py", line 694, in set
    self._prune()
  File "/Users/ladmin/nzbhydra/libs/werkzeug/contrib/cache.py", line 650, in _prune
    expires = pickle.load(f)
UnpicklingError: unpickling stack underflow

Any idea how to fix this? Or do I have to do a full reinstall of nzbhydra?

**Comment by theotherp** [comment]
Delete the flask_session folder

**Comment by strafer** [comment]
That worked. Thank you.
