### ISSUE TITLE
Database is Locked on 0.2.222

### ISSUE THREAD

**Issue by stoofz** [theotherp/nzbhydra#638]
Database is locked error on 0.2.222 upgrade and fresh install. 

No start up scripts / no double instances running. 

Log is from Fresh install

Traceback (most recent call last):
  File "C:\NZBHydraNew\nzbhydra\search.py", line 536, in search_and_handle_db
    result.indexerApiAccessEntry.save()
  File "C:\NZBHydraNew\nzbhydra\database.py", line 132, in save
    super(IndexerApiAccess, self).save(*args, **kwargs)
  File "C:\NZBHydraNew\libs\peewee.py", line 5114, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "C:\NZBHydraNew\libs\peewee.py", line 3543, in execute
    return self.database.last_insert_id(cursor, self.model_class)
  File "C:\NZBHydraNew\libs\peewee.py", line 3756, in last_insert_id
    return cursor.lastrowid
  File "C:\NZBHydraNew\libs\playhouse\sqliteq.py", line 87, in lastrowid
    self._wait()
  File "C:\NZBHydraNew\libs\playhouse\sqliteq.py", line 62, in _wait
    raise self._exc
OperationalError: database is locked
2017-07-20 09:52:25,690 - ERROR - web - Thread-31 - database is locked
Traceback (most recent call last):
  File "C:\NZBHydraNew\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\NZBHydraNew\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\NZBHydraNew\nzbhydra\web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "C:\NZBHydraNew\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "C:\NZBHydraNew\nzbhydra\web.py", line 871, in internalapi_search
    searchResult = startSearch(search_request)
  File "C:\NZBHydraNew\nzbhydra\web.py", line 831, in startSearch
    results = search.search(search_request)
  File "C:\NZBHydraNew\nzbhydra\search.py", line 359, in search
    result = search_and_handle_db(dbsearch, {x: search_request for x in indexers_to_call})
  File "C:\NZBHydraNew\nzbhydra\search.py", line 532, in search_and_handle_db
    indexersearchentry.save()
  File "C:\NZBHydraNew\nzbhydra\database.py", line 91, in save
    super(IndexerSearch, self).save(*args, **kwargs)
  File "C:\NZBHydraNew\libs\peewee.py", line 5114, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "C:\NZBHydraNew\libs\peewee.py", line 3543, in execute
    return self.database.last_insert_id(cursor, self.model_class)
  File "C:\NZBHydraNew\libs\peewee.py", line 3756, in last_insert_id
    return cursor.lastrowid
  File "C:\NZBHydraNew\libs\playhouse\sqliteq.py", line 87, in lastrowid
    self._wait()
  File "C:\NZBHydraNew\libs\playhouse\sqliteq.py", line 62, in _wait
    raise self._exc
OperationalError: database is locked

** Can't restore prior configuration file either. **

Error while restoring files: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\NZBHydraNew\\nzbhydra.db'. Original state was restored.

2017-07-20 09:54:55,709 - INFO - backup_debug - Thread-88 - Attempting to restore data from backup ZIP
2017-07-20 09:54:55,709 - INFO - backup_debug - Thread-88 - Creating new temp folder C:\NZBHydraNew\temp
2017-07-20 09:54:55,710 - INFO - backup_debug - Thread-88 - Found backup info in archive: {"configFile": "settings.cfg", "version": "0.2.220", "databaseFile": "nzbhydra.db"}
2017-07-20 09:54:55,710 - INFO - backup_debug - Thread-88 - Extracting backup data to temp folder C:\NZBHydraNew\temp
2017-07-20 09:54:55,910 - INFO - backup_debug - Thread-88 - Shutting down database
2017-07-20 09:54:55,911 - INFO - backup_debug - Thread-88 - Starting to restore database file to C:\NZBHydraNew\nzbhydra.db
2017-07-20 09:54:55,911 - INFO - backup_debug - Thread-88 - Renaming database file C:\NZBHydraNew\nzbhydra.db to temporary backup file C:\NZBHydraNew\nzbhydra.db.tempBackup
2017-07-20 09:54:55,917 - ERROR - backup_debug - Thread-88 - Error while restoring files
Traceback (most recent call last):
  File "C:\NZBHydraNew\nzbhydra\backup_debug.py", line 124, in restoreFromBackupData
    shutil.move(nzbhydra.databaseFile, databaseFileTempBackup)
  File "C:\NZBHydraNew\libs\shutil.py", line 303, in move
    os.unlink(src)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\NZBHydraNew\\nzbhydra.db'
2017-07-20 09:54:55,917 - INFO - backup_debug - Thread-88 - Restoring original state
2017-07-20 09:54:55,917 - ERROR - backup_debug - Thread-88 - Unable to bring back config file to state before restore
2017-07-20 09:54:55,918 - INFO - backup_debug - Thread-88 - Deleting temporary backup of database file C:\NZBHydraNew\nzbhydra.db.tempBackup
2017-07-20 09:54:55,920 - INFO - backup_debug - Thread-88 - Deleting temp folder C:\NZBHydraNew\temp

I ended up reverting to 0.2.220 and everything is okay again

**Comment by theotherp** [comment]
Ah fuck.

**Comment by theotherp** [comment]
Please try the new (old) code.

**Comment by stoofz** [comment]
0.2.221 working!

**Comment by theotherp** [comment]
Great. Somebody else will soon come and complain that it's not working for him but what can I do.
