### ISSUE TITLE
errors on startup

### ISSUE THREAD

**Issue by natelandau** [theotherp/nzbhydra#646]
I've been having problems with Hydra for about a day now.  Searching in the UI works fine but none of my tools (sonarr, radarr, etc.) are able to use hydra.  I have changed nothing in my settings and everything had been working great for months up until today.  I looked at the log and saw the following.  I don't know if this is related or not.

```
2017-07-29 20:22:50,307 - INFO - nzbhydra - MainThread - Started
2017-07-29 20:22:50,307 - INFO - nzbhydra - MainThread - Loading database file /config/hydra/nzbhydra.db
2017-07-29 20:22:50,313 - INFO - nzbhydra - MainThread - Starting db
2017-07-29 20:22:50,325 - INFO - indexers - MainThread - Activated indexer DogNZB
2017-07-29 20:22:50,328 - INFO - indexers - MainThread - Activated indexer NZBGeek
2017-07-29 20:22:50,332 - INFO - indexers - MainThread - Activated indexer Drunken Slug
2017-07-29 20:22:50,335 - INFO - indexers - MainThread - Activated indexer Tabula-Rasa
2017-07-29 20:22:50,337 - INFO - indexers - MainThread - Activated indexer abNZB
2017-07-29 20:22:50,340 - INFO - indexers - MainThread - Activated indexer nzbNoob
2017-07-29 20:22:50,344 - NOTICE - nzbhydra - MainThread - Starting web app on 127.0.0.1:5075
2017-07-29 20:22:50,344 - NOTICE - nzbhydra - MainThread - Go to http://127.0.0.1:5075 for the frontend
2017-07-29 20:22:50,346 - INFO - web - MainThread - Running threaded server
2017-07-29 20:22:50,350 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "/opt/hydra/nzbhydra.py", line 201, in run
    web.run(host, port, basepath)
  File "/opt/hydra/nzbhydra/web.py", line 1730, in run
    app.run(host=host, port=port, debug=config.settings.main.debug, threaded=config.settings.main.runThreaded, use_reloader=config.settings.main.flaskReloader)
  File "/opt/hydra/libs/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/opt/hydra/libs/werkzeug/serving.py", line 625, in run_simple
    inner()
  File "/opt/hydra/libs/werkzeug/serving.py", line 603, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/opt/hydra/libs/werkzeug/serving.py", line 506, in make_server
    passthrough_errors, ssl_context)
  File "/opt/hydra/libs/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/opt/hydra/libs/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/opt/hydra/libs/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/opt/hydra/libs/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/opt/hydra/libs/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
```

In addition, the sonarr logs (for example) show the following error

`Invalid request Validation failed: `

**Comment by theotherp** [comment]
There's another instance of hydra running. Or the port 5075 is used by
another program.
