### ISSUE TITLE
Error while processing search results from indexer PourCeSoir

### ISSUE THREAD

**Issue by anonvoy** [theotherp/nzbhydra#660]
Don't know if this indexer produces malformed result pages or if something is wrong with NZBHydra. The log shows this:

```
2017-09-07 10:34:35,410 - INFO - search_module - Thread-29963 - PourCeSoir: Starting search
2017-09-07 10:34:35,411 - DEBUG - search_module - Thread-29963 - PourCeSoir: Requesting https://pourcesoir.in/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&q=XXXXX with timeout 100
2017-09-07 10:34:35,411 - DEBUG - search - Thread-29961 - Added 1 of 1 calls to executor
2017-09-07 10:34:35,831 - DEBUG - search_module - Thread-29963 - PourCeSoir: HTTP request to indexer completed in 419ms
2017-09-07 10:34:35,836 - DEBUG - search_module - Thread-29963 - PourCeSoir: Successfully loaded URL https://pourcesoir.in/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&q=XXXXX
2017-09-07 10:34:35,836 - DEBUG - search_module - Thread-29963 - PourCeSoir: Started processing results
2017-09-07 10:34:35,866 - ERROR - search_module - Thread-29963 - PourCeSoir: Error while processing search results from indexer PourCeSoir
Traceback (most recent call last):
  File "/home/abc/.nzbhydra/nzbhydra/search_module.py", line 439, in execute_queries
    parsed_results = self.process_query_result(request.text, searchRequest)
  File "/home/abc/.nzbhydra/nzbhydra/searchmodules/newznab.py", line 510, in process_query_result
    entries, total, offset = self.parseXml(xml_response, maxResults)
  File "/home/abc/.nzbhydra/nzbhydra/searchmodules/newznab.py", line 535, in parseXml
    entry = self.parseItem(item)
  File "/home/abc/.nzbhydra/nzbhydra/searchmodules/newznab.py", line 594, in parseItem
    elif attribute_name == "info" and self.settings.backend.lower() in ["nzedb", "nntmux"]:
AttributeError: 'NoneType' object has no attribute 'lower'
2017-09-07 10:34:35,867 - ERROR - search_module - Thread-29963 - PourCeSoir: Access error: Error while parsing the results from indexer
2017-09-07 10:34:35,869 - INFO - search_module - Thread-29963 - PourCeSoir: Disabling indexer temporarily due to access problems. Will be reenabled in an hour
```

Perhaps it's useful to improve something.

**Comment by theotherp** [comment]
The caps check was probably unsuccessful.

Shutdown Hydra, open the settings.cfg, find the entry for that indexer, find the line that says `"backend:" none` or something like that. Replace the "none" with "newznab". Start Hydra again and it should work.

**Comment by anonvoy** [comment]
Indeed, that worked, everything is fine now. Thanks for the quick help, you definitely know your hydra :-)
