### ISSUE TITLE
500: INTERNAL SERVER ERROR / results not ready, timed out.

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra#661]
Since the last update I get this error too many times when checking 'History & Stats'. Sometimes it works, but most of the time it does not.

![2017-09-08 07_57_52-nzb hydra - search](https://user-images.githubusercontent.com/671621/30198011-b916df3a-946b-11e7-887e-84e1b96cd7fe.jpg)

```
2017-09-08 07:57:27,704 - ERROR - web - Thread-6322 - results not ready, timed out.
Traceback (most recent call last):
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/web.py", line 1272, in internalapi_search_requests
    return jsonify(get_search_requests(page=args["page"], limit=args["limit"], sortModel=args["sortModel"], filterModel=filterModel, distinct=args["distinct"], onlyUser=False))
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/nzbhydra/stats.py", line 394, in get_search_requests
    total_requests = query.count()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 3077, in count
    return self.aggregate(convert=False) or 0
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 3070, in aggregate
    return self._aggregate(aggregation).scalar(convert=convert)
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/peewee.py", line 2842, in scalar
    row = self._execute().fetchone()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/volume1/@appstore/nzbhydra/share/nzbhydra/libs/playhouse/sqliteq.py", line 51, in _wait
    raise ResultTimeout('results not ready, timed out.')
ResultTimeout: results not ready, timed out.
```

Can I somehow fix this? Increase the timeout maybe?

**Comment by theotherp** [comment]
Unfortunately there's currently no fix for this. Some people are affected, most are not.

I plan to release a new major version in the next months which should have not this issue. You'll have to wait until then, sorry.

**Comment by pven** [comment]
Thanks anyway! :-)

**Comment by bradmurray** [comment]
Is there any way to get around it on the user side? Reinstall? I get the error on my pi-based install all of the time for at least the last month and can't even use the service.

**Comment by theotherp** [comment]
You can try https://github.com/theotherp/nzbhydra/releases/tag/0.2.218 or
https://github.com/theotherp/nzbhydra/releases/tag/0.2.220
