### ISSUE TITLE
501 error going to "History & Stats" page

### ISSUE THREAD

**Issue by PearsonFlyer** [theotherp/nzbhydra#673]
Since the most recent update, I get this error after about 30 seconds when trying to navigate to the "History & Stats" page:

An error occured :
500: INTERNAL SERVER ERROR

results not ready, timed out.

I'm running on a Windows 10 (Creator's Update) box, no docker or anything.  Here is my log from when this issue is occurring:

2017-10-14 19:31:59,006 - ERROR - web - Thread-198314 - results not ready, timed out.
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "nzbhydra\web.py", line 474, in wrapped_function
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 1272, in internalapi_search_requests
  File "nzbhydra\stats.py", line 394, in get_search_requests
  File "site-packages\peewee.py", line 3077, in count
  File "site-packages\peewee.py", line 3070, in aggregate
  File "site-packages\peewee.py", line 2842, in scalar
  File "site-packages\playhouse\sqliteq.py", line 92, in fetchone
  File "site-packages\playhouse\sqliteq.py", line 51, in _wait
ResultTimeout: results not ready, timed out.
2017-10-14 19:31:59,209 - ERROR - search_module - Thread-198313 - altHUB: An error error occurred while searching: results not ready, timed out.
Traceback (most recent call last):
  File "nzbhydra\search_module.py", line 427, in execute_queries
  File "nzbhydra\search_module.py", line 374, in get_url_with_papi_access
  File "nzbhydra\search_module.py", line 295, in handle_indexer_success
  File "site-packages\peewee.py", line 3097, in get
  File "site-packages\peewee.py", line 2271, in next
  File "site-packages\peewee.py", line 2248, in iterate
  File "site-packages\playhouse\sqliteq.py", line 92, in fetchone
  File "site-packages\playhouse\sqliteq.py", line 51, in _wait
ResultTimeout: results not ready, timed out.
2017-10-14 19:32:30,648 - WARNING - api - Thread-198310 - results not ready, timed out., retrying in 1 seconds...

**Comment by theotherp** [comment]
Sorry for the super late response. I think you got an answer on reddit?

Anyway, this is an issue with Hydra that I'll probably never will be able to solve. It will be fixed in v2 which I plan to release soonish.

**Comment by theotherp** [comment]
Closing this. v2 is available and while not completely stable yet it doesn't have this issue.
