### ISSUE TITLE
Error while processing search results from indexer Binsearch

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#68]
FWIW, I just received this error about Binsearch in my console:

```python
2015-12-19 00:45:06,963 - ERROR - search_module - Error while processing search results from indexer Binsearch
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\search_module.py", line 257, in execute_queries
    parsed_results = self.process_query_result(request.content, query)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\searchmodules\binsearch.py", line 115, in process_query_result
    raise IndexerResultParsingException("Unable to find main table in binsearch page", self)
IndexerResultParsingException: Unable to find main table in binsearch page
```

And before that it spit out a bunch of HTML.  Here's a complete output from the console with the HTML included:

http://pastebin.com/XXTnDpP2

**Comment by theotherp** [comment]
Yeah, I need to lower that debug level to warn. It's both an error and not. Sometimes binsearch just returns the default search page, I'm not sure why, although to be honest haven't invested too much time to find out... It should work again later :-)

**Comment by albino1** [comment]
Yeah, it's an awfully panicked error with a screen full of HTML for such a small problem :)

**Comment by albino1** [comment]
Not sure if this is a continuation of the same problem or not, but thought I'd post it here just in case:

````python
2015-12-19 21:33:19,970 - ERROR - binsearch - Unable to find main table in binse
arch page: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
        <head>
                <meta http-equiv="Content-Type" content="text/html; charset=ISO-
8859-1">
                <meta name="revisit-after" content="3 days">
                <meta name="robots" content="index,follow,noarchive">
                <meta name="description" content="BinSearch.info Binary Usenet n
zb Search Engine">
                <meta name="keywords" content="usenet, search engine, nzb, binar
y, binaries, alt.binaries.boneless, alt.binaries.nl, indexing service">
                <title>keyword1 keyw...
2015-12-19 21:33:19,970 - ERROR - search_module - Error while processing search
results from indexer Binsearch
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\search_module.py", line 257, in
 execute_queries
    parsed_results = self.process_query_result(request.content)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\searchmodules\binsearch.py", li
ne 115, in process_query_result
    raise IndexerResultParsingException("Unable to find main table in binsearch
page", self)
````

This is using the latest NZBHydra, 0.0.1a38.
