### ISSUE TITLE
Parsing results failed on some indexers

### ISSUE THREAD

**Issue by pawi** [theotherp/nzbhydra#682]
Hi,

i have multiple indexers i query. However some of them are permanently disabled because of a xml parsing error. I use the linuxserver/hydra docker image.

Following are logs for an example query with one troubled indexer (3 out of 10 total) i have issues with. 
```
2017-11-17 09:35:38,503 - INFO - search_module - Thread-42 - Drunken Slug: Starting search
2017-11-17 09:35:38,506 - DEBUG - search_module - Thread-42 - Drunken Slug: Requesting https://api.drunkenslug.com/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&q=<NEEDLE> with timeout 20
2017-11-17 09:35:39,326 - DEBUG - search_module - Thread-42 - Drunken Slug: HTTP request to indexer completed in 820ms
2017-11-17 09:35:39,330 - DEBUG - search_module - Thread-42 - Drunken Slug: Successfully loaded URL https://api.drunkenslug.com/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&q=<NEEDLE>
2017-11-17 09:35:39,330 - DEBUG - search_module - Thread-42 - Drunken Slug: Started processing results
2017-11-17 09:35:39,360 - ERROR - search_module - Thread-42 - Drunken Slug: Error while processing search results from indexer Drunken Slug
Traceback (most recent call last):
  File "/app/hydra/nzbhydra/search_module.py", line 439, in execute_queries
    parsed_results = self.process_query_result(request.text, searchRequest)
  File "/app/hydra/nzbhydra/searchmodules/newznab.py", line 512, in process_query_result
    entries, total, offset = self.parseXml(xml_response, maxResults)
  File "/app/hydra/nzbhydra/searchmodules/newznab.py", line 537, in parseXml
    entry = self.parseItem(item)
  File "/app/hydra/nzbhydra/searchmodules/newznab.py", line 596, in parseItem
    elif attribute_name == "info" and self.settings.backend.lower() in ["nzedb", "nntmux"]:
AttributeError: 'NoneType' object has no attribute 'lower'
2017-11-17 09:35:39,419 - ERROR - search_module - Thread-42 - Drunken Slug: Access error: Error while parsing the results from indexer
2017-11-17 09:35:39,422 - INFO - search_module - Thread-42 - Drunken Slug: Disabling indexer temporarily due to access problems. Will be reenabled in 14 minutes
```

Edit: add indexer config
```
        {
            "showOnSearch": true, 
            "accessType": "both", 
            "audiobookCategory": null, 
            "animeCategory": null, 
            "userAgent": null, 
            "backend": null, 
            "downloadLimit": 5, 
            "comicCategory": null, 
            "score": 2, 
            "loadLimitOnRandom": null, 
            "type": "newznab", 
            "username": null, 
            "host": "<NOTIPADDRESSORDOMAIN:3380e32f89a6aca98a89e1a35e0f72b2>", 
            "search_ids": [
                "imdbid", 
                "rid", 
                "tmdbid", 
                "traktid", 
                "tvdbid", 
                "tvmazeid"
            ], 
            "password": null, 
            "categories": [], 
            "hitLimitResetTime": null, 
            "apikey": "<APIKEY:0c4e013d22666c1bda7f73a179ce0641>", 
            "hitLimit": 100, 
            "name": "Drunken Slug", 
            "enabled": true, 
            "preselect": true, 
            "magazineCategory": null, 
            "timeout": null, 
            "ebookCategory": null, 
            "searchTypes": [
                "movie", 
                "tvsearch"
            ]
        }, 
```
Trying the same query with Postman i get proper results (xml with over 20 items), the header information of the reply provide sane standards (type: text/xml;charset=UTF-8; encoding: gzip)

Any ideas what could be the cause?

**Comment by theotherp** [comment]
Your indexer config is not complete. Repeat the caps check from the config.

**Comment by pawi** [comment]
Mhm i thought after checking previous issues that i did that, maybe i didn't save it =/
Your are completely right it now works, sorry for bothering!

**Comment by theotherp** [comment]
No worries.
