### ISSUE TITLE
Unicode encode error

### ISSUE THREAD

**Issue by bxkx** [theotherp/nzbhydra#684]
Tried to pull a nzb through Sonarr, it failed with the following error in the NZBHydra log.
I think it is due to this special character in the name of the nzb/title: σ

 ```
ERROR - web - Thread-18 - 'ascii' codec can't encode character u'\u03c3' in position 5: ordinal not in range(128)
Traceback (most recent call last):
  File "/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/nzbhydra/nzbhydra/web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/nzbhydra/nzbhydra/web.py", line 992, in getnzb
    return extract_nzb_infos_and_return_response(args["searchresultid"], args["downloader"], args["internal"])
  File "/nzbhydra/nzbhydra/web.py", line 1066, in extract_nzb_infos_and_return_response
    return get_nzb_response(searchResultId)
  File "/nzbhydra/nzbhydra/api.py", line 289, in get_nzb_response
    response = send_file(bio, mimetype='application/x-nzb;', as_attachment=True, attachment_filename=filename, add_etags=False)
  File "/nzbhydra/libs/flask/helpers.py", line 510, in send_file
    filename=attachment_filename)
  File "/nzbhydra/libs/werkzeug/datastructures.py", line 1093, in add
    _value = _options_header_vkw(_value, kw)
  File "/nzbhydra/libs/werkzeug/datastructures.py", line 830, in _options_header_vkw
    for k, v in kw.items()))
  File "/nzbhydra/libs/werkzeug/http.py", line 212, in dump_options_header
    segments.append('%s=%s' % (key, quote_header_value(value)))
  File "/nzbhydra/libs/werkzeug/http.py", line 165, in quote_header_value
    value = str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03c3' in position 5: ordinal not in range(128)
```

**Comment by theotherp** [comment]
Sorry for the super late response. Has this happened again?

**Comment by bxkx** [comment]
Hi! It still happens when trying to downloading a file with that particular special character (probably with others as well?) but since I haven't come across that special character in any other nzbs than for one particular series it's not a big deal. though. :)
