### ISSUE TITLE
Unable to start on Windows 10 - 32 bit - The specified executable is not a valid application for this OS platform.

### ISSUE THREAD

**Issue by diepeterpan** [theotherp/nzbhydra#691]
Started with NZBHydraTray.exe

Then got the stack trace -

Running Windows 10 - 32 bit edition

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at SystemTrayApp.Window.startNzbHydraProcess(Boolean isRestart)
   at SystemTrayApp.Window.Window_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2115.0 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
NZBHydraTray
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/NzbHydra/NZBHydraTray.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2116.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2102.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by theotherp** [comment]
Please downgrade to 0.2.230 for now.

Am 21.12.2017 07:40 schrieb "diepeterpan" <notifications@github.com>:

**Comment by theotherp** [comment]
Does https://github.com/theotherp/nzbhydra/archive/0.2.230.zip work?

**Comment by diepeterpan** [comment]
I will give it a try and let you know.  Thx for the quick response.

**Comment by diepeterpan** [comment]
I did UNZIP 0.2.230 but there is no ".exe" in the zip 0.2.230.zip  Also tried 0.2.230 's files with the existing .exe's but same error.  Seems like the windows .exe's is only built for 64bit :-(  Can you make 32bit .exe's?

"Does https://github.com/theotherp/nzbhydra/archive/0.2.230.zip work?"

**Comment by theotherp** [comment]
Sorry, try that one: https://github.com/theotherp/nzbhydra-windows-releases/archive/556b9c89da3e4389c33166ca154b86f98f19d384.zip

**Comment by diepeterpan** [comment]
Nope, _"Sorry, try that one: https://github.com/theotherp/nzbhydra-windows-releases/archive/556b9c89da3e4389c33166ca154b86f98f19d384.zip"_ 's exe's also fail to run on Windows 10 32bit. Must be something in the code which is not 32bit compatible.

**Comment by diepeterpan** [comment]
I believe the problem is with - "nzbhydra.exe" spawned by the tray exe.  When launching "nzbhydra.exe" by itself gives windows 10 popup error - "This app can't run on your PC. To find a version for your PC, check with the software publisher." [Close] dialog.  Where is the source to "nzbhydra.exe", can I compile it myself?

**Comment by diepeterpan** [comment]
Looking at the manifest of nzbhydra.exe.manifest I seems to be compiled for 64bit only :-(

processorArchitecture="amd64"  must be "AnyCPU"

Can you compile a version that will run on any CPU; thus either 32bit or 64bit?

**Comment by theotherp** [comment]
That's hard, I don't compile it but rather use pyinstaller which openly
says that results will only work on the the same OS / architecture. I would
need to find a vm with 32 bit Windows. That will take a while.

Am 21.12.2017 2:53 nachm. schrieb "diepeterpan" <notifications@github.com>:

**Comment by diepeterpan** [comment]
An option is to just run pyinstaller under 32bit Phython.

https://github.com/pyinstaller/pyinstaller/issues/2359

"pyInstaller, (or py2exe or cxFreeze), embed the local copy of python,
and the required libraries, into the created package and the 32 bit
windows python installation is the same regardless of being installed on
a 32 bit or 64 bit machine."

**Comment by theotherp** [comment]
Right, that should be doable

Am 21.12.2017 3:51 nachm. schrieb "diepeterpan" <notifications@github.com>:

**Comment by theotherp** [comment]
Please try this file: 
[nzbhydra 0.2.231 x86.zip](https://github.com/theotherp/nzbhydra/files/1579902/nzbhydra.0.2.231.x86.zip)

Extract to your main folder, overwriting any existing files.

**Comment by diepeterpan** [comment]
Slow progress- installed in main folder but when I start **nzbhydra.exe** the process start (black windows appears) and then dies.  Don't seem to be any log files.

**Comment by theotherp** [comment]
When you open a console and start the process, what does it say?
