### ISSUE TITLE
Unable to browse for keystore file - 500 error

### ISSUE THREAD

**Issue by badamonis** [theotherp/nzbhydra#696]
Hey - attempting to enable SSL on Windows 10. When I hit the enable SSL toggle and the browse for the keystore file, I get the following 500 error:

An error occurred:
500: Internal Server Error

Path: /internalapi/config/folderlisting

Message: No message available

The following error is logged:

2018-01-06 23:03:26.034 ERROR --- [0.0-5076-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : [IP: 192.168.1.150] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at sun.awt.shell.Win32ShellFolder2.access$200(Unknown Source)
	at sun.awt.shell.Win32ShellFolder2$1.call(Unknown Source)
	at sun.awt.shell.Win32ShellFolder2$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by theotherp** [comment]
I think you're in the wrong project. Please recreate the issue: https://github.com/theotherp/nzbhydra2/issues/new

**Comment by theotherp** [comment]
In the meantime I will check it out.
