### ISSUE TITLE
NZBHydra Fatal Error

### ISSUE THREAD

**Issue by jodfie** [theotherp/nzbhydra#697]
You don't have to follow this template by the letter, just think about what you're trying to achieve ;-) 

I am on Mac OSX 10.12.6 running newest Chrome.
Everything was running fine for months maybe years now? until recently, I'm getting the below error whenever I start NZBHydra and then it shuts back down.

```
2018-01-09 00:54:12,715 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "nzbhydra.py", line 211, in run
    web.run(host, port, basepath)
  File "/Users/cardinalserver/NZBHydra/nzbhydra/web.py", line 1730, in run
    app.run(host=host, port=port, debug=config.settings.main.debug, threaded=config.settings.main.runThreaded, use_reloader=config.settings.main.flaskReloader)
  File "/Users/cardinalserver/NZBHydra/libs/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/Users/cardinalserver/NZBHydra/libs/werkzeug/serving.py", line 625, in run_simple
    inner()
  File "/Users/cardinalserver/NZBHydra/libs/werkzeug/serving.py", line 603, in inner
    passthrough_errors, ssl_context).serve_forever()
  File "/Users/cardinalserver/NZBHydra/libs/werkzeug/serving.py", line 506, in make_server
    passthrough_errors, ssl_context)
  File "/Users/cardinalserver/NZBHydra/libs/werkzeug/serving.py", line 440, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/Users/cardinalserver/NZBHydra/libs/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/Users/cardinalserver/NZBHydra/libs/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/Users/cardinalserver/NZBHydra/libs/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/Users/cardinalserver/NZBHydra/libs/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 48] Address already in use
2018-01-09 00:54:12,719 - INFO - nzbhydra - Dummy-3 - Exit registered. Stopping and closing database
2018-01-09 00:54:12,720 - INFO - nzbhydra - Dummy-3 - Database shut down
```

**Comment by theotherp** [comment]
The port is already in use, at it says. Make sure you're not running another instance of Hydra.
