### ISSUE TITLE
An error occured : 500: INTERNAL SERVER ERROR  indexer_search

### ISSUE THREAD

**Issue by DropbearNinja** [theotherp/nzbhydra#701]
Hi, I get the above error when trying to perform an internal search. But I've also been having problems with api from sonarr/radarr, so I think it might be happening for API too. 

I tried deleting log and database, following that i performed the search, and the entirey of the log is shown below.

> 2018-01-18 11:57:18,759 - ERROR - search - Thread-17 - Error while calling search module
Traceback (most recent call last):
  File "nzbhydra\search.py", line 561, in start_search_futures
  File "site-packages\concurrent\futures\_base.py", line 398, in result
  File "site-packages\concurrent\futures\thread.py", line 55, in run
  File "nzbhydra\search_module.py", line 139, in search
  File "nzbhydra\searchmodules\newznab.py", line 356, in get_search_urls
  File "nzbhydra\searchmodules\newznab.py", line 377, in addExcludedWords
AttributeError: 'NoneType' object has no attribute 'lower'
2018-01-18 11:57:22,118 - ERROR - web - Thread-17 - u'indexer_search'
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "nzbhydra\web.py", line 474, in wrapped_function
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 871, in internalapi_search
  File "nzbhydra\web.py", line 832, in startSearch
  File "nzbhydra\web.py", line 811, in process_and_jsonify_for_internalapi
  File "nzbhydra\api.py", line 177, in process_for_internal_api
KeyError: u'indexer_search'

My laymans examination of it seems to be related to converting excluded words to lower [case]?? I do have one excluded word 'xpost'...

attached log and settings for fun.
[nzbhydra-debuginfo-2018-01-18-12-06.zip](https://github.com/theotherp/nzbhydra/files/1641570/nzbhydra-debuginfo-2018-01-18-12-06.zip)

the only other thing to add is that it doesn't seem to be persistent. I dont know what exactly makes it start working again, but if i restart enough times, or do something, could be how im sitting at my chair for all i know, it will work normally for a bit, then just as randomly, start erroring again...

thanks theotherp, you really are a champion!

**Comment by DropbearNinja** [comment]
I turned my indexers all off and added back one by one, the error only occurs when usenet-crawler is activated... something wrong with UC's settings?

**Comment by theotherp** [comment]
The config for UC is incomplete. First try to delete it, save the config, add it again, let the caps check complete, save again, test again.
That should solve it.

If not: Shutdown Hydra, open the settings.cfg, search for the UV entry and set the "backend" entry to "nzedb".

**Comment by DropbearNinja** [comment]
Thanks theotherp, that seems to have fixed it!
