### ISSUE TITLE
Web interface loads with "Issued at claim (iat) cannot be in the future"

### ISSUE THREAD

**Issue by unlocalhost** [theotherp/nzbhydra#705]
The System is Running windows 7
Python Version is 2.7.14

* What do you expect to happen? What does happen? 
Upon loading NZB hydra upon reboot a browser window is opened.  Instead of getting my normal error I get a white screen with the text  "Issued at claim (iat) cannot be in the future".

From the python screen I get

2018-02-03 00:58:03,867 - INFO - indexers - MainThread - Activated indexer drunk
enslug
2018-02-03 00:58:03,868 - INFO - indexers - MainThread - Activated indexer nzbno
ob
2018-02-03 00:58:03,871 - NOTICE - nzbhydra - MainThread - Starting web app on 1
27.0.0.1:5075
2018-02-03 00:58:03,871 - INFO - nzbhydra - MainThread - Opening browser to http
://127.0.0.1:5075
2018-02-03 00:58:03,891 - INFO - web - MainThread - Running threaded server
2018-02-03 00:58:04,078 - ERROR - web - Thread-3 - Issued At claim (iat) cannot
be in the future.
Traceback (most recent call last):
  File "C:\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\NZBHydra\nzbhydra\web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "C:\NZBHydra\nzbhydra\web.py", line 563, in base
    getUserFromToken()  # Just see if the token is there
  File "C:\NZBHydra\nzbhydra\web.py", line 363, in getUserFromToken
    payload = jwt.decode(json.loads(payload), config.settings.main.secret)
  File "C:\NZBHydra\libs\jwt\api_jwt.py", line 75, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "C:\NZBHydra\libs\jwt\api_jwt.py", line 98, in _validate_claims
    self._validate_iat(payload, now, leeway)
  File "C:\NZBHydra\libs\jwt\api_jwt.py", line 129, in _validate_iat
    raise InvalidIssuedAtError('Issued At claim (iat) cannot be in'
InvalidIssuedAtError: Issued At claim (iat) cannot be in the future.

* Have you searched for this problem? 
In searching I found the some discussions related to the library but nothing pertaining to my specific issue.  I examined the code hoping it was a value I could manipulate.  

* Can the problem be reproduced? How?

The only change I made was adjusting the system time in between a reboot.  My suspicion is this is related to this after examining the code in api_jwt.py more closely.  Sadly that is about the extent of my programming knowledge NZB hydra is actually running as sickrage did a search while I was typing this.

**Set your log file level to debug, repeat the steps that cause the problem and post the debug info which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5075/nzbhydra/system/bugreport). If other tools are involved post their logs as well.**

Sadly I am unable to set my log level as the web interface is not loading and thus I cant make any changes here.  This is the log I am able to view

https://pastebin.com/0x49hVd4

The more information you provide up front the higher the chance that I can help you.

If I left anything out just ask

**Comment by theotherp** [comment]
Try deleting your hydra cookies: https://www.digitaltrends.com/computing/how-to-delete-cookies/

**Comment by unlocalhost** [comment]
Thank you for your help this worked.
