### ISSUE TITLE
Just started getting Unable to connect to indexer from Sonarr - In NZBHydra log says OperationalError: near "OFFSET": syntax error

### ISSUE THREAD

**Issue by slydog3333** [theotherp/nzbhydra#706]
I just started getting an error tonight from Sonarr that it can't connect to NZBHydra.

The debug log in NZBHydra shows:
2018-02-04 19:05:04,793 - DEBUG - web - Thread-3 - Call to method base
2018-02-04 19:05:04,795 - DEBUG - web - Thread-3 - Sending index.html
2018-02-04 19:05:07,186 - DEBUG - web - Thread-9 - Call to method internalapi_getversions
2018-02-04 19:05:07,186 - DEBUG - web - Thread-9 - Requiring auth for method internalapi_getversions
2018-02-04 19:05:07,187 - DEBUG - update - Thread-9 - C:\NZBHYD~1\nzbhydra.exe exists. Assuming this is a windows release
2018-02-04 19:05:07,187 - DEBUG - update - Thread-9 - Loading repository version from https://raw.github.com/theotherp/nzbhydra-windows-releases/master/version.txt
2018-02-04 19:05:07,233 - DEBUG - web - Thread-10 - Call to method base
2018-02-04 19:05:07,234 - DEBUG - web - Thread-10 - Sending index.html
2018-02-04 19:05:07,581 - DEBUG - web - Thread-13 - Call to method internalapi_getconfig
2018-02-04 19:05:07,581 - DEBUG - web - Thread-13 - Requiring auth for method internalapi_getconfig
2018-02-04 19:05:18,493 - DEBUG - web - Thread-16 - http://localhost:5075/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<APIKEY>&offset=0&limit=100
2018-02-04 19:05:18,494 - DEBUG - web - Thread-16 - API request: {u'minsize': None, u'raw': 0, u'attrs': None, u'query': None, u'rid': None, u'id': None, u'dbsearchid': None, u'category': None, u'group': None, u'author': None, u'imdbid': None, u'maxage': None, u'indexer': None, u'ep': None, u'maxsize': None, u'input': None, u'indexers': None, u'extended': True, u'offsets': None, u'season': None, u'minage': None, u'offset': 0, u'genre': None, 'apikey':<APIKEY>', u'episode': None, u'tvdbid': None, u'title': None, u'o': u'XML', u'cat': u'5030,5040', u'q': None, u'del': None, u't': u'tvsearch', u'limit': 100}
2018-02-04 19:05:18,494 - INFO - web - Thread-16 - API search request: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2018-02-04 19:05:18,505 - INFO - search - Thread-16 - Starting new search: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]
2018-02-04 19:05:19,502 - DEBUG - search - Thread-16 - 17492 search results stored in database
2018-02-04 19:05:19,503 - DEBUG - search - Thread-16 - Didn't find this query in cache or want to do a new search
2018-02-04 19:05:19,515 - DEBUG - search - Thread-16 - Did not pick anizb because it is not enabled for category TV HD
2018-02-04 19:05:19,516 - DEBUG - search - Thread-16 - Did not pick Binsearch because it is only enabled for internal searches
2018-02-04 19:05:19,516 - DEBUG - search - Thread-16 - Did not pick NZBIndex because it is only enabled for internal searches
2018-02-04 19:05:19,585 - DEBUG - search - Thread-16 - nzbtv.net has had 0 of a maximum of 9 API hits since 02:05
2018-02-04 19:05:19,586 - DEBUG - search - Thread-16 - Did not pick nzbtv.net because load limiting prevented it. Chances of this indexer being picked: 1/10
2018-02-04 19:05:20,157 - DEBUG - search - Thread-16 - DogNZB has had 2 of a maximum of 50 API hits since 02:05
2018-02-04 19:05:20,157 - DEBUG - search - Thread-16 - Picked DogNZB
2018-02-04 19:05:20,197 - ERROR - web - Thread-16 - near "OFFSET": syntax error
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 698, in api
  File "nzbhydra\web.py", line 772, in api_search
  File "nzbhydra\search.py", line 291, in search
  File "nzbhydra\search.py", line 199, in pick_indexers
  File "nzbhydra\search.py", line 133, in checkHitOrDownloadLimit
  File "site-packages\peewee.py", line 3173, in __len__
  File "site-packages\peewee.py", line 2242, in __len__
  File "site-packages\peewee.py", line 2238, in count
  File "site-packages\peewee.py", line 2285, in fill_cache
  File "site-packages\peewee.py", line 2271, in next
  File "site-packages\peewee.py", line 2248, in iterate
  File "site-packages\playhouse\sqliteq.py", line 92, in fetchone
  File "site-packages\playhouse\sqliteq.py", line 53, in _wait
OperationalError: near "OFFSET": syntax error

Manual searches in NZBHydra still work

Thanks for your help

**Comment by theotherp** [comment]
If you had posted the debug infos ZIP as requested I would be able to help you better. 

Anway, I guess you set the hit limit for one of your indexers lower than 1.

**Comment by slydog3333** [comment]
Thanks for your response.

Actually when posting a new thread your instructions don't ask for a zip file thought that might be what you're implying here:

**Set your log file level to debug, repeat the steps that cause the problem and post the debug info which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5075/nzbhydra/system/bugreport). If other tools are involved post their logs as well.**

Anyways, none of my indexers were set to less than 1. One of them was set to 1.

But I got the problem to go away by turning off all the indexers then back on.

Thanks for pointing me in the right direction and thanks for your work on this great program.
