### ISSUE TITLE
An error occured : 500: INTERNAL SERVER ERROR  indexer_search

### ISSUE THREAD

**Issue by antakar** [theotherp/nzbhydra#707]
* What do you expect to happen? What does happen? 
I am using main search box, whatever i enter as a search query, the same error message i get:
```
2018-02-07 12:07:24,546 - ERROR - web - Thread-30 - u'indexer_search'
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/NZBHydra/nzbhydra-master/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/share/CACHEDEV1_DATA/.qpkg/NZBHydra/nzbhydra-master/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/share/CACHEDEV1_DATA/.qpkg/NZBHydra/nzbhydra-master/nzbhydra/web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/NZBHydra/nzbhydra-master/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/NZBHydra/nzbhydra-master/nzbhydra/web.py", line 871, in internalapi_search
    searchResult = startSearch(search_request)
  File "/share/CACHEDEV1_DATA/.qpkg/NZBHydra/nzbhydra-master/nzbhydra/web.py", line 832, in startSearch
    return process_and_jsonify_for_internalapi(results)
  File "/share/CACHEDEV1_DATA/.qpkg/NZBHydra/nzbhydra-master/nzbhydra/web.py", line 811, in process_and_jsonify_for_internalapi
    results = process_for_internal_api(results)
  File "/share/CACHEDEV1_DATA/.qpkg/NZBHydra/nzbhydra-master/nzbhydra/api.py", line 177, in process_for_internal_api
    indexer_search_info = IndexerSearchSchema().dump(indexer_info["indexer_search"]).data
KeyError: u'indexer_search'
```
* Can the problem be reproduced? How?

I just run the search for anything with all defaults options.
[nzbhydra-debuginfo-2018-02-07-12-05.zip](https://github.com/theotherp/nzbhydra/files/1702967/nzbhydra-debuginfo-2018-02-07-12-05.zip)

**Comment by theotherp** [comment]
Your Usenet Crawler entry is not correct. Try clicking the caps check button in its config window. Save, search again. If that doesn't help delete it, save the database, add it again.

**Comment by antakar** [comment]
The problem is with https://www.usenet-crawler.com. I have re-created the indexer in hydra, and it keeps failing. It fails on capabilities checks:


Error testing capabilities
The capabilities of the indexer could not be checked. You can set the IDs manually. Refer to the Wiki for the IDs supported by some indexers.

You may repeat the check at any time to try again.

**Comment by theotherp** [comment]
Please post the new debug infos ZIP which should contain more information on what exactly went wrong.

**Comment by antakar** [comment]
Please see the latest logs.
[nzbhydra-debuginfo-2018-02-09-08-37.zip](https://github.com/theotherp/nzbhydra/files/1710251/nzbhydra-debuginfo-2018-02-09-08-37.zip)
