### ISSUE TITLE
History & Stats 500: INTERNAL SERVER ERROR ( version: 0.2.233  )

### ISSUE THREAD

**Issue by ajkis** [theotherp/nzbhydra#717]
From log
```
2018-04-11 07:04:38,121 - ERROR - web - MainThread - results not ready, timed out.
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "/opt/nzbhydra/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 1272, in internalapi_search_requests
    return jsonify(get_search_requests(page=args["page"], limit=args["limit"], sortModel=args["sortModel"], filterModel=filterModel, distinct=args["distinct"], onlyUser=False))
  File "/opt/nzbhydra/nzbhydra/stats.py", line 394, in get_search_requests
    total_requests = query.count()
  File "/opt/nzbhydra/libs/peewee.py", line 3077, in count
    return self.aggregate(convert=False) or 0
  File "/opt/nzbhydra/libs/peewee.py", line 3070, in aggregate
    return self._aggregate(aggregation).scalar(convert=convert)
  File "/opt/nzbhydra/libs/peewee.py", line 2842, in scalar
    row = self._execute().fetchone()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 51, in _wait
    raise ResultTimeout('results not ready, timed out.')
ResultTimeout: results not ready, timed out.
```

**Comment by ajkis** [comment]
Thanks, to be honest I did not even notice nzbhydra 2 was released.

**Comment by theotherp** [comment]
I meant to deprecate v1 and add a message to it for all users but haven't got around to do it.
