### ISSUE TITLE
500: INTERNAL SERVER ERROR  results not ready, timed out.

### ISSUE THREAD

**Issue by paulrumens** [theotherp/nzbhydra#720]
I have been using Hydra for ages on my Mac with no issues, I updated Mono for Sonarr then Hydra stopped working, I have no idea if this is related or not!

I scrubbed everything and started fresh. Now when I use Hydra I am getting this error:

An error occured :
500: INTERNAL SERVER ERROR

results not ready, timed out.

Here is what my logs say:

2018-06-24 12:25:54,710 - WARNING - search - Thread-27 - No indexers were selected for this search:
2018-06-24 12:26:09,395 - ERROR - web - Thread-26 - results not ready, timed out.
Traceback (most recent call last):
  File "/Applications/NZBHydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Applications/NZBHydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/NZBHydra/nzbhydra/web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "/Applications/NZBHydra/nzbhydra/web.py", line 1263, in internalapi_search_requestsforsearching
    searchRequests = get_search_requests(1, 20, sortModel=None, filterModel=filterModel, distinct=True, onlyUser=limitToUser)
  File "/Applications/NZBHydra/nzbhydra/stats.py", line 394, in get_search_requests
    total_requests = query.count()
  File "/Applications/NZBHydra/libs/peewee.py", line 3074, in count
    return self.wrapped_count(clear_limit=clear_limit)
  File "/Applications/NZBHydra/libs/peewee.py", line 3087, in wrapped_count
    return rq.scalar() or 0
  File "/Applications/NZBHydra/libs/peewee.py", line 2842, in scalar
    row = self._execute().fetchone()
  File "/Applications/NZBHydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/Applications/NZBHydra/libs/playhouse/sqliteq.py", line 51, in _wait
    raise ResultTimeout('results not ready, timed out.')
ResultTimeout: results not ready, timed out.

I tried deleting the flask_session folder

**Comment by theotherp** [comment]
Switch to nzbhydra 2.

**Comment by paulrumens** [comment]
Ha, yeah, fair point! I did try that, but couldn't get it to work. I installed the legacy version of Java, added the wrapper, and ran it I get:

server:~ user$ python /Users/user/Desktop/nzbhydra2-1/nzbhydra2wrapper.py 
Logging wrapper output to /Users/user/Desktop/nzbhydra2-1/data/logs/wrapper.log
2018-06-24 16:51:51,533  INFO - No file nzbhydra.yml found. Using 128M XMX
2018-06-24 16:51:51,534  INFO - Starting NZBHydra main process with command line: java -Xmx128M -DfromWrapper -XX:TieredStopAtLevel=1 -noverify -Xloggc:/Users/user/Desktop/nzbhydra2-1/data/logs/gclog-2018-06-24_16-51-51.log -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCCause -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=5M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/user/Desktop/nzbhydra2-1/data/logs -Dspring.output.ansi.enabled=ALWAYS -jar /Users/user/Desktop/nzbhydra2-1/lib/core-1.5.1-exec.jar --datafolder /Users/user/Desktop/nzbhydra2-1/data in folder /Users/user/Desktop/nzbhydra2-1
Unrecognized VM option '+PrintGCCause'
Could not create the Java virtual machine.
2018-06-24 16:51:51,651  ERROR - Main process shut down unexpectedly. If the wrapper was started in daemon mode you might not see the error output. Start Hydra manually with the same parameters in the same environment to see it

**Comment by theotherp** [comment]
Not sure what the legacy version of Java is. Please see the Readme on the
project page, I'm on my phone right now. A certain version of jdk or
openjdk is required.

The error in v1 is one I haven't been able to fix, once you encounter it
there's nothing you or I can do to fix it.

**Comment by paulrumens** [comment]
No worries, I'll stop here, and move over to the Hydra2 thread...
