### ISSUE TITLE
HydraTask4 causing SQL Crash

### ISSUE THREAD

**Issue by kamos69** [theotherp/nzbhydra#724]
OS: Ubuntu 16.04
Docker: Linuxserver.io version:- 78 Build-date:- July-27-2018-22:05:19-UTC

* What do you expect to happen? What does happen? 
NZBHYdra2 Crashes. I expect it to not crash.
* Have you searched for this problem? You don't have to answer, just make sure.
Yes. I can't find it anywhere.
* Can the problem be reproduced? How?
No. I have no clue how to reproduce it. It crashes randomly. Only thing that helps is if I restart the app.

```2018-07-30 15:55:13.807  WARN --- [     HydraTask4] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: null,
2018-07-30 15:55:13.807 ERROR --- [     HydraTask4] o.h.engine.jdbc.spi.SqlExceptionHelper   : [HydraTask4] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:100; busy:23; idle:0; lastwait:30000].,
2018-07-30 15:55:13.807 ERROR --- [     HydraTask4] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.,
,
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection,
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:431),
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373),
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:447),
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277),
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96),
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179),
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673),
	at org.nzbhydra.downloading.DownloadStatusUpdater$$EnhancerBySpringCGLIB$$5cc71624.checkQueueStatus(<generated>),
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source),
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
	at java.lang.reflect.Method.invoke(Method.java:498),
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65),
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54),
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81),
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511),
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection,
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692),
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602),
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1700),
	at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:48),
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:189),
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380),
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373),
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:447),
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277),
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96),
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179),
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673),
	at org.nzbhydra.downloading.DownloadStatusUpdater$$EnhancerBySpringCGLIB$$5cc71624.checkQueueStatus(<generated>),
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source),
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
Caused by: org.hibernate.exception.GenericJDBCException: Unable to acquire JDBC Connection,
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47),
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109),
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95),
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:90),
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:112),
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:230),
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:237),
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:214),
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:52),
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1512),
	at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:45),
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:189),
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380),
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373),
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:447),
Caused by: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [HydraTask4] Timeout: Pool empty. Unable to fetch a connection in 30 seconds, none available[size:100; busy:23; idle:0; lastwait:30000].,
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:706),
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198),
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132),
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122),
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:386),
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:87),
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:112),
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:230),
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:237),
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:214),
	at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:52),
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1512),
	at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:45),
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:189),
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:380),```

Please help.

**Comment by theotherp** [comment]
Please follow the instructions and post the debug infos ZIP.

**Comment by theotherp** [comment]
Huh, the instructions weren't correct because you posted on the project for NZBHydra v1. Please create a new issue on https://github.com/theotherp/nzbhydra2 and post the debug infos ZIP there.
