### ISSUE TITLE
Don't show the NZB icon if a downloader is not configured

### ISSUE THREAD

**Issue by Cozza38** [theotherp/nzbhydra#75]
Just a usability issue/feature request.

My wife was browsing through hydra last night and kept clicking the NZB Icon as it's the most obvious icon for downloading. 

I don't have a downloader configured so much confusion was had. If this you have any spare time, this would be great :)

**Comment by albino1** [comment]
Along these same lines it'd be nice if SABnzbd is configured to have a SABnzbd logo and if NZBGet is configured to have an NZBGet logo.  It's also then more clear what you're doing when you click on it.

Example usage from NZBM with the green one being chosen:

![al-nzbm-sabnzbdlogo](https://cloud.githubusercontent.com/assets/12164957/11923768/2a01caa0-a75d-11e5-86be-e4aecf592f09.jpg)

**Comment by Cozza38** [comment]
That's a great idea. I pulled the icons to save work if it goes ahead.

![nzbget](https://cloud.githubusercontent.com/assets/5052021/11923868/c57ee1c0-a7fd-11e5-999d-726eb2c3ec58.png)
![sabnzbdplus](https://cloud.githubusercontent.com/assets/5052021/11923869/c59b07ce-a7fd-11e5-8368-7f62bc4361c5.png)

**Comment by theotherp** [comment]
Huh, the first part was already implemented but got lost at some point... :-)

**Comment by albino1** [comment]
Just updated to 0.0.1a40 and I still don't have a SABnzbd icon, just the normal nzb icon.

I tried changing my Download Client to None, saving it, and running a search, but instead of no icons I have the default NZB icon which errors when you click it just like before.

Then I re-enabled SABnzbd, saved, and searched, and it still shows the default NZB icon and no SABnzbd icon, but works when I click on it sending the file to SAB.

**Comment by theotherp** [comment]
That's weird, it works fine on my home PC and on my dedi.

For me it looks like this 
![](http://i.imgur.com/GdFO59K.png) 
and this 
![](http://i.imgur.com/1lJlyQD.png)

Perhaps do a full refresh (Ctrl+F5) on the search page.

**Comment by albino1** [comment]
Don't know why I didn't think of that before, but yeah that worked.

Now I'm getting a new problem though were a bunch of my test files I passed to SABnzbd are having to WAIT with a timeout, and then eventually are erroring as Empty NZBs:

![al-sabnzbd-wait empty](https://cloud.githubusercontent.com/assets/12164957/11927064/81099564-a77e-11e5-9c82-5df9d80c67f2.jpg)

And:

![al-sabnzbd-wait empty2](https://cloud.githubusercontent.com/assets/12164957/11927195/948055d2-a77f-11e5-9818-652be142b2bf.jpg)

Also:

![al-sabnzbd-emptyerrors](https://cloud.githubusercontent.com/assets/12164957/11927163/69c45046-a77f-11e5-83fe-aec6277e8000.jpg)


At first I thought it was just a DOGnzb problem, but it's happening with Usenet Crawler, PFMonkey, 6box and NZBIndex too.  Most of them eventually are going through, but many of them aren't.  This wasn't happening before.  Can you think of anything that might have changed to cause that?

**Comment by theotherp** [comment]
Hmm... I didn't change anything in that regard. Could you download one of the "empty" NZBs using the shown link, open it with a text editor and check their content?

**Comment by albino1** [comment]
Looking through the logs, I think they're just timing out, so I'm not sure what's getting passed.  Examples:

````
2015-12-21 00:54:50,953 - INFO - web - API request to download Breaking.Bad.S01E01.720p.BluRay.x264.DTS-WiKi from DogNZB
2015-12-21 00:55:01,609 - ERROR - api - Error while connecting to URL https://api.dognzb.cr/api?apikey=<APIKEY>&t=get&id=2f9ddce37178d4890419b569d0e11340: HTTPSConnectionPool(host='dognzb.cr', port=443): Max retries exceeded with url: /fetch/2f9ddce37178d4890419b569d0e11340/dc45e19a22e05d69c2043a04d7659035 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000455AF60>, 'Connection to dognzb.cr timed out. (connect timeout=10)'))
2015-12-21 00:55:01,624 - ERROR - api - Error while trying to download NZB Breaking.Bad.S01E01.720p.BluRay.x264.DTS-WiKi from DogNZB
2015-12-21 00:57:21,072 - INFO - web - API request to download Breaking.Bad.S01E01.720p.BluRay.nHD.x264-NHANC3 from DogNZB
2015-12-21 00:57:41,056 - ERROR - api - Error while connecting to URL https://api.dognzb.cr/api?apikey=<APIKEY>&t=get&id=c86c692d4644b9215beea6523ead2f78: HTTPSConnectionPool(host='dognzb.cr', port=443): Read timed out. (read timeout=10)
2015-12-21 00:57:41,056 - ERROR - api - Error while trying to download NZB Breaking.Bad.S01E01.720p.BluRay.nHD.x264-NHANC3 from DogNZB
2015-12-21 00:59:46,153 - INFO - web - API request to download The.Writers.Room.S01E01.Breaking.Bad.720p.WEB-DL.AAC2.0.H.264 from DogNZB
2015-12-21 00:59:56,808 - ERROR - api - Error while connecting to URL https://api.dognzb.cr/api?apikey=<APIKEY>&t=get&id=8c0c61b3e91d9e12bfe4d2eeb0419fe2: HTTPSConnectionPool(host='dognzb.cr', port=443): Max retries exceeded with url: /fetch/8c0c61b3e91d9e12bfe4d2eeb0419fe2/dc45e19a22e05d69c2043a04d7659035 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000058EEDD8>, 'Connection to dognzb.cr timed out. (connect timeout=10)'))
2015-12-21 00:59:56,808 - ERROR - api - Error while trying to download NZB The.Writers.Room.S01E01.Breaking.Bad.720p.WEB-DL.AAC2.0.H.264 from DogNZB
2015-12-21 01:05:24,085 - INFO - web - API request to download breaking bad s01e01 720p bluray x264-reward mkv from 6box
2015-12-21 01:05:34,520 - ERROR - api - Error while connecting to URL https://6box.me/api?apikey=<APIKEY>&t=get&id=d859e7720f9d94db2255e1b8516db032: HTTPSConnectionPool(host='6box.me', port=443): Read timed out. (read timeout=10)
2015-12-21 01:05:34,520 - ERROR - api - Error while trying to download NZB breaking bad s01e01 720p bluray x264-reward mkv from 6box
2015-12-21 01:09:04,871 - INFO - web - API request to download The.Writers.Room.2013.S01E01.Breaking.Bad.720p.HDTV.x264-2HD from 6box
2015-12-21 01:09:15,292 - ERROR - api - Error while connecting to URL https://6box.me/api?apikey=<APIKEY>&t=get&id=6aa1148849b029d41edaba1c16ba2a39: HTTPSConnectionPool(host='6box.me', port=443): Read timed out. (read timeout=10)
2015-12-21 01:09:15,309 - ERROR - api - Error while trying to download NZB The.Writers.Room.2013.S01E01.Breaking.Bad.720p.HDTV.x264-2HD from 6box
````

I downloaded a couple of the "empty" NZBs using the error link in SAB, i.e.:

`http://123.45.67.89:5075/api?apikey=<API KEY>&t=get&id=(guid:'92825972',indexer:NZBIndex,searchid:35,title:sample-the.writers.room.2013.s01e01.breaking.bad.720p.hdtv.264-2hd)`

One from NZBIndex worked fine, one from 6box displayed a page with this error:

`Unable to download NZB`

Then when I reloaded it worked fine.

Sunday nights are notoriously bad for indexers, so maybe I just hit a bad stretch.  If it's continuing tomorrow I'll get back to you.

**Comment by theotherp** [comment]
Alright.

**Comment by albino1** [comment]
So I'm still getting it this morning.  I clicked on 10 NZBs from a variety of indexers and I got the WAIT with a timer countdown on Usenet Crawler, PFMonkey, OZnzb and NZBIndex.  9 eventually went through after the 60 second countdown went through once or twice.  Two initially failed with this error:

`ERROR: Saving E:\MKVs\incomplete\Breaking Bad - S01E01 - Pilot - 720p BluRay.par2 [01\__ADMIN__\Breaking Bad - S01E01 - Pilot - 720p BluRay.par2 [01/80] - "Breaking Bad - S01E01 - Pilot - 720p BluRay.par2".nzb.gz failed`

But somehow they got re-grabbed and got added.

Only 1 failed outright with the Empty NZB error:

`WARNING: Empty NZB file api?apikey=<api key>%26t=get%26id=(guid:!'31872662!',indexer:NZBClub,searchid:36,title:Breaking.Bad.S01E01-07.German.DL.720p.BluRay.x264-UTOPiA)',indexer:NZBClub,searchid:36,title:Breaking.Bad.S01E01-07.German.DL.720p.BluRay.x264-UTOPiA).nzb [http://123.45.67.89:5075/api?apikey=<api key>&t=get&id=(guid:'http://123.45.67.89:5075/api?apikey=<api key>%26t=get%26id=(guid:!'31872662!',indexer:NZBClub,searchid:36,title:Breaking.Bad.S01E01-07.German.DL.720p.BluRay.x264-UTOPiA)',indexer:NZBClub,searchid:36,title:Breaking.Bad.S01E01-07.German.DL.720p.BluRay.x264-UTOPiA)]`

It looks like in the Empty NZB error that URL is listed twice.  

I tried this URL from the error:

`http://123.45.67.89:5075/api?apikey=<api key>&t=get&id=(guid:'http://123.45.67.89:5075/api?apikey=<api key>%26t=get%26id=(guid:!'31872662!',indexer:NZBClub,searchid:36,title:Breaking.Bad.S01E01-07.German.DL.720p.BluRay.x264-UTOPiA)`

Which gives me the error:

`unknown literal: "!'"`

Then I tried this one:

`http://123.45.67.89:5075/api?apikey=<api key>%26t=get%26id=(guid:!'31872662!',indexer:NZBClub,searchid:36,title:Breaking.Bad.S01E01-07.German.DL.720p.BluRay.x264-UTOPiA)`

Which says:

```
Unauthorized

API key not provided or invalid
```

Any ideas?

**Comment by albino1** [comment]
I just performed the same test with NZBM and all 10 NZBs went through in significantly less time with no WAIT and no errors or warnings.

Is it possible that NZBHydra is getting overloaded by too many API requests at once?  Or trying to download too many NZBs at once?

**Comment by theotherp** [comment]
NZBHydra is only running with one thread all API requests will be queued. This might cause some of the connections from sabnzbd to nzbhydra to time out. 
I'd suggest that you choose to upload the NZBs to sabnzbd instead of sending the link so that nzbhydra handles the connections.

If you'd like you could also try to choose "Redirect to the indexer" as the NZB access type. If I understand correctly that's what nzbm does. That way most of the load will be delegated to the indexer.

In any case, I just tested sending 10 links to sabnzbd and it downloaded 10 NZBs in 56 seconds. It only requests one NZB at a time and pauses in between downloads.

**Comment by theotherp** [comment]
Tomorrow by this time I'll have left for holidays, so I won't be able to analyze this before january second or so.

**Comment by albino1** [comment]
> f you'd like you could also try to choose "Redirect to the indexer" as the NZB access type. If I understand correctly that's what nzbm does. That way most of the load will be delegated to the indexer.

Using this method and Send Link I added 10 NZBs from 10 indexers and all 10 failed with Empty NZB:

![al-sabnzbd-emptyerrors2](https://cloud.githubusercontent.com/assets/12164957/11941126/4d676718-a7e2-11e5-8cf3-e8e2d5d3ea21.jpg)

**Comment by theotherp** [comment]
Alright, no idea. Will get back to you in two weeks. Happy holidays ☺

**Comment by albino1** [comment]
Using `Use direct links` fails as well.  Judging from inside of SAB the actual links look identical to sending via proxy.

**Comment by theotherp** [comment]
Oh, does the log say anything?

**Comment by albino1** [comment]
Hmm, it doesn't show anything for any recent errors.  But I did find this from before:

````python
2015-12-21 11:19:41,210 - ERROR - web - unknown literal: "!'"
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 338, in api
    args = rison.loads(args["id"])
  File "C:\Program Files (x86)\NZBHydra\libs\rison\decoder.py", line 225, in loads
    return Parser().parse(s, format=format)
  File "C:\Program Files (x86)\NZBHydra\libs\rison\decoder.py", line 34, in parse
    value = self.read_value()
  File "C:\Program Files (x86)\NZBHydra\libs\rison\decoder.py", line 45, in read_value
    return self.parse_open_paren()
  File "C:\Program Files (x86)\NZBHydra\libs\rison\decoder.py", line 120, in parse_open_paren
    v = self.read_value()
  File "C:\Program Files (x86)\NZBHydra\libs\rison\decoder.py", line 43, in read_value
    return self.parse_bang()
  File "C:\Program Files (x86)\NZBHydra\libs\rison\decoder.py", line 94, in parse_bang
    raise ParserException('unknown literal: "!' + c + '"')
ParserException: unknown literal: "!'"
````

And these:

````python
2015-12-21 11:20:40,460 - ERROR - web - Tried API access with invalid or missing API key
2015-12-21 11:22:16,555 - ERROR - web - Tried API access with invalid or missing API key
````

**Comment by albino1** [comment]
Oh wait, here we go:

````python
2015-12-21 12:50:52,992 - WARNING - newznab - Indexer returned a result page without total results and offset. Shame! *rings bell*
2015-12-21 12:50:53,913 - INFO - binsearch - Last results count 0
2015-12-21 12:50:54,723 - WARNING - newznab - Indexer returned a result page without total results and offset. Shame! *rings bell*
2015-12-21 12:51:21,352 - INFO - web - API request to download The.Writers.Room.2013.S01E01.Breaking.Bad.720p.HDTV.x264-2HD from 6box
2015-12-21 12:51:21,352 - ERROR - web - Invalid value of nzbaccesstype: redirect
2015-12-21 12:51:27,921 - INFO - web - API request to download Breaking.Bad.S01E01.FRENCH.720p.BluRay.x264-JMT from PFMonkey
2015-12-21 12:51:27,921 - ERROR - web - Invalid value of nzbaccesstype: redirect
2015-12-21 12:51:32,960 - INFO - web - API request to download Breaking.Bad.S01E01.720p.BluRay.x264.DTS-WiKi from DogNZB
2015-12-21 12:51:32,960 - ERROR - web - Invalid value of nzbaccesstype: redirect
2015-12-21 12:51:37,999 - INFO - web - API request to download Breaking.Bad.S01E01.Der.Einstieg.-.Pilot.German.DL.720p.BluRay.x264-UTOPiA from Usenet Crawler
2015-12-21 12:51:37,999 - ERROR - web - Invalid value of nzbaccesstype: redirect
2015-12-21 12:52:09,089 - INFO - web - API request to download Breaking.Bad.S01E01-07.German.DL.720p.BluRay.x264-UTOPiA from NZBClub
2015-12-21 12:52:09,089 - ERROR - web - Invalid value of nzbaccesstype: redirect
2015-12-21 12:52:14,128 - INFO - web - API request to download The.Writers.Room.S01E01.720p.WEB-DL.AAC2.0.H.264 from OZnzb
2015-12-21 12:52:14,128 - ERROR - web - Invalid value of nzbaccesstype: redirect
2015-12-21 12:52:55,220 - INFO - web - API request to download sample-the.writers.room.2013.s01e01.breaking.bad.720p.hdtv.264-2hd from NZBIndex
2015-12-21 12:52:55,220 - ERROR - web - Invalid value of nzbaccesstype: redirect
2015-12-21 12:53:26,279 - INFO - web - API request to download Breaking.Bad.S01E01.720p.BluRay.x264-REWARD-Obfuscated from nzbgeek
2015-12-21 12:53:26,279 - ERROR - web - Invalid value of nzbaccesstype: redirect
2015-12-21 12:53:41,348 - INFO - web - API request to download Talking.Bad.S01E01.720p.HDTV.x264-2HD from Newztown
2015-12-21 12:53:41,348 - ERROR - web - Invalid value of nzbaccesstype: redirect
2015-12-21 12:55:42,561 - INFO - web - API request to download Breaking Bad - S01E01 - Pilot - 720p BluRay.par2 [01/80] - "Breaking Bad - S01E01 - Pilot - 720p BluRay.par2" from NZBFinder
2015-12-21 12:55:42,561 - ERROR - web - Invalid value of nzbaccesstype: redirect
````

**Comment by theotherp** [comment]
I did a commit 20 minutes ago or so that should fix that.

**Comment by theotherp** [comment]
When an error occurrs NZBHydra currently doesn't return a proper (error) status code but instead a HTML with an error message. Sabnzbd cannot parse that and will show the "empty NZB" error. 

The ! error I cannot explain, it shouldn't even be in the link.

Anyway, so it's a combination of several problems. I clearly still have a lot of work to do to get this run stable.

**Comment by albino1** [comment]
Updated, but the same errors:

````python
2015-12-21 13:08:19,868 - INFO - binsearch - Last results count 0
2015-12-21 13:08:20,815 - WARNING - newznab - Indexer returned a result page without total results and offset. Shame! *rings bell*
2015-12-21 13:09:08,405 - INFO - web - API request to download Breaking.Bad.S01E01.DVDRip.XviD-ORPHEUS from PFMonkey
2015-12-21 13:09:08,407 - ERROR - web - Invalid value of nzbaccesstype: direct
2015-12-21 13:09:39,457 - INFO - web - API request to download Ddlvalley Rocks Breaking Bad S01E01 Pilot 2160P Nf WEBRip Dts x264-ION from nzb.su
2015-12-21 13:09:39,457 - ERROR - web - Invalid value of nzbaccesstype: direct
2015-12-21 13:09:44,528 - INFO - web - API request to download NEW.Breaking.Bad.S01.E01.Pilot.UHD.4K.2160p.HDL[10of807]"Breaking.Bad.S01E01.Pilot.2160p.NF.WEBRip.DTS.x264-iON.mkv.009"yEnc from NZBIndex
2015-12-21 13:09:44,528 - ERROR - web - Invalid value of nzbaccesstype: direct
2015-12-21 13:09:49,566 - INFO - web - API request to download Breaking.Bad.S01E01 from NZBFinder
2015-12-21 13:09:49,566 - ERROR - web - Invalid value of nzbaccesstype: direct
2015-12-21 13:09:54,637 - INFO - web - API request to download Breaking.Bad.S01E01.DVDRip.XviD-ORPHEUS-Obfuscated from nzbgeek
2015-12-21 13:09:54,637 - ERROR - web - Invalid value of nzbaccesstype: direct
2015-12-21 13:10:01,782 - INFO - web - API request to download Breaking.Bad.S01E01.Pilot.German.WS.DVDRip.XviD-iNSPiRED from Usenet Crawler
2015-12-21 13:10:01,782 - ERROR - web - Invalid value of nzbaccesstype: direct
2015-12-21 13:10:06,819 - INFO - web - API request to download Home.Movies.S04E06.SDTV.Psycho-Delicate from OZnzb
2015-12-21 13:10:06,819 - ERROR - web - Invalid value of nzbaccesstype: direct
2015-12-21 13:10:11,858 - INFO - web - API request to download The.Writers.Room.2013.S01E01.Breaking.Bad.720p.HDTV.x264-2HD from 6box
2015-12-21 13:10:11,858 - ERROR - web - Invalid value of nzbaccesstype: direct
````

All NZBs fail with `WARNING: Empty NZB file`.

**Comment by albino1** [comment]
> Anyway, so it's a combination of several problems. I clearly still have a lot of work to do to get this run stable.

It's still usable now if I just stick with Proxy, so it sounds like a problem for after the vacation :)

**Comment by theotherp** [comment]
I meant "redirect"; not direct. But "direct" doesn't work either :-/

Over and out.

**Comment by albino1** [comment]
> I meant "redirect"; not direct. But "direct" doesn't work either :-/

Ah, yeah, I can confirm that redirect does mostly work now after that commit.  At least there are no `vInvalid value of nzbaccesstype` errors.
