### ISSUE TITLE
Fatal error / SSLContext  (Ubuntu 14)

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra#76]
Installed hydra on Ubuntu 14 LTE and it works great.
When I try to use SSL I get this error message

2015-12-21 09:55:59,700 - INFO - nzbhydra - Starting web app on 0.0.0.0:5075
2015-12-21 09:55:59,702 - INFO - nzbhydra - Opening browser to https://127.0.0.1:5075
2015-12-21 09:56:00,021 - ERROR - nzbhydra - Fatal error occurred
Traceback (most recent call last):
  File "nzbhydra.py", line 131, in run
    web.run(host, port)
  File "/opt/nzbhydra/nzbhydra/web.py", line 839, in run
    context = create_context()
  File "/opt/nzbhydra/nzbhydra/web.py", line 873, in create_context
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
AttributeError: 'module' object has no attribute 'SSLContext'

Tried the same settings, the same certs and the same version of hydra on my Raspberry Pi and it works.

**Comment by theotherp** [comment]
Yeah, after I copied all needed libraries to the libs subfolder so that it would run without external dependencies the SSL stuff got all whacky. I'll look into it, the last time I got frustrated and just stopped, I might have more patience now...

**Comment by theotherp** [comment]
Which python version?

**Comment by Hobbabobba** [comment]
I installed 2.7.11 manually, now it is working.
