### ISSUE TITLE
NZBIndex Errors

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#79]
I got these two NZBIndex errors tonight.  Here's the first:

```python
2015-12-28 00:37:01,905 - ERROR - search_module - Unable to access NZBIndex: The search service is temporarily unavailable.
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\search_module.py", line 253, in execute_queries
    self.check_auth(request.text)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\searchmodules\nzbindex.py", line 244, in check_auth
    raise IndexerAccessException("The search service is temporarily unavailable.", self)  # The server should return code 503 instead of 200...
IndexerAccessException: The search service is temporarily unavailable.
```

Which isn't a big deal, but the error itself could maybe be handled better.

And here's the second:

```python
2015-12-28 00:42:39,910 - ERROR - search_module - Error while processing search results from indexer NZBIndex
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\search_module.py", line 257, in execute_queries
    parsed_results = self.process_query_result(request.content)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\searchmodules\nzbindex.py", line 102, in process_query_result
    if "No results found" in html:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4582: ordinal not in range(128)
```

Which seems a bit more legit due to the ascii decoding error.

**Comment by theotherp** [comment]
I fucking hate encoding errors.
