### ISSUE TITLE
Unable to run in Windows with ActivePython

### ISSUE THREAD

**Issue by ScuttleSE** [theotherp/nzbhydra#89]
E:\nzbhydra>python nzbhydra.py
Traceback (most recent call last):
  File "nzbhydra.py", line 9, in <module>
    import requests
  File "E:\nzbhydra\libs\requests\__init__.py", line 58, in <module>
    from . import utils
  File "E:\nzbhydra\libs\requests\utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "E:\nzbhydra\libs\requests\compat.py", line 7, in <module>
    from .packages import chardet
  File "E:\nzbhydra\libs\requests\packages\__init__.py", line 29, in <module>
    import urllib3
  File "E:\nzbhydra\libs\urllib3\__init__.py", line 10, in <module>
    from .connectionpool import (
  File "E:\nzbhydra\libs\urllib3\connectionpool.py", line 40, in <module>
    from .request import RequestMethods
  File "E:\nzbhydra\libs\urllib3\request.py", line 6, in <module>
    from .filepost import encode_multipart_formdata
  File "E:\nzbhydra\libs\urllib3\filepost.py", line 8, in <module>
    from .fields import RequestField
  File "E:\nzbhydra\libs\urllib3\fields.py", line 2, in <module>
    import mimetypes
  File "E:\nzbhydra\libs\mimetypes.py", line 28, in <module>
    import posixpath
  File "E:\nzbhydra\libs\posixpath.py", line 19, in <module>
    from genericpath import _unicode
ImportError: cannot import name _unicode

**Comment by theotherp** [comment]
Use standard python.
