### ISSUE TITLE
Testing Newznab-indexers doesn't work

### ISSUE THREAD

**Issue by ScuttleSE** [theotherp/nzbhydra#90]
2016-01-10 12:10:26,480 - INFO - newznab - Testing connection for host https://m3.indexone.ch/
2016-01-10 12:10:28,634 - ERROR - web - check_auth() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "E:\nzbhydra-master\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\nzbhydra-master\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\nzbhydra-master\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "E:\nzbhydra-master\nzbhydra\web.py", line 184, in decorated
    return f(*args, **kwargs)
  File "E:\nzbhydra-master\nzbhydra\web.py", line 622, in internalapi_testnewznab
    success, message = test_connection(args["host"], args["apikey"])
  File "E:\nzbhydra-master\nzbhydra\searchmodules\newznab.py", line 109, in test_connection
    check_auth(r.text)
TypeError: check_auth() takes exactly 2 arguments (1 given)

Tried with multiple indexers, same result, searching works

**Comment by FailOPS** [comment]
Yup, I experience it also on a Debian Jessie System

**Comment by theotherp** [comment]
Already fixed on my machine, will be fixed with the next push to develop. Expect a release to master later today. Thanks for the report.

**Comment by albino1** [comment]
Testing the Newznab indexers still doesn't work for me using the latest https://github.com/theotherp/nzbhydra/commit/4ea26d579fcf72b87570b8d178ccfeb4a3ad489c.  When I click the button it starts to rotate and then stops.  Here's the subsequent error from the console:

```python
NameError: global name 'concurrent' is not defined
2016-01-10 17:28:51,082 - ERROR - web - global name 'concurrent' is not defined
Traceback (most recent call last):
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files (x86)\NZBHydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files (x86)\NZBHydra\libs\webargs\core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 208, in decorated
    return f(*args, **kwargs)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\web.py", line 677, in internalapi_testcaps
    result = check_caps(host, apikey)
  File "C:\Program Files (x86)\NZBHydra\nzbhydra\searchmodules\newznab.py", line 196, in check_caps
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(toCheck)) as executor:
NameError: global name 'concurrent' is not defined
```

**Comment by theotherp** [comment]
Well, I broke it again in the meantime :-/
